### ISSUE TITLE
Selecting QTGMC leaves "Access Violation" error in preview

### ISSUE THREAD

**Issue by razorThunder** [stax76/staxrip#1]

**Comment by stax76** [comment]
Thanks for reporting, at the moments I can't do much about this type of error because it's much likely not my code causing it, please post such errors here:

http://forum.doom9.org/showthread.php?t=172068

or here:

http://forum.doom9.org/showthread.php?t=168856

**Comment by stax76** [comment]
QTGMC does not work using AviSynth because off a slowdown problem but it works using VapourSynth.
