### ISSUE TITLE
KNLMeansCL 0.7+ causes crash on selecting filter

### ISSUE THREAD

**Issue by Ofekmeister** [stax76/staxrip#10]
OS: Windows 7 x64
Staxrip: 1.3.1.7

The long term releases (0.7+) of KNLMeansCL https://github.com/Khanattila/KNLMeansCL/releases makes stax crash when selecting/loading filter. However, they work fine when it's just python involved.

Attached picture shows successful loading of KNLMeansCL 0.7.2 x64 in terminal.

![cmd](https://github-cloud.s3.amazonaws.com/assets%2F9677399%2F10956969%2F159c0556-832e-11e5-81bf-f431082a85d2.PNG)

**Comment by stax76** [comment]
I tried it with 0.7.2 and both avs and vs without problems, what's your GPU?

**Comment by Ofekmeister** [comment]
Nvidia GeForce GTX 560M

**Comment by stax76** [comment]
What you can try is copying the OpenCL.dll file that comes with KNLMeansCL to the system directory (C:\Windows\System32).

**Comment by Ofekmeister** [comment]
Ok I got it ty. It appears 0.7+ requires very recent graphics drivers. Just fyi in case you plan on updating it in stax, 0.7+ does not work with Nvidia GT/GTX 500 series yet.

https://github.com/Khanattila/KNLMeansCL/issues/14
https://github.com/Khanattila/KNLMeansCL/issues/13

**Comment by Khanattila** [comment]
NVIDIA simply has no suitable drivers for GT/GTX 500 series.
Can you tell me that it is a stupid, because GT 640 is much slower than GTX 560, but it was released in 2012 as opposed to 2011.
