### ISSUE TITLE
Enhancement:  Don't stop batch processing on exception

### ISSUE THREAD

**Issue by Dave--G** [stax76/staxrip#100]
Adding an outer exception handler to StaxRip would allow processing to continue instead of crashing out:

In my case a batch of videos contained a single long file name, which caused processing to stop.  All other files were short and could have been processed.  Since each video is processed in isolation from others, trap/log/continue should work fine.  Global error conditions (out of free disk space for example) would just result in a big error log.  It should be easy to implement an exception handler that traps & appends errors to a log, then displays the log if it exists at the end of processing.

**Comment by stax76** [comment]
If I remember right then I added a timeout to close the exception dialog after 2 minutes to allow the job list to continue processing.

There is also some logic that shows a warning for long file names and to shorten temp paths. Please post a log file if it happens again.
