### ISSUE TITLE
Audio tracks are in the opposite order

### ISSUE THREAD

**Issue by burnchar** [stax76/staxrip#103]
When opening videos which contain multiple audio tracks, they are consistently in the opposite order of the source file:

![image](https://cloud.githubusercontent.com/assets/681802/18258503/39a15666-7394-11e6-99ac-3abc3db34e1b.png)

Notice ID3 should be the second track and ID2 should be the first.

**Comment by stax76** [comment]
I don't remember if it was fixed meanwhile, next build will first look for dtsma and thd files before it picks anything else, if it's still a issue please re-open it.
