### ISSUE TITLE
VC++ 2015 download link is invalid.

### ISSUE THREAD

**Issue by brucethemoose** [stax76/staxrip#104]
http://imgur.com/a/a8biL

To reproduce: uninstall VC++ 2015 runtimes, install older version from Microsoft's site, click on the download link in StaxRip. 

As a side note, this means I'm completely unable to use the StaxRip test build... which is unfortunate, as I could really use the AMD encoder. 

Is there a workaround? I'm trying to find the appropriate version myself, but the version straight from MS's site doesn't seem to be new enough.

**Comment by brucethemoose** [comment]
For reference, this is the latest version I could find online:

https://www.microsoft.com/en-us/download/details.aspx?id=52685

**Comment by brucethemoose** [comment]
Alright, fixed it by finding the newest runtimes.

If anyone else has this issue, working download link is here:

https://go.microsoft.com/fwlink/?LinkId=615460

**Comment by jhangyu** [comment]
Thanks for the link
It almost drive me crazy

**Comment by stax76** [comment]
I hope it works in the test build from today:

https://github.com/stax76/staxrip/blob/master/md/test-build.md
