### ISSUE TITLE
StaxRip's converting to HEVC problem: in the first playing, a few frames look terrible.

### ISSUE THREAD

**Issue by gigi7777** [stax76/staxrip#105]
StaxRip's converting to HEVC (H.265) problem: in the first playing, a few frames look terrible.
They're appear with a white transparent fuzzy screen on a few frames and after a while dissapeared.
What am I doing wrong?
What settings should I use?

**Comment by Brainiarc7** [comment]
Hello,

Before we can answer that question :

What encoder for HEVC are you using? Nvidia's NVENC? x265?
What encoder settings are you using? Attach a snippet from media info on
the output file with the observed issue.

And finally,Ill need information on your playback platform.
What GPU are you using?
Is hardware accelerated HEVC decode available?
What media player are you using?
You can provide a snippet from DXVAChecker from your system so we can
confirm.

Regards,

Brainiarc7.

**Comment by gigi7777** [comment]
Hו Brainiarc7,

Thank you for the quick response.

**Details**
------------
* HEVC Encoder: 2 pass - x265 (--pass 1 --bitrate 2500)

Media Info
------------
General
Complete name               : D:\zmpf\Downloads\drive-download-20160905T111828Z\The.Huntsman.Winters.War_StaxRip.mp4
Format                      : MPEG-4
Format profile              : Base Media
Codec ID                    : iso4 (iso4/hvc1/iso6)
File size                   : 83.9 MiB
Duration                    : 4 min
Overall bit rate mode       : Variable
Overall bit rate            : 2 694 kb/s
Encoded date                : UTC 2016-09-07 13:42:12
Tagged date                 : UTC 2016-09-07 13:42:12

Video
ID                          : 1
Format                      : HEVC
Format/Info                 : High Efficiency Video Coding
Format profile              : Main@L4@Main
Codec ID                    : hvc1
Codec ID/Info               : High Efficiency Video Coding
Duration                    : 4 min
Bit rate                    : 2 500 kb/s
Maximum bit rate            : 7 103 kb/s
Width                       : 1 920 pixels
Height                      : 800 pixels
Display aspect ratio        : 2.40:1
Frame rate mode             : Constant
Frame rate                  : 23.976 (24000/1001) FPS
Color space                 : YUV
Chroma subsampling          : 4:2:0
Bit depth                   : 8 bits
Bits/(Pixel*Frame)          : 0.068
Stream size                 : 77.8 MiB (93%)
Writing library             : x265 1.9+200-6098ba3e0cf16b11:[Windows][GCC 5.3.0][64 bit] 8bit+10bit+12bit
Encoding settings           : wpp / ctu=64 / min-cu-size=8 / max-tu-size=32 / tu-intra-depth=1 / tu-inter-depth=1 / me=1 / subme=2 / merange=57 / no-rect / no-amp / max-merge=2 / temporal-mvp / no-early-skip / recursion-skip / rdpenalty=0 / no-tskip / no-tskip-fast / strong-intra-smoothing / no-lossless / no-cu-lossless / no-constrained-intra / no-fast-intra / open-gop / no-temporal-layers / interlace=0 / keyint=250 / min-keyint=23 / scenecut=40 / rc-lookahead=20 / lookahead-slices=5 / bframes=4 / bframe-bias=0 / b-adapt=2 / ref=3 / limit-refs=3 / no-limit-modes / weightp / no-weightb / aq-mode=1 / qg-size=32 / aq-strength=1.00 / cbqpoffs=0 / crqpoffs=0 / rd=3 / psy-rd=2.00 / rdoq-level=0 / psy-rdoq=0.00 / no-rd-refine / signhide / deblock=0:0 / sao / no-sao-non-deblock / b-pyramid / cutree / no-intra-refresh / rc=2 / pass / bitrate=2504 / qcomp=0.60 / qpmin=0 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ipratio=1.40 / pbratio=1.30
Encoded date                : UTC 2016-09-07 13:42:12
Tagged date                 : UTC 2016-09-07 13:42:13

Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 4 min
Bit rate mode               : Variable
Bit rate                    : 192 kb/s
Maximum bit rate            : 200 kb/s
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 spf)
Compression mode            : Lossy
Stream size                 : 5.98 MiB (7%)
Language                    : English
Encoded date                : UTC 2016-09-07 13:01:45
Tagged date                 : UTC 2016-09-07 13:42:13

Platform & GPU
------------------
First Computer:
OS          : Windows 7 Professional
CPU         : Intel(R) Core(TM) i5-3470 CPU @ 3.20GHz
GPU         : NVIDIA NVS 310

Second Computer:
OS          : Windows 10 Home
CPU         : Intel(R) Core(TM) i7-5500U CPU @ 2.40GHz
GPU         : NVIDIA GeForce 840M


More Info
------------
Video:
Format                : MPEG-4
Format profile        : Base Media / Version 2
Codec ID              : mp42 (M4A /mp42/isom)
File size             : 6.03 MiB
Duration              : 4mn 21s
Overall bit rate mode : Variable
Overall bit rate      : 194 Kbps
Encoded date          : UTC 2016-09-07 13:01:45
Tagged date           : UTC 2016-09-07 13:01:56

Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : 40
Duration              : 4mn 21s
Bit rate mode         : Variable
Bit rate              : 192 Kbps
Maximum bit rate      : 205 Kbps
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 KHz
Frame rate            : 46.875 fps (1024 spf)
Compression mode      : Lossy
Stream size           : 5.98 MiB (99%)
Writing library       : Nero AAC codec 1.5.4.0
Encoding settings     : -cbr 192000
Encoded date          : UTC 2016-09-07 13:01:45
Tagged date           : UTC 2016-09-07 13:01:56

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
Encoding video using x265 1.9+200 x64 multi lib 8/10/12 bit
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

y4m  [info]: 1920x800 fps 24000/1001 i420p8 unknown frame count
raw  [info]: output file: NUL
x265 [info]: HEVC encoder version 1.9+200-6098ba3e0cf16b11
x265 [info]: build info [Windows][GCC 5.3.0][64 bit] 8bit+10bit+12bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2 AVX
x265 [info]: Main profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 4 threads
x265 [info]: frame threads / pool features       : 2 / wpp(13 rows)
x265 [info]: Coding QT: max CU size, min CU size : 64 / 8
x265 [info]: Residual QT: max TU size, max depth : 32 / 1 inter / 1 intra
x265 [info]: ME / range / subpel / merge         : hex / 57 / 2 / 2
x265 [info]: Keyframe min / max / scenecut       : 23 / 250 / 40
x265 [info]: Lookahead / bframes / badapt        : 20 / 4 / 2
x265 [info]: b-pyramid / weightp / weightb       : 1 / 1 / 0
x265 [info]: References / ref-limit  cu / depth  : 3 / on / on
x265 [info]: AQ: mode / str / qg-size / cu-tree  : 1 / 1.0 / 32 / 1
x265 [info]: Rate Control / qCompress            : ABR-2504 kbps / 0.60
x265 [info]: tools: rd=3 psy-rd=2.00 recursion-skip signhide tmvp
x265 [info]: tools: strong-intra-smoothing lslices=5 deblock sao stats-write
x265 [info]: frame I:     49, Avg QP:16.29  kb/s: 15530.35
x265 [info]: frame P:   1605, Avg QP:17.26  kb/s: 5100.42
x265 [info]: frame B:   4602, Avg QP:20.95  kb/s: 1425.04
x265 [info]: Weighted P-Frames: Y:14.3% UV:9.3%
x265 [info]: consecutive B-frames: 4.1% 2.5% 23.4% 51.3% 18.7%
encoded 6256 frames in 1724.83s (3.63 fps), 2478.45 kb/s, Avg QP:19.97



NVIDIA NVS 310
MPEG2_IDCT: DXVA2, SD / HD / FHD / 4K
MPEG2and1_VLD: DXVA2, SD / HD / FHD / 4K
MPEG2_VLD: DXVA2, SD / HD / FHD / 4K
MPEG2_A: DXVA1, SD / HD / FHD / 4K
MPEG2_C: DXVA1, SD / HD / FHD / 4K
MPEG1_VLD: DXVA2, SD / HD / FHD / 4K
VC1_VLD2010: DXVA2, SD / HD / FHD
VC1_VLD: DXVA2, SD / HD / FHD
VC1_IDCT: DXVA1/2, SD / HD / FHD
WMV9_IDCT: DXVA1/2, SD / HD / FHD
32FCFE3F-DE46-4A49-861B-AC71110649D5: DXVA2
H264_VLD_Stereo_Progressive_NoFGT: DXVA2, SD / HD / FHD / 4K
H264_VLD_Stereo_NoFGT: DXVA2, SD / HD / FHD / 4K
H264_VLD_NoFGT: DXVA2, SD / HD / FHD / 4K
1B81BE6A-A0C7-11D3-B984-00C04F2E73C5: DXVA2
H264_VLD_SVC_Scalable_Constrained_High: DXVA2, SD / HD / FHD / 4K
MPEG4pt2_VLD_Simple: DXVA2, SD / HD / FHD
MPEG4pt2_VLD_AdvSimple_NoGMC: DXVA2, SD / HD / FHD
9947EC6F-689B-11DC-A320-0019DBBC4184: DXVA2
B194EB52-19A0-41F0-B754-CC244AC1CB20: DXVA2
4B2E068F-396A-43DF-B86B-7DC6D2B6726A: DXVA1
312B6A3A-41DE-4A43-9C0F-FB3D5F0DFB9A: DXVA1


6CB69578-7617-4637-91E5-1C02DB810285: DXVA1/2, SD / HD / FHD / 4K / 8K
F9F19DA5-3B09-4B2F-9D89-C64753E3EAAB: DXVA1/2, SD / HD / FHD / 4K / 8K
ProgressiveDevice: DXVA1/2, SD / HD / FHD / 4K / 8K
BobDevice: DXVA1/2, SD / HD / FHD / 4K / 8K
SoftwareDevice: DXVA2, SD / HD / FHD / 4K / 8K


Interlace
95F4EDF4-6E03-4CD7-BE1B-3075D665AA52: DXVAHD, SD / HD / FHD / 4K / 8K
Progressive
95F4EDF4-6E03-4CD7-BE1B-3075D665AA52: DXVAHD, SD / HD / FHD / 4K / 8K


InputFormat
  0: A8R8G8B8
  1: X8R8G8B8
  2: AYUV
  3: YUY2
  4: NV12
  5: YV12
  6: P8
  7: A8P8
  8: AIP8
  9: AI44

OutputFormat
  0: A8R8G8B8
  1: X8R8G8B8
  2: YUY2
  3: NV12

DeviceType
  Hardware: Yes
  Software: -
  Reference: -
  Other: -

DeviceCaps
  LinearSpace: Yes
  xvYCC: Yes
  RGBRangeConversion: No
  YCbCrMatrixConversion: No

FeatureCaps
  AlphaFill: No
  Constriction: Yes
  LumaKey: Yes
  AlphaPalette: Yes

FilterCaps
  Brightness: Yes
  Contrast: Yes
  Hue: Yes
  Saturation: Yes
  NoiseReduction: Yes
  EdgeEnhancement: Yes
  AnamorphicScaling: Yes

InputFormatCaps
  RGBInterlaced: No
  RGBProcAmp: No
  RGBLumaKey: Yes
  PaletteInterlaced: No

VideoProcessorCount: 1

MaxInputStreams: 5

MaxStreamStates: 5

PastFrames: 2

FutureFrames: 1

ProcessorCaps
  DeinterlaceBlend: Yes
  DeinterlaceBOB: Yes
  DeinterlaceAdaptive: Yes
  DeinterlaceMotionCompensation: No
  InverseTelecine: Yes
  FrameRateConversion: No

InverseTelecineCaps
  32: No
  22: No
  2224: No
  2332: No
  32322: No
  55: No
  64: No
  87: No
  222222222223: No
  Other: No

CustomRate: -


* Hardware accelerated HEVC decode available, other encoded files from HandBrake and Avidemux look perfect.
* I'm using PotPlayer 64bit

Screenshots of PotPlayer
----------------------------
https://drive.google.com/open?id=0B7u5g9lX6l5AWnV0T3V1QWZPeXc
https://drive.google.com/open?id=0B7u5g9lX6l5AX3lwSWswRDZxaXM


Thanks,
gigi7777

**Comment by Brainiarc7** [comment]
I see.

So far, you have only listed the platform capabilities of the Nvidia NVS 310, which by my understanding does not have HEVC decode acceleration in hardware
The GTX 840M can do partial HEVC hardware accelerated decode (based on the Nvidia Maxwell GM108 SM).

Can you repeat this with another media player?

I'd recommend Windows media player with the K-Lite Mega codec pack installed to test for artifacts. 
Also repeat playback with VLC on both platforms and confirm if said artifacts are repeated.
This should rule out media player issues should it only be observed in specific media players and not others.

Regards,

Brainiarc7

**Comment by gigi7777** [comment]
Hi,

I'm watching HEVC movies on Chinese computer - CENOVO, not so strong but with PotPlayer it's doing his job. These movies which converted by HandBrake work great but it looks a little discolored to me, good result but not enough. Avidemux did a great job, the results are amazing and it's work with no problems. And then wanted to test StaxRip and to compare it to Avidemux, the results are roughly similar, but only the short startup with the washed white frames (as it seen in the images) a little bit annoying. If the movie continue to run there's no problem and everything is fine. If I want to search by frame then I can't see anything and it's a shame.
I checked it with VLC and the film got stuck and faltering. I checked WMP and it's look fine but it's a very poor program.
Something in my encoding is not right, and I'll be happy to find out and fix it, and set a high standard for the other versions.
I suspect that something in my encoding have a wrong parameter or too high and that weighs heavily on the playing and I want to know what it is and if it should be canceled or changed.

Thanks,
Gigi7777

**Comment by gigi7777** [comment]
Hi,

I'm watching HEVC movies on Chinese computer - CENOVO, not so strong but with PotPlayer it's doing his job. These movies which converted by HandBrake work great but it looks a little discolored to me, good result but not enough. Avidemux did a great job, the results are amazing and it's playing with no problems. And then I wanted to test StaxRip and to compare it to the other programs, the results are roughly similar to Avidemux, but only the short start with the washed white frames (as it seen in the images through the links) a little bit annoying. If the movie continue to run there's no problem and everything is fine. If I want to search a scene by a frame then I can't see anything and it's a shame.
I checked it with VLC and the film got stuck and faltering and it's very frustrating. I checked WMP and it's look fine but it's a very poor program.
Something in my encoding is not right, and I'll be happy to find out and fix it, and set a high standard for the other versions.
I suspect that something in my encoding have a wrong parameter or too high and that weighs heavily on the playing and I want to know what it is and if it should be canceled or changed.

Thanks,
gigi7777

**Comment by Arcanemagus** [comment]
@gigi7777 That sounds more like an issue with the player you are using not properly decoding the video...

**Comment by gigi7777** [comment]
Maybe it's the combination of the player and the decoded type. The Avidemux file played in PotPlayer smoothly and looks great with high quality.
I'll wait for improvements in the new versions of the encoding software and the player.

**Comment by stax76** [comment]
You can also use LAV Filters with PotPlayer I think.
