### ISSUE TITLE
Subtitle Hardcode Problem

### ISSUE THREAD

**Issue by t0welie** [stax76/staxrip#106]
Hello all im having some issues with hardcoded subtitles and i thought this would be the best place to find help since google hasnt helped me much im using the latest stable release of staxrip and for some reason once i start the encode all seems fine but it only encodes like 4 mins of the video then quits it doesnt finish the entire video file any help on this matter would be awesome cause ive googled and tried everything ive come across/read and this is driving me nuts i used Ripbot to try encoding with my same settings and it works but some of the images in the subtitles arent correctly displayed a box that covers up jap writing and displays english only shows half the image EXAMPLE: https://s13.postimg.org/nodu6a0c7/example1.png and some dont display correctly at all EXAMPLE2: https://s13.postimg.org/cw7l6v7c7/example2.png any info needed etc just let me know and i can provide the subtitles are in ASS format here is the media info of the file im trying to encode im also trying to encode it to HEVC x265 10bit at CRF 20 audio is going to HE-AAC 2.0 Channel 82kb/s any help is much appreciated as i said earlier this is driving me nuts

General
Unique ID                                : 183505957801068014824369250427912724644 (0x8A0DF63FC0197CE8935BC7EFAF8620A4)
Complete name                            : C:\Users\Rukia\Downloads[xweel] Prison School [BD 1080p 10bit FLAC]\Prison School - 02 (BD 1920x1080 x264 10bit FLAC) [C4E58ABF].mkv
Format                                   : Matroska
Format version                           : Version 4 / Version 2
File size                                : 1.66 GiB
Duration                                 : 24 min 40 s
Overall bit rate mode                    : Variable
Overall bit rate                         : 9 621 kb/s
Encoded date                             : UTC 2016-03-14 22:47:23
Writing application                      : mkvmerge v8.9.0 ('Father Daughter') 32bit
Writing library                          : libebml v1.3.3 + libmatroska v1.4.4
Attachments                              : BigNoodleTitling.ttf / Bodoni Bk BT Book.ttf / Bodoni SvtyTwo OS ITC TT Bold.TTF / Bolton.ttf / Book Antiqua Bold.TTF / Boom Tank.ttf / Brain Flower Euro.ttf / BrushType-SemiBold.ttf / Calibri Light.ttf / Cambria.ttc / Capture it.ttf / Cartoonist Kooky.ttf / Century Schoolbook.ttf / ChicChalk.otf / Collegiate.ttf / Compass Bold.ttf / Constantia Bold.ttf / COUTURE Bold.ttf / DHF Semangat 2012 Demo.ttf / DJB My Mood Ring Says Blah.ttf / DK Liquid Embrace.ttf / Edo SZ.ttf / Encode Sans Compressed.ttf / Encode Sans Condensed Bold.ttf / Eras Bold ITC.ttf / ExpresswayRg-Regular.ttf / Felt Tip Roman.ttf / FeltTipRoman.ttf / FSO incompetent apprentice.ttf / Gentium Book Basic Bold Italic.ttf / Gentium Book Basic Bold.ttf / Helvetica Neue LT Com 45 Light.ttf / Helvetica Neue LT Com 55 Roman.ttf / Helvetica Neue LT Com 67 Medium Condensed.ttf / Helvetica Neue LT Com 75 Bold.ttf / Helvetica Neue LT Com 85 Heavy.ttf / Helvetica Neue LT Com 87 Heavy Condensed.ttf / Helvetica World Bold.ttf / HelveticaLTStd-Blk.otf / HelveticaLTStd-Bold.otf / HelveticaLTStd-FractionBold.otf / HelveticaRoundedLTStd-Bd.otf / Janda Manatee Solid.ttf / LeviBrush.TTF / Mortal Kombat 5.ttf / Resurrection.TTF / Scotosaurus.ttf / Seven Monkey Fury BB.ttf / squeaky chalk sound.ttf / Times New Roman.ttf / tom script.ttf / Universal Serif.ttf / AA_amakara_sample.ttf / Aharoni Bold.ttf / Arial Black.ttf / Arial Bold.ttf / ArtificeSSK.ttf / Bebas.TTF / BellCentennialStd-BdListing.otf / BellGothicStd-Black.otf

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High 10@L4.1
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Duration                                 : 24 min 40 s
Bit rate mode                            : Variable
Bit rate                                 : 8 024 kb/s
Maximum bit rate                         : 150 Mb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate mode                          : Constant
Frame rate                               : 23.976 (24000/1001) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 10 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.161
Stream size                              : 1.38 GiB (83%)
Writing library                          : x264 core 148 r2638 7599210 [L-SMASH]
Encoding settings                        : cabac=1 / ref=4 / deblock=1:0:0 / analyse=0x3:0x133 / me=esa / subme=9 / psy=1 / psy_rd=2.00:0.00 / mixed_ref=1 / me_range=24 / chroma_me=1 / trellis=2 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=0 / chroma_qp_offset=-2 / threads=6 / lookahead_threads=1 / sliced_threads=0 / nr=0 / decimate=0 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=2 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=4 / scenecut=40 / intra_refresh=0 / rc_lookahead=60 / rc=crf / mbtree=1 / crf=15.0 / qcomp=0.60 / qpmin=0 / qpmax=81 / qpstep=4 / vbv_maxrate=150000 / vbv_bufsize=150000 / crf_max=0.0 / nal_hrd=vbr / filler=0 / ip_ratio=1.40 / aq=1:1.00
Default                                  : Yes
Forced                                   : No
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio
ID                                       : 2
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Codec ID                                 : A_FLAC
Duration                                 : 24 min 40 s
Bit rate mode                            : Variable
Bit rate                                 : 1 492 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 10.417 FPS (4608 spf)
Bit depth                                : 24 bits
Stream size                              : 263 MiB (16%)
Writing library                          : Lavf55.19.100
Default                                  : Yes
Forced                                   : No

Text
ID                                       : 3
Format                                   : ASS
Codec ID                                 : S_TEXT/ASS
Codec ID/Info                            : Advanced Sub Station Alpha
Duration                                 : 24 min 30 s
Bit rate                                 : 30.9 kb/s
Count of elements                        : 30576
Compression mode                         : Lossless
Stream size                              : 5.42 MiB (0%)
Title                                    : Chihiro
Language                                 : English
Default                                  : Yes
Forced                                   : No

Menu
00:00:00.000                             : en:Introduction
00:00:44.419                             : en:Opening
00:02:14.009                             : en:Part A
00:15:39.021                             : en:Part B
00:23:00.004                             : en:Ending
00:24:30.052                             : en:Preview

**Comment by t0welie** [comment]
also dunno if it matters but i installed all the fonts used as attachments in the file still no difference

**Comment by dhimanAdhikari** [comment]
I am encoding Charlotte BD 720p [GJM-Mezashite] and some episodes have the same problem although this is the very first time I've ever encountered a problem with StaxRip.

I choose to hardcode subs (personally) and this was a rather unpleasant error encoding only the first couple minutes in my case. However, when choosing not to hard-sub no errors pop up and the encode seems to be working. Currently, I am testing the rest of the episodes to check out the problem more.

**Comment by stax76** [comment]
In the latest test build you can try vapoursynth, staxrip supports two different ASS renderers for vapoursynth, it will show a dialog asking which renderer to use.
