### ISSUE TITLE
HEVC encoding use only 50% of all cpu cores

### ISSUE THREAD

**Issue by nikolakhs** [stax76/staxrip#107]
I'm using latest stable StaxRip version on Windows 8.1 and Intel i7 1st generation. While encoding I see x265.exe is using only 50% of every cpu core.

Log:
x265 [info]: HEVC encoder version 1.9+200-6098ba3e0cf16b11
x265 [info]: build info [Windows][GCC 5.3.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x265 [info]: Main 10 profile, Level-4.1 (Main tier)

**Comment by burnchar** [comment]
This has nothing to do with StaxRip and everything to do with x265's settings (and possibly version -- 2.0 is out). Look at the x265 docs here: http://x265.readthedocs.io/en/default/cli.html
