### ISSUE TITLE
Nvenc Hevc isnt encoding

### ISSUE THREAD

**Issue by Joly0** [stax76/staxrip#11]
I am using a Nvidia Geforce GTX 860M and tried everything i can do, but i cant encode a Video with Nvenc hevc encoder dont know why. http://pastebin.com/xTNigUaz

**Comment by Joly0** [comment]
btw th same dont work with intel h265 i have a intel core i7 4720 so its a maxwell which should support quick sync?

**Comment by stax76** [comment]
NVIDIA h265 encoding requires Maxwell second generation, Intel h265 encoding requires Skylake.
