### ISSUE TITLE
Minor glitch: Clicking "English" on subtitles does not deselect non-English

### ISSUE THREAD

**Issue by burnchar** [stax76/StaxRip#110]
Clicking "English" in the subtitle selection menu selects English subtitles, but I would expect it to set subtitle selection to only those subtitles, including deselection of Spanish, German, etc.

**Comment by stax76** [comment]
I'm not sure what's the best approach for everybody.

**Comment by burnchar** [comment]
I did not understand that this was by design. Since it sounds like this is not a bug, I will close the ticket. Thank you very much, as always, for your work.
