### ISSUE TITLE
Abandoned project?

### ISSUE THREAD

**Issue by Druhl** [stax76/staxrip#113]
Is it safe to say with the author(s) not having been on in months this is likely abandoned?

It has been my favourite encoding GUI for some time but I've been waiting/hoping for a build to come out with ffmpeg NVENC 2-pass support. I know ffmpeg supports this but not within the last StaxRip build. I am not a coder or would modify my own.

Just a selfish user.  :)

**Comment by MakuSensei** [comment]
hopefully not leave this excellent project

StaxRip is much better than MeGUI

**Comment by stax76** [comment]
Chances I'll continue are good. :)

**Comment by tracker1** [comment]
Would love to see proper 2-pass as well... I've been really happy with staxrip myself... and just found out my GTX 1080 supports running two encodes at a time... :-)  start in new process twice, then feed the job queue, been very happy once I finally tweaked in the nv encode where I wanted it...

**Comment by stax76** [comment]
I can probably add it but would need command line examples.

**Comment by stax76** [comment]
Since staxrip won't be abandoned I'm closing the issue now.
