### ISSUE TITLE
Error Encoding video using x264 r2705 8-Bit x64

### ISSUE THREAD

**Issue by MakuSensei** [stax76/staxrip#114]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      Error Encoding video using x264 r2705 8-Bit x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Encoding video using x264 r2705 8-Bit x64 failed with exit code: 255 (0xFF)

The exit code might be a system error code: Una operación anterior completó la acción solicitada.

The exit code might be a system error code: Los atributos extendidos no son consistentes.

avs [info]: 1280x720p 0:0 @ 2997/125 fps (cfr)
x264 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x264 [info]: profile High, level 4.0

Start:    11:46:09 p. m.
End:      11:46:09 p. m.
Duration: 00:00:00

**Comment by stax76** [comment]
Please post the full log file.
