### ISSUE TITLE
Error encoding with Nvidia.h.265 

### ISSUE THREAD

**Issue by Microbone** [stax76/staxrip#115]
Hi there

unable to encode with Nvidia.h.265 /NVEncC (avcuvid cuda).
Used to work like a charm...

Tried both 2.07v2 and 3.01 version...

Tried both newest release and 1.3.8.8-test - same result.

Error Encoding using NVEncC 2.07v2 x64

Encoding using NVEncC 2.07v2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

avcuvid: codec
avcuvid: unable to decode by cuvid.
Failed to open input file.

StaxRip.ErrorAbortException: Encoding using NVEncC 2.07v2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

avcuvid: codec
avcuvid: unable to decode by cuvid.
Failed to open input file.

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 240
   at StaxRip.NVIDIAEncoder.Encode() in D:\Projekte\VS\VB\StaxRip\Encoding\NVIDIAEncoder.vb:line 80
   at StaxRip.MainForm.Encode() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2220
   at StaxRip.MainForm.RunJobRecursive() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 3462

/cheers

**Comment by deinlandel** [comment]
Same error

**Comment by Microbone** [comment]
At that point I was using newest release of nvidia drivers. Waited for next release and after updating the drivers the problem was gone!
