### ISSUE TITLE
Unicode filenames are not supported by AviSynth

### ISSUE THREAD

**Issue by ming-hai** [stax76/staxrip#117]
Unicode filenames are not supported by AviSynth.

VapourSynth supports unicode, it can be enabled at:

Filters > Filter Setup > VapourSynth

Unicode filenames are  supported by MeGUI.

**Comment by stax76** [comment]
What does the avs script look like?

**Comment by Nan-c** [comment]
I have the same problem.


Unicode filenames are not supported by AviSynth.

VapourSynth supports unicode, it can be enabled at:

Filters > Filter Setup > VapourSynth

Did you find an answer?
