### ISSUE TITLE
Request (please) for RGB filter

### ISSUE THREAD

**Issue by 44vince44** [stax76/staxrip#119]
This is a request, dunno where to put it, and sorry for posting it if it's the wrong place.
Staxrip is now more than complete for many encoding tasks. However an RGB filter (R, G B multiplication and offset) can be useful. Is this planned in dev ? Thank you Stax76

**Comment by stax76** [comment]
Sorry for not responding earlier. This tracker is the best place for feature request. For filter requests I need to know the name of the filter.

**Comment by 44vince44** [comment]
Sorry Stax I didn't know where to post such request. Anyway, the filter is an internal Avisynth filter called:
"**RGBAdjust**"  ( http://avisynth.nl/index.php/RGBAdjust  )

It has many parameters, but some of them can be hardcoded so only remain the most used ones:
RGBAdjust(clip clip [, 
      float r, float g, float b, float a, 
      float rb, float gb, float bb, float ab, 
      float rg, float gg, float bg, float ag, 
      bool analyze, bool dither ] ) 

If don't know if the fact that there are many parameters is a problem. Thank you Stax for all.

**Comment by stax76** [comment]
There was some negative feedback because of performance and memory lately, the menu has already a lot menu items, you can create your own filter profile easily however, right click the filters menu and select 'Profiles...' and add something like:

RGBAdjust = RGBAdjust(r = 1, g = 1, b = 1)

**Comment by 44vince44** [comment]
Thank you for the tip, i'll try it. Indeed, if there are performance and memory issues, it's maybe preferable not to include it... thanks Stax76
