### ISSUE TITLE
Unable to Remove Filter

### ISSUE THREAD

**Issue by vanontom** [stax76/staxrip#12]
The latest StaxRip beta seems to have a problem removing filters. I am unable to remove any filters as usual, by right-clicking and selecting Remove, or by pressing Delete on the filter. This is a fresh StaxRip install, portable-style (no special place, settings in same folder).

Have not encountered this problem before. Previously had 1.3.1.5 Beta installed (and many others, in Program Files, settings in AppData/Roaming) with no problems. I see the GitHub Wiki Changelog has some Test builds that I will now try. Thank you for your work on StaxRip, it's been invaluable for years.

StaxRip 1.3.1.7 Beta
Windows 10 Pro x64

Update: Yes, this is actually fixed in the latest Test build (2015-10-24).

**Comment by stax76** [comment]
Sorry about the late reply, yes, it's fixed in the test build, thanks for the report.
