### ISSUE TITLE
Auto load nnedi plugin when using nnedi3_rpow2 function please

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#120]
Hello Stax, 

When creating a custom filter using _nnedi3( )_ the line to load the nnedi3 plugin is automatically added into the avs script.

Will it be possible to add this too when the **nnedi3_rpow2( )** function of _nnedi3_  is used in a custom made filter please ? 

For example i create a filter : 
nnedi3_rpow2(2, cshift="Spline36Resize", fwidth=%target_width%, fheight=%target_height%)

and the plugin line will be automatically added into the avs script like when creating a simple nnedi3 filter
Somewhat a simple rule like : nnedi3 _or_ nnedi3_rpow2 = auto call nnedi3 plugin 

PS: I know i can add the line to load the plugin directly into the filter I created, just wondering if it won't be "cleaner" to auto load it as other recognized plugins in the Staxrip program.

Thanks a lot in advance

**Comment by stax76** [comment]
Hi,

it will work in the next build, I think you can also use a commend meanwhile:

#nnedi3(

**Comment by jalba69** [comment]
Thanks a lot for this, really appreciate it.
