### ISSUE TITLE
Green upside down encodes

### ISSUE THREAD

**Issue by dhimanAdhikari** [stax76/staxrip#122]
I'm using StaxRip v1.3.7.0 and x265 build v2.1 10-bit (Dec 1 from builds.x265.eu).

The last time I encoded was a couple weeks ago and the encode was perfectly fine. After I finished encoding today the result was upside down and was transparent green (pics attached)

I tried encoding again using an older version of x265 but still the same result. I've double checked the encode settings and they are my usual settings so that's out. I've also tried encoding a different file to see if my source is the problem but that too gave the same results.

![vlcsnap-error484](https://cloud.githubusercontent.com/assets/20817945/20880203/f896535a-bafc-11e6-85d9-1dd68176961d.png)

![vlcsnap-error112](https://cloud.githubusercontent.com/assets/20817945/20880221/0c095e8c-bafd-11e6-883d-144302c89acf.png)

Please help

**Comment by Arcanemagus** [comment]
* Is the preview in Staxrip displaying the same issue?
* Where are you seeing the issue? If it's an external player, try a different one as this looks like a rendering issue in the player.

**Comment by dhimanAdhikari** [comment]
I never really check the preview but yes the Preview is displaying the issue too.
And I've tried both VLC and MPC-HC so its not an issue of the video player.

Am I doing something wrong?

**Comment by Arcanemagus** [comment]
Is the source filter different between the one that works and the broken ones? Eg. `LWlibavVideoSource` vs `FFVideoSource`?

**Comment by dhimanAdhikari** [comment]
Actually, I have always used the source filter set as "Automatic" and it never gave me a problem before.

**Comment by Arcanemagus** [comment]
Yes, but once you load a source file it will have selected a source filter for you, is the filter it is selecting different between them?

**Comment by dhimanAdhikari** [comment]
Yes, they are different. The "green error" ones have FFVideoSource and the good one has LSMASHVideoSource.

I'm assuming using a different Source Filter is the obvious answer. If so thank you very much for your help.

**Comment by Arcanemagus** [comment]
That depends _entirely_ on the source material as different source filters have different capabilities with decoding stuff. Most of my sources end up using the `LWlibavVideoSource`, with a few ending up on `FFVideoSource`. I've had some very problematic files that `DirectShow` was the only one that could read the metadata properly for (but then crashed StaxRip within ~20 seconds so it was unusable).

Somebody who knows more of the internals would have to answer any deeper, as the default has worked in all but 2 cases for me.
