### ISSUE TITLE
Old x265 build

### ISSUE THREAD

**Issue by Brainpiercing** [stax76/staxrip#123]
The x265 version in this is by now pretty old. Can I simply replace it with a recent build (from Doom9 or other)?

**Comment by dhimanAdhikari** [comment]
Yes you can :)

**Comment by Brainpiercing** [comment]
Are the default options set up in the compiler? I mean should I change any options manually in a different build to get back the same quality as with Staxrip?

**Comment by dhimanAdhikari** [comment]
Nothing to change, just replace the x265.exe build with the new one and you are good to go.

**Comment by stax76** [comment]
The latest test build is up-to-date again.
