### ISSUE TITLE
Program Freezes in the Start

### ISSUE THREAD

**Issue by Salsichah** [stax76/staxrip#124]
It's happening that every time I click to open stax rip. Opens and a few seconds later, it stops to respond. The only version that works great to me is the version 1.2.2.2 beta, after that, all releases freezes when I try to open.

I think I have all the requirements installed. I'm using Windows 7 64bits.

**Comment by stax76** [comment]
sorry for not responding earlier, please try the test build

https://github.com/stax76/staxrip/blob/master/md/test-build.md
