### ISSUE TITLE
Low CPU Usage when using SMDegrain

### ISSUE THREAD

**Issue by OnbekendHH** [stax76/staxrip#128]
When using SMDegrain Filter, CPU Load is very low (under 50%), correspondingly Encoding FPS is also very low. Is SMDegrain not Multithreaded? Thanks for any help!
Greetings,
OnbekendHH

**Comment by stax76** [comment]
Hi,

best ask in the avisynth+ or vapoursynth thread (I don't know which one you use).

http://forum.doom9.org/showthread.php?t=165771&page=999

http://forum.doom9.org/showthread.php?t=168856&page=999
