### ISSUE TITLE
QSVEncC h264 issue

### ISSUE THREAD

**Issue by ukharley** [stax76/staxrip#129]
Had to revert to the old QSVEncC 2.51 as the new 2.59 version doesn't work for me.

Old QSVEncC 2.51 version
---------------------------
QSVEncC (x64) 2.51 (r1105) by rigaya, Jun 12 2016 21:42:18 (VC 1900/Win/avx2)
OS             Windows 10 (x64)
CPU Info       Intel Core i5-3450 @ 3.10GHz [TB: 3.70GHz] (4C/4T) <IvyBridge>
GPU Info       Intel HD Graphics 2500 (6EU) 350-1200MHz [77W] (10.18.10.4425)
Media SDK      QuickSyncVideo (hardware encoder), 1st GPU, API v1.11

New QSVEncC 2.59 version
----------------------------
Encoding using QSVEncC 2.59 x64 failed with exit code: -1073741819 (0xC0000005)

**Comment by stax76** [comment]
it seems related the the vpy reader, I get this message before it crashes:

vpy: invalid colorformat 0.
Input: switching to avi reader.

**Comment by stax76** [comment]
rigaya said he will investigate the issue.

**Comment by rigaya** [comment]
I have uploaded [QSVEnc 2.61](http://rigaya34589.blog135.fc2.com/blog-entry-880.html), which will fix this problem.

**Comment by ukharley** [comment]
Thanks. Works now.
