### ISSUE TITLE
MP3 Audio Setting - Rate Mode: ABR

### ISSUE THREAD

**Issue by rkolja** [stax76/staxrip#13]
Hi,
could it be that the ABR setting is not working? When I'm encoding in mp3 - 128kbit - ABR - the resulting file is with constant mp3 stream rate.
![stax_1317_abr](https://cloud.githubusercontent.com/assets/15999412/11372096/f06c93c4-92cb-11e5-86a4-5e03d59d9a3d.PNG)

Greets
rkolja

**Comment by stax76** [comment]
Hi,
thanks for the report, it's fixed locally.

cheers,
stax
