### ISSUE TITLE
Processing MOV file from SJ4000 fails

### ISSUE THREAD

**Issue by pberenyi** [stax76/staxrip#130]
I was trying to convert some video shot with my SJ4000 actioncam to H.265 / AAC and the first thing I have noticed that extracting the audio track was very slow. Secondly when I've started the conversion it failed with 'audio format could not be recognized'.
The media info from one of the files:
Format                         : MPEG-4
Format profile                 : QuickTime
Codec ID                       : qt  
File size                      : 26.6 MiB
Duration                       : 13s 967ms
Overall bit rate               : 16.0 Mbps

Video
ID                             : 1
Format                         : AVC
Format/Info                    : Advanced Video Codec
Format profile                 : High@L4
Format settings, CABAC         : Yes
Format settings, ReFrames      : 1 frame
Format settings, GOP           : M=1, N=15
Codec ID                       : avc1
Codec ID/Info                  : Advanced Video Coding
Duration                       : 13s 967ms
Bit rate                       : 14.7 Mbps
Width                          : 1 920 pixels
Height                         : 1 080 pixels
Display aspect ratio           : 16:9
Frame rate mode                : Constant
Frame rate                     : 30.000 fps
Color space                    : YUV
Chroma subsampling             : 4:2:0
Bit depth                      : 8 bits
Scan type                      : Progressive
Bits/(Pixel*Frame)             : 0.237
Stream size                    : 24.5 MiB (92%)
Language                       : English

Audio
ID                             : 2
Format                         : PCM
Format settings, Endianness    : Little
Format settings, Sign          : Signed
Codec ID                       : sowt
Duration                       : 13s 84ms
Bit rate mode                  : Constant
Bit rate                       : 512 Kbps
Channel(s)                     : 1 channel
Sampling rate                  : 32.0 KHz
Bit depth                      : 16 bits
Stream size                    : 818 KiB (3%)
Language                       : English

 Encoding the same file with Mediacoder is successful.

**Comment by stax76** [comment]
can you upload a sample up to 30 seconds?

**Comment by pberenyi** [comment]
Here is a 5 sec sample that does not work for me. (I had to zip it to upload.)
[20170001.zip](https://github.com/stax76/staxrip/files/683099/20170001.zip)

**Comment by stax76** [comment]
It looks mp4box demuxes a corrupt wav file as well as reports errors on the video stream. You can workaround it disabling audio demuxing and use the option: Options > Audio > Force Decoding using ffmpeg. If you disable audio demuxing StaxRip uses the mov file as audio source file, so ffmpeg can extract a wav file from the mov file. When you use ffmpeg as encoder you can skip force decoding because ffmpeg can read mov, eac3to and qaac can't read mov so decoding is necessary.

```
D:\Projekte\VS\VB\StaxRip\bin\Apps\MP4Box\MP4Box.exe -raw 2 -out "D:\Temp\20170001\20170001_temp\20170001 ID2 English.wav" "D:\Temp\20170001\20170001.MOV"

[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
[AVC/HEVC] Not enough bits in bitstream !!
Extracting '' Audio - Compressor
```

**Comment by stax76** [comment]
Since other people reported similar issues I changed it to automatically demux PCM with ffmpeg.

https://github.com/stax76/staxrip/blob/master/md/test-build.md
