### ISSUE TITLE
Unable to Pass All Subtitles in Batch Process

### ISSUE THREAD

**Issue by Rick-N-Thailand** [stax76/staxrip#131]
Hello,

I've been able to set in the Template to Pass "ALL" subtitles and audio streams.  However, MKV / MP4 container only enables the first one (Check Box).  When I process a Single Video , I can manually select (check box) other subtitles in the MKV / MP4 container options.  Is there a way change the functionality or code to have ALL subtitles passed to the MKV / MP4 container to be selected by default?

Thanks :)

Rick

**Comment by stax76** [comment]
maybe following works:
![unbenannt](https://cloud.githubusercontent.com/assets/11410540/21598237/50e14e8a-d159-11e6-9497-d2997bc5d65f.png)

**Comment by Rick-N-Thailand** [comment]
Hi Stax,

Thank you for the message.  Simple and easy fix thanks... I had:  "Demux Subtitles:" > "All" but that just demuxed them... Putting "All" in the Preferred Language Box fixed me right up...

Thanks again,

Rick
