### ISSUE TITLE
StaxRip doesn't detect MPC-HC version properly

### ISSUE THREAD

**Issue by kamild1996** [stax76/staxrip#132]
In the apps menu, I chose "MPC Player" and I pointed it to my MPC-HC x64 1.7.10 installation. However, StaxRip doesn't want to accept that, and instead it says "Unsupported outdated version".
Using the latest version of StaxRip, 1.4.0.0, on Windows 10.

EDIT: Screenshot: http://imgur.com/66ezqzx

EDIT2: Similar issues with MPC-BE, but instead the program suggests to press F12 in order to modify the expected version. After doing so it works, also when you select MPC-HC.

**Comment by stax76** [comment]
it'll be fixed in the next built, another workaround is to edit the versions.txt file, it's in the startup dir under apps or if it was modified it can also be in the settings dir.
