### ISSUE TITLE
AMD H.265?

### ISSUE THREAD

**Issue by jullit31** [stax76/staxrip#133]
Are there any plans to support AMD H.265 encoding? Would that be beneficial (compared to Intel Quick Sync H.265)?

**Comment by stax76** [comment]
I think it's not yet supported by VCEEnc, StaxRip uses the latest 2.0, you can ask in the support thread at doom9 if anybody knows if rigaya has plans to support it

https://forum.doom9.org/showthread.php?t=172068&page=999

or you can mail him directly, his mail address can be found here (left side):

http://rigaya34589.blog135.fc2.com/blog-entry-799.html

**Comment by itscodezilla** [comment]
VCEEnc is now up to version 3.05 and supports Polaris HEVC encoding.

**Comment by stax76** [comment]
It's already supported in the last test build.
