### ISSUE TITLE
unsupported c++ 2015

### ISSUE THREAD

**Issue by foXaCe** [stax76/staxrip#139]
hello in the new beta build visual c++ 2015 bug

status 
unsupported version

why ?

**Comment by stax76** [comment]
Hi, I'm not sure what went wrong but you can pass it with F12, test build from today explicitly states the F12 trick. Most recent VC++ 2015 is Update 3, not sure if that's what the vapoursynth installer installs.

https://www.microsoft.com/en-us/download/details.aspx?id=53587

**Comment by foXaCe** [comment]
OK World with f12 edit

**Comment by foXaCe** [comment]
Thanks
