### ISSUE TITLE
Command line - incorrect variable for a network share

### ISSUE THREAD

**Issue by massiliattak** [stax76/staxrip#14]
Hello,

It seems that variables with 2 backslashes at the beginning are incorrectly interpreted by the Encoding Batch expression.

As you can see below in the Macros window, the variable is correct.
![image](https://cloud.githubusercontent.com/assets/4604296/11472149/d564c9fe-976a-11e5-9ba9-65389b61a597.png)

But, in the Preview tab, one of the backslash is missing:
![image](https://cloud.githubusercontent.com/assets/4604296/11472168/039e2b3a-976b-11e5-9606-5f7d34db55e3.png)

So, starting the encoding process fails immediately. 
I need to modify each time the generated batch and add the missing backslash for success.

The problem exists only for Command Line profiles (x264, DivX H.265, Nvidia H.265).

**Comment by stax76** [comment]
Hello,

StaxRip never supported such paths (it's luck if it works in some configurations). I don't have a network drive so unfortunately I'm not able to debug it.
