### ISSUE TITLE
Crashes when loading TIVTC or SRestore

### ISSUE THREAD

**Issue by StepMur92** [stax76/staxrip#140]
Using Windows 10, AMD FX-8320, 8 GB of 1666 MHz memory
Adding TIVTC and/or SRestore to plugins folder (tried every possible plugins folder that I could find). Adding required lines in Profiles. Trying to load any of these plugins - and StaxRip crashes immediately.
However, it works with Staxrip 1.2.2.0 under Windows 10.
What should I change to make it work?

**Comment by stax76** [comment]
Probably those plugins don't have a working x64 version or they are corupting memory which crashes the .NET CLR. Can you get it working outside of staxrip with VirtualDub x64?
