### ISSUE TITLE
Crash when start script convert to HDR

### ISSUE THREAD

**Issue by kliffgomel** [stax76/staxrip#141]
[Log.txt](https://github.com/stax76/staxrip/files/823786/Log.txt)

**Comment by stax76** [comment]
.NET 4.6.2 is installed?

**Comment by kliffgomel** [comment]
.NET Framework 4.6.1586.0

**Comment by stax76** [comment]
try this:

https://www.microsoft.com/en-us/download/details.aspx?id=53345

**Comment by kliffgomel** [comment]
Sorry, I probably was mistaken. Version is 4.6.01586, but release is 394802 (.NET 4.6.2 Windows 10 Anniversary Update).

**Comment by stax76** [comment]
I've uploaded a new test built with 5 updated nuget packeges related C# scripting.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by kliffgomel** [comment]
Exception
[log.txt](https://github.com/stax76/staxrip/files/863826/log.txt)

**Comment by stax76** [comment]
Did you try to reinstall .NET? Since you are the only one reporting this it's likely that there is something wrong on your system. It reports System.IO.FileSystem, Version=4.0.1.0 while I think it should load something with 4.6.2 or 4.0.30319, when you look at the loaded dlls in process expolorer do you see v4.0.30319?

**Comment by kliffgomel** [comment]
![2017-03-25_09-10-27](https://cloud.githubusercontent.com/assets/26083325/24319910/f7fc1ed6-113a-11e7-9e29-7f89cd8e893b.png)
It seems everything is normal, I don't know in what a problem. At me along with the built-in packet of .NET of version 4.6.2 still packets of versions 3.5, 4.5 are set.

**Comment by kliffgomel** [comment]
[Log.txt](https://github.com/stax76/staxrip/files/869884/Log.txt)
staxrip 1.4.1.3

**Comment by stax76** [comment]
Can you please try the latest build? I've changed and learned some things so there is a chance I can fix it this time.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by stax76** [comment]
Because I converted the HDR script to powershell and because C# scripting will be removed soon close this issue now.

**Comment by kliffgomel** [comment]
powershell script works great!
