### ISSUE TITLE
Still error with non-English file name

### ISSUE THREAD

**Issue by Gabarito007** [stax76/staxrip#142]
Hi.
I've already read [#67](https://github.com/stax76/staxrip/issues/67) and [#87](https://github.com/stax76/staxrip/issues/87)
**and** also try to edit Event Command with %source_dir%%source_name%.%template_name%.%muxer_ext% for SetTargetFile
**and** also got the latest [test buid](https://github.com/stax76/staxrip/blob/master/md/test-build.md) x64 1.4.0.7, running on Windows 7.

Nevertheless, I'm still getting error with filename:
x265 [error]: unable to open input file <->
Log:
[Só corro.x265 - MKV - Super Low 26 - AAC - 22050 Hz_StaxRip.log.txt](https://github.com/stax76/staxrip/files/825246/So.corro.x265.-.MKV.-.Super.Low.26.-.AAC.-.22050.Hz_StaxRip.log.txt)

Thx.

**Comment by stax76** [comment]
It's too difficult to find out if Win 7, avs2pipemod, x265 or staxrip is too blame for this, it would take hours for investigation and it's unlikely that I could find a solution, I invested a huge amount of time in this area, in Win 10 it works just fine. Real unicode support is only possible with Win 10 and VapourSynth, your file name doesn't even use unicode though and I believe Brasil has the same code pages as my country Germany (1252/850), quite possible Win 7 is to blame:

> Note there are serious implementation bugs in Windows's code page 65001 support which will break many applications that rely on the C standard library IO methods, so this is very fragile. (Batch files also just stop working in 65001.) Unfortunately UTF-8 is a second-class citizen in Windows.

http://stackoverflow.com/questions/388490/unicode-characters-in-windows-command-line-how

If x264 works than x265 can be blamed to refuse to implement an avifile/avisynth/vapoursynth reader.

**Comment by Gabarito007** [comment]
Thank you very much for your kind attention to my question.

When I analysed Log file and realized that avs2pipemod was in the action, I suspected that it was the cause.
Then, I looked for a newer version of it.
Version bundled in last StaxRip is 1.1.1 (Aug, 2016).
I could not find a newer than that.
So, I came to ask you some solution.

Now, everytime I got a file with english caracters, I rename it to, say, file.mp4 and proccess it.
Finished, I rename back to its original name.
But it's very annoying.

Of course, I will ask to doom9 forum at x165 thread for sure.

Thx.

**Comment by Gabarito007** [comment]
That's right -> Codepage here is same than yours, 1252/850.

;-)

**Comment by Gabarito007** [comment]
Yesterday at morning I leave a comment [here](https://forum.doom9.org/showthread.php?s=ffde1fc586b2b984497cf04474168bb2&t=168814&page=253), at Doom9, but system said that my comment would be subject to Moderator judgment.
Today at evening, my comment still did not appeared...
:-(

**Comment by stax76** [comment]
Meanwhile I've requested it also, closing it now.
