### ISSUE TITLE
SLI supported ?

### ISSUE THREAD

**Issue by robotreto** [stax76/staxrip#143]
great work indeed !  
I am encoding using NVIDIA 265 with several hundered fps, fantastic !

Sadly just one of my 2 cards (GTX 970 SLI x 2) is utilized (VE Load > 90 %). The other card is idle (VE Load 0%), even when I have 2 instances of StaxRip running.

What could be done to utilize both cards ?

**Comment by stax76** [comment]
The test build has a 'Device' option on the 'Other' tab, you can also find it by entering device in the search input box at the bottom.

https://github.com/stax76/staxrip/blob/master/md/test-build.md
