### ISSUE TITLE
Crash when abort project on demux phase

### ISSUE THREAD

**Issue by kliffgomel** [stax76/staxrip#145]
AbortException

StaxRip.AbortException: Ошибка в приложении.
   в StaxRip.Proc.Start() в D:\Projekte\VS\VB\StaxRip\General\Proc.vb:строка 195
   в StaxRip.MainForm.OpenEac3toDemuxForm(String playlistFolder, Int32 playlistID) в D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:строка 5017

**Comment by stax76** [comment]
Thanks for reporting this, it will be fixed in the next build.
