### ISSUE TITLE
QSVEnc error with video at 10bits

### ISSUE THREAD

**Issue by RayZX** [stax76/staxrip#146]
I did tests and it really is not about frame rate, it seems like the problem is bit depht, Quick Sync does not support 10bit?

**Comment by stax76** [comment]
I don't think it's the frame rate, at least I could not reproduce it.

Can you upload this sample?

What means: A instrução no 0xp referenciou a memória no 0xp. A memória não pôde ser s.

**Comment by stax76** [comment]
I don't know if QS supports 10bit, please post the log file.

**Comment by aussiebro** [comment]
i tried 10bit using the nvencc  cuda decoder and get errors. then i set it as 8bit and it converts.

**Comment by stax76** [comment]
Please post a full log file to pastebin with auto expire enabled.
