### ISSUE TITLE
eac3to: Only first audio track processed when not extracting all audio tracks on import

### ISSUE THREAD

**Issue by Samhayne** [stax76/staxrip#147]
When not extracting all audio tracks on import eac3to will be passed the container.
But it won't be given a track number to process.

Looking in the log the command line used doesn't use any track numbers:
```
command line: "[...]StaxRip 1.4.0\Apps\eac3to\eac3to.exe" "[...]\movie.mkv" "[...]\movie_temp\movie_out2.m4a" -quality=0.67 -normalize -down6 -progressnumbers
------------------------------------------------------------------------------
MKV, 1 video track, 2 audio tracks, 1 subtitle track, 2:13:57, 24p /1.001
1: h264/AVC, English, 1920x808 23.975p
2: DTS, German, 5.1 channels, 1509kbps, 48kHz
3: DTS, English, 5.1 channels, 1509kbps, 48kHz
```

The result is a movie claiming to have multiple audio tracks for different languages but in
each will be the same track - the first track of the original container.

**Comment by stax76** [comment]
You mean you were opening a blu-ray folder in order to demux with eac3to? Why did you not demux all the audio tracks you want to include? Please post full log files.

**Comment by Samhayne** [comment]
I was reconverting a movie in an mkv container with a German and an English audio track.

If I untick all audio track exports when opening it in Staxrip I will end up with a movie having the first audio track twice (though still named "German" and "English")

If I let Staxrip do the audio exports everything is fine as the extracted tracks are passed directly to eac3to.

Without the export the MKV container will be passed to eac3to... but without telling it which track to encode. I guess it will just pick the first one it finds. (See log above)

I'm at work right now and can't come up with an example file right now but I hope this description is still clear enough. :)

**Comment by stax76** [comment]
I'm a bit surprised that nobody has found this before, a new build with a fix is online:

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by Samhayne** [comment]
Supercool, Stax! :)
(I discovered  this bug months ago but didn't realize that you're monitoring bug reports. Until the video comparison tool lead to a crash with a browser opening this site. And... maybe one part of me was just sure that sb else already reported it)
