### ISSUE TITLE
x264 default for --qpmin is now 0, not 10 anymore

### ISSUE THREAD

**Issue by LigH-de** [stax76/staxrip#148]
The command line reduction still assumes a default of 10 for --qpmin which removes this parameter erroneously for this value; but the current default is 0 instead.

Externally discussed in [the Gleitz board](http://forum.gleitz.info/showthread.php?26177-StaxRip-Encoding-Frontend-(Diskussion)&p=458236&viewfull=1#post458236).

**Comment by stax76** [comment]
Thanks for reporting, I've corrected it (locally).
