### ISSUE TITLE
Request to pull-in updated NVENC 6.0 SDK 

### ISSUE THREAD

**Issue by Lord-Malgus** [stax76/staxrip#15]
Request to pull-in updated NVENC 6.0 SDK

See nvidia page here :
https://developer.nvidia.com/nvidia-video-codec-sdk

SDK Updated (NVENC SDK 6.0): November 30, 2015

Thank you!

**Comment by Lord-Malgus** [comment]
need to wait for a supported encoder (NVencC / ffmpeg) to add support before staxrip can add..

**Comment by stax76** [comment]
Hi,
I'll tell the NVEncC author about the SDK update.
Thanks

**Comment by Lord-Malgus** [comment]
Thank you!
