### ISSUE TITLE
Request: Hard Coded Subtitles

### ISSUE THREAD

**Issue by Azz100** [stax76/staxrip#150]
Hi,

Is it possible to add support for .sup files when hard coding. Currently only SRT, ASS and VobSub are supported.

Hopefully it wont me to hard as both .sup and VobSub are both image based subtitles.

Thanks for the great work.

**Comment by stax76** [comment]
I don't think there is a filter for this.

**Comment by sneaker2** [comment]
VapourSynth already comes with such a plugin. (sub.ImageFile())
http://www.vapoursynth.com/doc/plugins/subtext.html

Until Stax has this properly integrated you should be able to use the following workaround:
1. Open file with a VapourSynth source filter
2. Tools > Advanced > Hard Coded Subtitle and select the .sup or .idx file
3. Click "Filters">"Edit" and there
4. change e.g. "_TextSubMod("C:\movies\subtitle_file.sup")_" to "_clip = core.sub.ImageFile(clip, file="C:/movies/subtitle_file.sup")_"
(note the change of backwards to forwards slashes)
5. Encode like usually

**Comment by stax76** [comment]
Next test build supports srt, ass, idx and sup using vapoursynth and Tools > Advanced > Hard Coded Subtitle

@sneaker

Thanks for the help with it.
