### ISSUE TITLE
problem encoding x264 to h265 nvidia 10 bit

### ISSUE THREAD

**Issue by nicscap** [stax76/staxrip#155]
Hi, I have a problem to convert some files to h265, I use GPU with cuda and a 10 bit. 

I attached log report like you required.

https://pastebin.com/knrqCfQp

thank you

**Comment by stax76** [comment]
Something looks wrong with your command line, did you enter " without as cutom switch?

"C:\Program Files\StaxRip\Apps\NVEncC\NVEncC64.exe" --cqp 20:23:25 --codec h265 --output-depth 10**" without** -i "N:\Quantico\stagione 1\Quantico.1x01.Corri.DLMux.720p.ITA.ENG.SUBS_new_temp\Quantico.1x01.Corri.DLMux.720p.ITA.ENG.SUBS_new_new.avs" -o "N:\Quantico\stagione 1\Quantico.1x01.Corri.DLMux.720p.ITA.ENG.SUBS_new_temp\Quantico.1x01.Corri.DLMux.720p.ITA.ENG.SUBS_new_new_out.h265"

-----------------

Encoding using NVEncC 3.02 x64 failed with exit code: 1 (0x1)
 
The exit code might be a system error code: STATUS_WAIT_1
 
The exit code might be a system error code: Funzione non corretta.
 
Error: Unknown option: "1\Quantico.1x01.Corri.DLMux.720p.ITA.ENG.SUBS_new_temp\Quantico.1x01.Corri.DLMux.720p.ITA.ENG.SUBS_new_new.avs -o N:\Quantico\stagione"

**Comment by nicscap** [comment]
Hi, thank for reply. 
I enter that, but now I remove it and the problem persist.

I post another log file here: https://pastebin.com/86Y9mK9v

thanks

**Comment by stax76** [comment]
Please try a test build, it generates avisynth code to open Main 10 profile source files.

https://github.com/stax76/staxrip#download
