### ISSUE TITLE
Shutdown when finished does not shutdown the computer

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#156]
I updated from StaxRip 1.3.1.7-beta to 1.4.0.0.
Now when I leave my encodes over night and set the job queue to shutdown when done, the computer stays on.
This didn't happen before on the previous version I used.

My current system profile:
![image](https://cloud.githubusercontent.com/assets/10564090/25670456/572d5f84-2ff2-11e7-8f81-861345d6f3fd.png)

**Comment by stax76** [comment]
There was a breaking change in a windows update, please try a test build:

https://github.com/stax76/staxrip#download
