### ISSUE TITLE
Some apps/tools in StaxRip don't parse Windows environment variables correctly

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#157]
Hi, I sent en email and got your reply but I think I didn't write the message clear so I'm trying again here.

Apparently StaxRip doesn’t parse system environment variables from Windows such as %TEMP%, %APPDATA%, %LOCALAPPDATA%, etc.
I found this line from a log file:

FFVideoSource("D:\myvideo.mkv", cachefile = "%TEMP%\StaxRip Temp working files\myvideo.ffindex")

It seems to me that the apps/tools used don’t parse them correctly. 

Suggestion: leave fields in StaxRip inputs with system variable nomenclature, but parse it when feeding the commands to tools.
ie.
In StaxRip the commands can be read as %TEMP%, but when sending the text to a app/tool, it should parse it as "C:\User\AppData\Local\Temp", and not leave it to the tool to parse it according to the OS.

Here's a list of Windows environment variables:
https://www.tenforums.com/tutorials/3234-environment-variables-windows-10-a.html

**Comment by stax76** [comment]
Next build will expand system environment variables.
