### ISSUE TITLE
StaxRip crashes after muxing

### ISSUE THREAD

**Issue by callibsoffm** [stax76/staxrip#158]
Hello,

after each encoding and muxing StaxRip crashes. Beyond a crash.srip.
[crash.zip](https://github.com/stax76/staxrip/files/975338/crash.zip)
With kind regards

Alexander

**Comment by stax76** [comment]
Hi,

please try the last build and post the full log file if it fails.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by callibsoffm** [comment]
Hi,

with the last build everything works fine.

Thanks

Alexander


Von: stax76 [mailto:notifications@github.com]
Gesendet: Donnerstag, 4. Mai 2017 17:17
An: stax76/staxrip <staxrip@noreply.github.com>
Cc: Alexander Arnold <damienffm@hotmail.com>; Author <author@noreply.github.com>
Betreff: Re: [stax76/staxrip] StaxRip crashes after muxing (#158)


Hi,

please try the last build and post the full log file if it fails.

https://github.com/stax76/staxrip/blob/master/md/test-build.md
