### ISSUE TITLE
Please add support for "ICQ mode with lookahead" to staxrip GUI  (QSVEncC HEVC) if available

### ISSUE THREAD

**Issue by Lord-Malgus** [stax76/staxrip#16]
Currently Staxrip only exposes the base "--icq" option for QSVEncC HEVC encoder.  I notice its available for the QSVEncC AVC encoder.  Skylake CPU is on backorder at the moment, so I can not confirm if "ICQ mode with lookahead" is available for HEVC on that platform.  

![image](https://cloud.githubusercontent.com/assets/9889229/11612471/badfb6d6-9bc8-11e5-82ee-02903e2bed47.png)

![image](https://cloud.githubusercontent.com/assets/9889229/11612467/723ba174-9bc8-11e5-81a1-0891f4c893d3.png)

If this is indeed available I'd love to see this option added to QSVEncC HEVC.

Thank you.

**Comment by stax76** [comment]
unfortunately it's not supported:

LA-ICQ (Intelligent Const. Quality with Lookahead) mode is not supported on current platform.

QSVEncC.exe finished with error!
