### ISSUE TITLE
a/v desync - decoder dependent

### ISSUE THREAD

**Issue by Bokujutsu** [stax76/staxrip#160]
Transcoding nVidia shadowplay videos causes desync depending on which decoder is used.

(bad) Synth log: https://pastebin.com/FV6k0RJZ
(better) avcuvidnative log: https://pastebin.com/kYJehCUL
(better) avcuvidcuda log: https://pastebin.com/Qtv5zV4R
(perfect(slower)) ffmpegintel log: https://pastebin.com/80uLe2W5
(perfect(slow))ffmpegdxva2 log: https://pastebin.com/WHLeWq95

**Comment by stax76** [comment]
Thanks for trying different decoders and for uploading the results to pastebin, this gives me all needed info.

What is unusual:
```
Frame rate mode           : Variable
Frame rate                : 59.338 FPS
Minimum frame rate        : 1.360 FPS
Maximum frame rate        : 63.694 FPS
Original frame rate       : 60.000 FPS
```
and then the properties staxrip reads from the scripts:
```
source frame count : 17816
source frame rate  : 59.338162
source duration    : 00:05:00.2450000
target frame count : 17816
target frame rate  : 59.338162
target duration    : 00:05:00.2450000
```
synth output:
```
Frame rate mode           : Constant
Frame rate                : 59.338 FPS
```
ffmpeg output:
```
Frame rate mode           : Constant
Frame rate                : 60.000 FPS
```
I believe that the ffmpeg decoder converts vfr to cfr. I also believe that some avisynth and vapoursynth source filters can make this conversion too, you would have to read the docs of the source filters and edit the avs code yourself.

Generally it's possible to re-encode with VFR, staxrip got some VFR improvements a few weeks ago but only for MKV, it can extract and mux a time code file for MKV. If somebody makes a request MP4 could probably also be improved. Unfortunately I don't have much experience with VFR.

Other things you could try is to check if shadowplay has a setting to record with CFR and if you are familiar with handbrake or are interested in it you can check how handbrake deals with it, I think typically handbrake is good in handling many type of issues automatically.

Hope this helps

**Comment by stax76** [comment]
in the next build you can use the context menu:

https://postimg.org/image/v2a9wcqcr/

https://github.com/VFR-maniac/L-SMASH-Works/blob/master/AviSynth/README#L48

Can I close the issue?

**Comment by Bokujutsu** [comment]
Yes, thank you. 👍
