### ISSUE TITLE
Projected file size

### ISSUE THREAD

**Issue by Gabarito007** [stax76/staxrip#162]
Is it 'possible/too difficult' to put an extra information on Staxrip log window displaying projected file size?
I mean beside eta captions, at that point:

![2](https://cloud.githubusercontent.com/assets/14959189/25871284/580436ea-34dd-11e7-8928-7ced465e7d36.png)

This is important because when encoding large files, I could preview if size is acceptable or I have to abort encoding and start it again after change video quality by crf value.

As you might know, Virtualdub has that:

![3](https://cloud.githubusercontent.com/assets/14959189/25871481/0196d320-34de-11e7-9ba8-bfcd79a1a87f.png)

**Comment by stax76** [comment]
This status line is the output of the encoder without modification. Parsing this decreases impacts performance so it's a bit problematic, furthermore staxrip would need to read the file size which also is problematic. You could ask in the x265 thread if anybody else would find it useful.

https://forum.doom9.org/showthread.php?t=168814&page=267

**Comment by Gabarito007** [comment]
Got it.
Fair enough.
Thanks.
