### ISSUE TITLE
Improve demuxing GUI with more options for attachments

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#164]
Hi Stax,

It will be nice to have a few more options in the demuxing window for Mkv & mp4  files.

Right now if we input a MKV file having an attachment as source in staxrip we extract the attachment to the temp folder automatically without even knowing about it unless looking to mediainfo for the file, for example a text file with comments will display like this in mediainfo : 
**Attachments : Some_File.txt**
usually it displays the filename + extension , at least for what i could test.

In the case of a MP4 or mov file having a cover picture they are not extracted and we are not informed those are there, unless looking into mediainfo, there it will simply look like this : 
**Cover : Yes**
it just says there is one cover, nothing more.

I don't know much about MKV's extraction so i cannot help much for those, for mp4's i use them often, the command to dump the cover picture from a MP4 is : 
**mp4box.exe  -dump-cover videoInput.mp4** 
Also while I'm at it to dump all tracks and the cover (if there is one) from a mp4 the command is : 
**mp4box -dump-cover -raw * inputfile.mp4**
to dump a specific track it's 
**mp4box -raw TrackID inputfile.mp4**

In case you want to test , for adding a cover to a MP4 you need this in mp4box : 
**-itags cover="picture.jpeg"**  ( can be other formats of pictures too, not only jpeg) 

Or for more easy testing in mp4 container set a switch with :
**Add Cover = -itags cover="$browse_file$"**  or **Add Cover = -itags cover="$picture.jpeg$"**

In case you want to combine cover + comments + encoder used for testing : 
**-itags cover="picture.jpeg":encoder="Staxrip %version%":comment="Some text comments"**

Another interesting one is creation date **:created="UTC 2015-07-19 07:52:02"** to transpose the date of the original footage recorded to the encoded one but this is very specific uses. Output in mediaInfo is : 
 Recorded date  : UTC 2015-07-19 07:52:02

Not sure how you do but if you are able to parse some stuff from mediainfo it could result in something like this , for mp4, mov (and probably a few other formats supported by mp4box ) : 
![alt text](https://img15.hostingpics.net/pics/16831220170511232400.png)
for MKV's : 
![alt text](https://img15.hostingpics.net/pics/41150220170511232400Copie.png)

Pushing this further we could also import **Comment** & **Description**  often present in mediainfo fields into a text file to not loose them and re-import them back later either as attachment text file or tag for a MKV and for mp4's as a comment tag that we will need to add manually using this command : 
**-itags comments="some text comments"**

I'm not sure how many people use comments in those containers but it's a easy way to keep track of some stuff in encoded videos.

I think i forgot nothing, probably did as always but overall this is the idea.

Thanks a lot again and sorry to bother you with more requests. 

Edit : forgot to add this for mp4box, might serve in some case so there it is : 
 -dump-chap                 Extracts chapter file
 -dump-chap-ogg       Extracts chapter file as OGG format

**Comment by jalba69** [comment]
**mpxbox -info inputfile.mp4** give a bit more infos about the cover file type in the itunes tags info part : 

iTunes Info:
        Name: Video Name 
        Comment:  some comment  _( apparently not uft8 output tho)_
        Created: 20170508
        Encoder Software: Lavf57.72.101
        Cover Art: JPEG File

or also this : 
iTunes Info:
        Encoded by: StaxRip 1.4.3.7
        Cover Art: PNG File

small variation between _encoder software_ and _encoded_ by but it detects the cover type of file apprently.

In mediainfo it correspond to this :

Movie name                           : Video Name 
Description                             :  Some comments ( no issue wiht uft8 characters ) 
Recorded date                       : 20170508
Writing application              : Lavf57.72.101
Cover                                         : Yes

For what it is worth.

**Comment by stax76** [comment]
Hi,

I've implemented the MKV attachments in the demuxing GUI.

For the rest please create separate issues with only a single request per issue.

**Comment by jalba69** [comment]
Thank you, will do a couple more for mp4, .mov covers and comments metadata extraction.

Thanks again.

**Comment by jalba69** [comment]
Tested last version with MKV input, works perfectly, you make dreams come true, thanks a lot for this.
