### ISSUE TITLE
Batch Encoding VBR2 - Static Bitrate Option Needed

### ISSUE THREAD

**Issue by devlin85** [stax76/staxrip#165]
Right now when you are doing a batch encode on VBR or VBR2 (NVENC, but it applies to all vbr settings) it only pays attention to the file size field, and then calculates a bitrate from that (even though there is a field to enter a bitrate). Which can lead to wildly different bitrates, ones that even crash the encoder being too large. There needs to be a way to have a fixed bitrate for multiple files. 

I use this to shrink down my security and dash camera footage for storage and the clips range from 1 min to 2 hours, you can imagine the issue 🤣 . Right now my only option is using QCP, but that can lead to some very poor results at night vs the daytime shots.

**Comment by stax76** [comment]
Hi,

there is a option: Main Menu > Options > Misc > Use fixed bitrate

**Comment by devlin85** [comment]
holy 💩 ! thank you!!
