### ISSUE TITLE
[Feature] Store log files of jobs separately

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#166]
An extremely useful feature for debugging would be to store log files of jobs in a "Logs" folder.

Logs currently are stored in the temporary folder where processing files for the video. If users are going to process many videos, then the temporary files are going to build up and take up a lot of space on the hard drive. Log files are extremely important, so it would be beneficial to store them additionally in a separate Logs folder.

Of course this might generate chaos in the filenaming since each log has the name of the video being processed. If the same video is processed multiple times with different settings, logs would overwrite each other. A suggestion would be to precede the video.log name with a historic job number such as SR-job00043_video.log, as an example.

**Comment by stax76** [comment]
in the next build there is:

- new: added new feature to archive log files in the settings directory, by default the last 50 log files are keept, this number can be customized at: 'Main Menu > Tools > Settings > General', the folder can be opened with the windows file explorer at: Main Menu > Tools > Folders > Log Files
