### ISSUE TITLE
Demux mp4,mov, show if there is an attachment on the GUI and allow extraction.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#167]
Helllo stax,

Some MP4's, .mov's and probably some other formats mp4box can demux allow to add a cover picture, command to add a cover picture into a mp4 using mp4box is : 
-itags cover="picture.jpeg"

It will be nice in the demuxing GUI to see if there is a cover attached to the input file and get a dialog asking if we want to select it for extraction or not, something like this maybe : 
![alt text](https://img15.hostingpics.net/pics/16831220170511232400.png)

In mediainfo if there is a cover we wee this only : 
Cover : Yes

The command to extract a cover picture using mp4box is : 
mp4box.exe -dump-cover videoInput.mp4

Thanks a lot.

**Comment by stax76** [comment]
Hello Yanak, next build supports it.

**Comment by jalba69** [comment]
Thanks a lot for all Stax
