### ISSUE TITLE
Demuxing: Extract metadata comments to a text file.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#168]
Hi Stax,

Often the video have comments as tags, having the possibility to extract Comments from the input source file into a text file for later use or to later import it back into a MKV as attachment or as a itag command for MP4's will be nice.

Mkv's can import directly an attachment so this will be easy selecting the txt file as attachment in options, MP4's will have to be entered manually by the user as a itags comment : 
-itags comment="Some text comments copied from the text file"

This part is for the end user to mess with using a few switches, no need of an automatic re-import. 

Filtering and getting comments and maybe some other metadata like GPS coordinates extracted to a text file will be be very nice.

Thanks in advance.

**Comment by stax76** [comment]
Writing MP4 comments to disc is probably not something many users have a interest.

With Event Commands (After Source Loaded/ExecuteScriptFile) and PowerShell scripting you can still do it with 4 lines code.

```
$p = [ShortcutModule]::p
$comment = [MediaInfo]::GetGeneral($p.FirstOriginalSourceFile, "Comment")
if ($comment -eq "") {exit}
$comment >> ($p.TempDir + "Comment.txt")
```

**Comment by jalba69** [comment]
Fantastic, works also as ExecutePowerShellScript directly.

This is great, really have to learn some of this stuff, will give a few tries later and try to get a bit more outcome like GPS infos and such following your code example, should be possible too  i bet, will need a fe trial and errors but should get it.

Thanks a lot Stax.
