### ISSUE TITLE
[Issue] 1.4.3.8-test will not run

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#169]
Testing 1.4.3.8 and it won't run, StaxRip window doesn't appear.

Tried running as administrator but nothing.
Extracted 1.4.3.7 to overwrite files from 1.4.3.8 and it works.
Something is wrong with latest build.

**Comment by stax76** [comment]
I can't test 1.4.3.8 since I already deleted it when I saw this issue. Does 1.4.3.9 run?

**Comment by Zcehtro** [comment]
Just extracted 1.4.3.9 and I'm having the same issue.

**Comment by Zcehtro** [comment]
JIC I cleared my jobs list from 1.4.3.7 and ran 1.4.3.9 again but no success, still wouldn't run.
I took a look at the processes list in Task Manager and saw the StaxRip opens for a few seconds and then immediately closes.

**Comment by stax76** [comment]
Send me the settings folder.

**Comment by Zcehtro** [comment]
Here you go:

https://www.dropbox.com/s/91pl3njimp24pmi/StaxRip%20x64%201.4.3.9%20Settings%20-Zcehtro.7z?dl=0

**Comment by Zcehtro** [comment]
Saw that you uploaded 1.4.4.1, tried it and still same issue.

**Comment by stax76** [comment]
It starts well here on Win 7 and Win 10 using your settings folder. Since you said you extracted files from one build on top of another build (never a great idea) I tried that but it didn't cause any issue.

From which location do you start? Do you pass any command line arguments?

.NET 4.7 is installed? Please post a log file from 1.4.3.7

**Comment by Zcehtro** [comment]
Ok, here's a big post because I found multiple things.

1. Here's the list of all the file locations related to StaxRip:
https://www.dropbox.com/s/3i2194t3l0lo82q/StaxRip%20file%20list.txt?dl=0

Only have files in in a custom folder in my D: drive, and the settings are in AppData\Roaming\StaxRip x64\.

2. I have Everything, and out of curiosity I typed staxrip and found crash dumps:

![image](https://cloud.githubusercontent.com/assets/10564090/26176999/ae14574a-3b1d-11e7-93fb-af45f5f9a20c.png)

JIC here's an archive with all the *.dmp files, don't know if they're useful or not:
https://www.dropbox.com/s/w1h91kxixttb6lq/CrashDumps.7z?dl=0

3. For the .NET framework, I always use the installer from Ninite.com to update my software, and the latest one I got from them is 4.6.2.

![image](https://cloud.githubusercontent.com/assets/10564090/26177138/2654fc14-3b1e-11e7-8345-1ee563f097ae.png)

You recommend I use the version of .NET you're using? Is it a stable or development?

4. After all this was written, I played around with making clean installs. I tried the following with 1.4.4.1:

- Overwrite previous installation, same settings folder. NOT WORKING
- Clean installation, same settings folder. NOT WORKING
- Clean installation, clean settings folder. NOT WORKING

**Comment by Zcehtro** [comment]
Just tried with 1.4.4.4 and still no luck. I'll download .NET 4.7 and post back.

**Comment by Zcehtro** [comment]
Just installed .NET 4.7 and it's working now.

Issue solved.

**Comment by stax76** [comment]
I added the warning, unfortunately it wasn't working. I uninstalled .NET 4.7 on my Win 7 test system and the system showed a warning telling that there is no .NET runtime. Which OS do you use?

**Comment by Zcehtro** [comment]
Windows 10. I was using an older version of .Net.
