### ISSUE TITLE
Reset audio encoder options when the encoder is switched

### ISSUE THREAD

**Issue by burnchar** [stax76/staxrip#17]
I usually use 16-bit FLAC for movie audio tracks (because it's lossless but smaller than DTS-MA or TrueHD) and because 16-bit stores the same audio quality as 24-bit.

When I change 'Output' in the menu whose window is labeled "eac3to", the default option, "-core", remains even though it is an invalid option for FLAC.
![capture](https://cloud.githubusercontent.com/assets/681802/11704515/a5ef34b0-9ea5-11e5-89c0-cb51f09bea61.PNG)

**Comment by stax76** [comment]
I've changed it to remove '-core' for non dts output.
