### ISSUE TITLE
1.4.3.9 Sources problem

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#170]
Hello Stax and sorry to bother you again, 

tried the 1.4.3.9 and saw the change for manual sources, great thing to make it more clear especially since i don't use vapoursynth, very welcome change, sadly with my custom filters it ends messed up.

example of one of my source filters : 

```
LogoRemove =
    MP_Pipeline("""
    ### platform: win64
    $select:msg:Select Source Type;LogoRemove LSMASHVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LSMASHVideoSource("%source_file%", format = "YUV420P8");LogoRemove LWLibavVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LWLibavVideoSource("%source_file%", format = "YUV420P8");LogoRemove FFVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\both\ffms2\ffms2.dll")FFVideoSource("%source_file%", cachefile = "%source_temp_file%.ffindex", colorspace = "YV12");LogoRemove AviSource|AviSource("%source_file%", Audio = False)$
    ### ###
    ### platform: win32
    LoadcPlugin("C:\Program Files (x86)\AviSynth+\plugins+\AVSInpaint.dll")
    Import("C:\Users\User\Desktop\InpaintFunc.avs")
    InpaintFunc(mask="$browse_file$", loc="$enter_text:Enter logo coordinates ex: 760,1030,-28,-8$", speed=20, mode="$select:msg:Mode;Inpaint for Opaque logo|Inpaint;Deblend for Transparent logo|Deblend;Both if both Opaque and Transparent|Both$", ppmode=1, pp=75, Radius=5.0, reset=true, show=$select:msg:Show Delogoing Steps and Process;Show result only|false;Show steps and process|true$)
    ### ###
    """)
```

Previously  i was using this one by selecting it as source manually, this custom filter opened immediately the file browser to select the picture needed for masking the logo, 
then selected the type of input from a dialog, LSMASHSource, FFVideoSource, LWLibavVideoSource etc. Then the parameters for logo location and some other parameters 
and finally once all this done i opened the video input file simply by clicking "source" normally and browsing for the video input, and i had the final result applied, ready to be encoded.

result of this inside the code editor of the previous editions of Staxrip once all options had been selected after having selected LSMASHVideoSource from the 4 options dialog box  : 
```
MP_Pipeline("""
 ### platform: win64
LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll")  LSMASHVideoSource("%source_file%", format = "YUV420P8")
### ###
### platform: win32
LoadcPlugin("C:\Program Files (x86)\AviSynth+\plugins+\AVSInpaint.dll")
Import("C:\Users\user\Desktop\InpaintFunc.avs")
 InpaintFunc(mask="F:\Mask2.bmp", loc="760,1030,-28,-8", speed=20, mode="Inpaint", ppmode=1, pp=75, Radius=5.0, reset=true, show=false)
### ###
""")
```

Now it seems that all those options present in the $$ select code are also displayed each time i load a source : 
![alt text](https://img4.hostingpics.net/pics/34566220170516170342.png)

Seems like the 4 options in my custom filter to select the type of input are recognized and displayed as 4 different "logoremove" options, the 4 options present in this part of the code : 

>  $select:msg:Select Source Type;LogoRemove LSMASHVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LSMASHVideoSource("%source_file%", format = "YUV420P8");LogoRemove LWLibavVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LWLibavVideoSource("%source_file%", format = "YUV420P8");LogoRemove FFVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\both\ffms2\ffms2.dll")FFVideoSource("%source_file%", cachefile = "%source_temp_file%.ffindex", colorspace = "YV12");LogoRemove AviSource|AviSource("%source_file%", Audio = False)$

Adding another source filter using the same scheme as previous one ( this one is used for vdubx86 input) and it ends up like this : 
![alt text](https://img4.hostingpics.net/pics/97705420170516164714.png)

I have one debug_frameserver filter using only avisource in the custom source filter #code and it displays perfectly once i select an avi for input, this is just perfect to have it there automatically now, problem is those filters having multiples possibilities for source...

Not sure what can be done but maybe not displaying the source is they are inside the $ $ markers, exclude the auto detection if they are in such code part maybe ? 

Thanks a lot in advance.

**Comment by stax76** [comment]
It's uploading.

**Comment by jalba69** [comment]
Hello Stax, Just tried it and it still displays all options for logo remove, doesn't seems to work sadly :/ 

Also the program crash each time after loading a source file while in the demuxing process.

Crashes happens also with a clean non modified profile, will do a bug report just after for the crash with the log file.

**Comment by Mike-83** [comment]
Hello, Stax and jalba69!  Try to install PowerShell_5.1 .  I have not crashes, but hang`s when demuxing process, and when script re-mux v2 demuxing was error about  PowerShell

**Comment by jalba69** [comment]
I have net4.7 and my powershell version is this apparently : 

Name                           Value
----                           -----
PSVersion                      5.1.14409.1005
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.14409.1005
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

Will check if there is a newer one, had no issues with Staxrip 1.4.3.9 too.

**Comment by stax76** [comment]
@jalba69 

another build is uploading

@Mike-83

it already has warnings about .NET 4.7 and PowerShell 5

**Comment by jalba69** [comment]
Build 1.4.2.2 seems to work  better, got only 2 entires with "LogoRemove" instead of 4 previously, almost there. 

It's even better than before as it will then automatically execute the rest of the code and open the file browser to select the picture then the dialog boxes for the settings needed,  just by loading a source file, have to make 2 steps before so now it will be even easier.

Sadly I still have the crash after demuxing or loading the re-mux3 script like explained here https://github.com/stax76/staxrip/issues/173

Thanks a lot

**Comment by stax76** [comment]
So there is still one entry too much? Please post the code from all of your source filter profiles.

**Comment by jalba69** [comment]
Yes there is 2 entires when there should be only 1 , there was  4 before this last version, here it is my custom source entires : 

https://pastebin.com/3HWi53r9

You can skip the virtualdubplugin one,  focus on logoremove one , the other one is to use debugframeserver in vegas, supporting only x86 codec that cannot be read by the program wihtotu this trick.

**Comment by stax76** [comment]
I don't get a double entry, what file type were you opening?

**Comment by jalba69** [comment]
That's weird then, i tested mp4 and mov and always get double entires, even ifi leave only the logoremove filter and remove the other custom ones.

Finishing to download last uploaded version and will try again then report back

**Comment by jalba69** [comment]
Tested 1.4.4.3, default settings, just adding the LogoRemove as extra source filter, not the 2 others and opening mov,mp4 or avi i get this : 

![alt text](https://img15.hostingpics.net/pics/45192420170517191233.png) 

Only thing added on the top of the defautl settings is  LogoRemove filter code in the source filter section 

Crashes seem fixed on this build but need to test more.

**Comment by stax76** [comment]
I tested mkv which was fine, not so mov now I notice, investigating

**Comment by jalba69** [comment]
You are right, had not tested MKV myself, just did and only one LogoRemove entry there, but for other formats it brings 2.

I feel sorry for the headache i am giving you with this :/

**Comment by stax76** [comment]
No problem, sorry about the bugs, should be fine in the build currently uploading. I'll stop for today, cu.

**Comment by jalba69** [comment]
No need to be sorry, if one should be it's really me for giving you so much trouble, don't know how i can thank you enough for all the efforts you put into this, hopefully my pockets will be less broken soon  so i could make a paypal donation at least.

Btw i saw you added the possibility to add a cover to mkv's and mp4's natively, thanks also for that, that's a great thing.

You done more than enough and deserve some good rest yes, i'll report later after testing new build.

Thanks again for all Stax.

**Comment by jalba69** [comment]
It works perfectly, the LogoRemove filter is even easier to use than before, one click for all process, absolutely wonderful.

Thank you

**Comment by Gabarito007** [comment]
@jalba69, may you, please, explain how to "install" and use your script to Logo remove?
I'm doing it by Virtualdub plugin and frame server, but if I could use on the fly, directly, by Staxrip, it would be great!

**Comment by jalba69** [comment]
Hi,
 i will try to explain with a concrete example but i'm not sure it is easier than Vdub,  I usually get better results using this than delogo and such plugins in Vdub that's why i use it, and hopefully will be able to continue use it for a long while even if it's often slower especially when the videos input resolution is high, on medium and low resolution it's ok i guess,

- The logo remover plugin works only under x86 version of avisynth so Staxrip can't run it directly, to make it work with staxrip in x64 you need first the MP-Pipeline plug-in that you find here ( first link ) : 
http://forum.doom9.org/showthread.php?p=1746479#post1746479

Once downloaded you put all the content from the **"64"** folder into the avisynth plugin64+ folder, here :
**"C:\Program Files\AviSynth+\plugins64+\\"**  You don't need the content in "86 "folder, just what is inside the "64" into avisynth plugins64+  folder.

This first part is just to run x86 stuff in avisynth x64 that Staxrip uses.

- Then you need the stuff for the logo remover itself, first the .dll located here, from this zip  you just need the  **"AVSInpaint.dll"** file: 
http://forum.doom9.org/attachment.php?attachmentid=8134&d=1203776927
and then this is the script part, direct link to the script : http://avisynth.nl/images/InpaintFunc.avs
save it as **"InpaintFunc.avs"**
more infos on this one and the options of the logo remover options can be found here : http://avisynth.nl/index.php/InpaintFunc
Put those 2 files somewhere, maybe a folder on desktop, those 2 files paths will need to be added in the next part.

- Now comes my Staxrip custom source filter that gave a headhache to Stax today, add this code into staxrip as new source filter possible, but first modify the existing  paths for AVSInpaint.dll and to the InpaintFunc.avs to match where you put the ones you got from the previous step, you can put both files from the previous step inside a folder on the desktop for example )  : 

```
 LogoRemove =
    MP_Pipeline("""
    ### platform: win64
    $select:msg:Select Source Type;LogoRemove LSMASHVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LSMASHVideoSource("%source_file%", format = "YUV420P8");LogoRemove LWLibavVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LWLibavVideoSource("%source_file%", format = "YUV420P8");LogoRemove FFVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\both\ffms2\ffms2.dll")FFVideoSource("%source_file%", cachefile = "%source_temp_file%.ffindex", colorspace = "YV12");LogoRemove AviSource|AviSource("%source_file%", Audio = False)$
    ### ###
    ### platform: win32
    LoadcPlugin("C:\Program Files (x86)\AviSynth+\plugins+\AVSInpaint.dll")
    Import("C:\Users\User\Desktop\InpaintFunc.avs")
    InpaintFunc(mask="$browse_file$", loc="$enter_text:Enter logo coordinates ex: 760,1030,-28,-8$", speed=20, mode="$select:msg:Mode;Inpaint for Opaque logo|Inpaint;Deblend for Transparent logo|Deblend;Both if both Opaque and Transparent|Both$", ppmode=1, pp=75, Radius=5.0, reset=true, show=$select:msg:Show Delogoing Steps and Process;Show result only|false;Show steps and process|true$)
    ### ###
    """)
```

- Now for the next step to test if it works i took one trailer video, and added a watermark on the middle of it , video is located here :  http://www.mediafire.com/file/9dny8qhvi4cv64h/Earth_Trailer_BBC.mkv

At this step we need to create a picture mask for the logo, load the video in staxrip using "automatic" option,  then open the preview mode and extract one frame as .bmp ( right click on the preview video > Tools > save bitmap ).
 Then load the picture in your favorite picture editor.

- to make it easy add one transparent layer to the picture and start to paint the logo with pure white color
- once done paint the background in full black, ( fill it with the bucket tool ), then save it with the name you want but with bitmap .bmp extension.

At the end we have one black picture and a logo covered in white that is our mask, like here for the video example: 
![alt text](https://img4.hostingpics.net/pics/979191mask.png)
Download this picture in full size to test with the example video later, direct link here : http://www.mediafire.com/view/n329j6iv96ixtx6/mask.bmp , the one embed above is a png, you need the bmp from the link .

- The next step is define the location of the logo to treat, most pictures editors let you see the x,y positions of your cursor, i added one example here for this picture:

![alt text](https://img4.hostingpics.net/pics/527242Howtogetcoords.png)
Here it ends up in **756,500,-758,-532** for coordinates , inpaintfunc.avs script allows to treat an area without entering exact coordinates like seen here http://avisynth.nl/index.php/InpaintFunc in options at the **string  loc = null** option, you can treat a region instead of a precise location but i prefer this more precise way with coords.

If needed in the next days I can modify my source filter to use one of those regions instead of exact coordinates, just having a list of regions to treat instead of coords, like top left, top right, bottom left etc, should be possible to be done without much efforts, just need time, if needed.

Our video example is 1920x1080px, same for the mask picture, the 2 first coordinates are the x,y red corner i draw at the top left of the logo location ( more or less as long as it covers the logo position ), the next 2 coordinates are video width and height less the x,y coordinates of the red corner position i draw at the bottom right of the logo position, might be more clear in the picture just above then explained like this ;)

- And that 's all we needed, you fire up again Staxrip, open the video example as source, this time instead of "automatic" you select select "RemoveLogo" then again browse but this time for the mask white and black .bmp picture, 

then enter coordinates, then select the type of source you open with , ffdshow or LSMASHSource etc, ( if you don't know what to use simply check the first time you import the video to take a picture .bmp what stxrip uses in automatic mode ), here for the MKV video example it will be FFvideosource.

Then on the next steps select the type of logo to remove, opaque , transparent of both, ( here for the video example pick opqaue ) ,  then option "show result only", ( 2nd option "show process" can help for fine tuning ).

- Depending your machine it could look like staxrip is freezing a bit, depends of the machine, the settings used and the video length and resolution too, mine settings are pushed a bit so it needs to read entire video etc , anyays do not worry and just wait a bit for the mask file to be generated and look preview, it it's really too slow on a weaker machine you can use this as source, a more relaxed one not reading the entire video and not generating a new mask file each time a setting change : 

 ```
LogoRemove =
    MP_Pipeline("""
    ### platform: win64
    $select:msg:Select Source Type;LogoRemove LSMASHVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LSMASHVideoSource("%source_file%", format = "YUV420P8");LogoRemove LWLibavVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LWLibavVideoSource("%source_file%", format = "YUV420P8");LogoRemove FFVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\both\ffms2\ffms2.dll")FFVideoSource("%source_file%", cachefile = "%source_temp_file%.ffindex", colorspace = "YV12");LogoRemove AviSource|AviSource("%source_file%", Audio = False)$
    ### ###
    ### platform: win32
    LoadcPlugin("C:\Program Files (x86)\AviSynth+\plugins+\AVSInpaint.dll")
    Import("C:\Users\User\Desktop\InpaintFunc.avs")
    InpaintFunc(mask="$browse_file$", loc="$enter_text:Enter logo coordinates ex: 760,1030,-28,-8$", speed=5, mode="$select:msg:Mode;Inpaint for Opaque logo|Inpaint;Deblend for Transparent logo|Deblend;Both if both Opaque and Transparent|Both$", ppmode=1, pp=75, Radius=5.0, show=$select:msg:Show Delogoing Steps and Process;Show result only|false;Show steps and process|true$)
    ### ###
    """)
```

Results can be fine tuned using Staxrip built in editor and changing a few values and settings, this is up to you, I did not spent much time on this one, just used my default settings but probabyl the result can be improved a tiny bit wiht a lot of patience, more on the settings posible here : http://avisynth.nl/index.php/InpaintFunc


It's a bit harsh to start up with this, but once done all you need to do is load up your video as usual in Staxrip using "automatic" mode, check with what Staxrip opens it, (ffvideosource,LSMASHSource etc), then open the preview mode and save a .bmp image, open this image in your editor, draw the mask for the logo to remove, then get coordinates and done.

Next you load your video in staxrip again and all you have to do is select "LogoRemove" then browse for the mask picture created and enter the settings for coordinates + a few clicks. Takes only 3 minutes maximum to do all this once used to it.

One last thing, a few comparison frames from the video with watermark before/after: 
![alt text](https://img4.hostingpics.net/pics/79900020170518020210.jpg)
![alt text](https://img4.hostingpics.net/pics/48544320170518020223.jpg)

Not perfect and probably could end up better with some fine tuning in the settings but i don't have the patience anymore to do it after this long post :p 

Hope i forgot nothing and that it is clear enough, i bet it isn't tho, but i done the best i could to explain the process, and sorry for hijacking the thread Stax ;)

**Comment by Gabarito007** [comment]
> Hope i forgot nothing and that it is clear enough, i bet it isn't tho, but i done the best i could to explain the process, and sorry for hijacking the thread Stax ;)


Thank you very much, jalba69!
Your explanations are very detailed and clear.
And results you get from your scripts and methods are first class quality.
Congratulations! 👍 

Later, I'll try to duplicate here with my videos.
Thanks again.

**Comment by Gabarito007** [comment]
One more question.
I can't add a new source filter as described here:
>...add this code into staxrip as **new source filter** possible, but first modify...

What do you mean?
At filter link, there are:
Source
Replace
Insert
Add
...

At Source, there are:
Automatic
AviSource
DGSource
...

At Add, there are:
Source
Misc
Field
...

Where to put that code?

**Comment by jalba69** [comment]
Hi,
Make a right click in the filters area then select profiles from the contextual menu, like here : 

![alt text](https://img4.hostingpics.net/pics/62738620170518151311.png) 

Then a new window will appear and under (sources ) part you copy the code , like here : 

![alt text](https://img4.hostingpics.net/pics/21421020170518151547.png) 

I changed a bit the code so you have also the speed option now to speed it up a bit, also removed the "reset=true" parameter so it generates mask data only once and not reset each time : 

code to copy like on screenshot above : 

```
 Logo Remove =
    MP_Pipeline("""
    ### platform: win64
    $select:msg:Select Source Type;LogoRemove LSMASHVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LSMASHVideoSource("%source_file%", format = "YUV420P8");LogoRemove LWLibavVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LWLibavVideoSource("%source_file%", format = "YUV420P8");LogoRemove FFVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\both\ffms2\ffms2.dll")FFVideoSource("%source_file%", cachefile = "%source_temp_file%.ffindex", colorspace = "YV12");LogoRemove AviSource|AviSource("%source_file%", Audio = False)$
    ### ###
    ### platform: win32
    LoadcPlugin("C:\Program Files (x86)\AviSynth+\plugins+\AVSInpaint.dll")
    Import("C:\Users\Users\Desktop\InpaintFunc.avs")
    InpaintFunc(mask="$browse_file$", loc="$enter_text:Enter logo coordinates ex: 760,1030,-28,-8$", speed=$select:msg:Select Logo Analyze Speed;Very Slow - Analyze 100% of the Video|20;Slow - Analyze 75% of the Video|15;Medium - Analyze 50% of the Video|10;Fast - Analyze 25% of the Video|5;Very Fast - Analyze 10% of the Video|5;Ultra Fast - Analyze 5% of the Video|1$, mode="$select:msg:Mode;Inpaint for Opaque logo|Inpaint;Deblend for Transparent logo|Deblend;Both if both Opaque and Transparent|Both$", ppmode=1, pp=50, Radius=3.0, sharpness=75.0, preblur=8.0, postblur=4.0, reset=false, show=$select:msg:Show Delogoing Steps and Process;Show result only|false;Show steps and process|true$)
    ### ###
    """)
```
Just copy this to a text file and modify those 2 lines to match the paths of your own files before adding it into Staxrip : 
 LoadcPlugin("**C:\Program Files (x86)\AviSynth+\plugins+\AVSInpaint.dll**")
 Import("**C:\Users\user\Desktop\InpaintFunc.avs**")

Btw what was the plugin from Vdub you was using for this ?  The Mp-Pipeline thing allow to use vdub x86 plugins in Staxrip too, you juts need to do the settings in vdbud, then collect the settings and pass them to staxrip.

Good luck ;)

**Comment by Gabarito007** [comment]
I'm using:
DeLogo 1.3.2
Logoaway 4.01
RegionRemove
MSU LogoRemover
DonaldGraft Logo 1.7b2

But, in fact, I use most RegionRemove.

I'll try your tips later.

**Comment by jalba69** [comment]
Using MP-Pipeline it is possible to try run directly soem Vdub scripts in avisynth and Staxrip, adapted my personal Virtualdub source filter and made a custom menu for 4 of your Vdub scripts, did not added the MSU one as there is two of them available and seems like it needs 2 passes so probably won't work.

All you need is to install the MP-pipeline files that was the first step i described.
Then add this code as source filter ( like in my previous post example ) : 

```
VirtualDubPlugins =
    MP_Pipeline("""
    ### platform: win64
    $select:msg:Select Source Type;LSMASHVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LSMASHVideoSource("%source_file%", format = "YUV420P8");LWLibavVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\avs\L-SMASH-Works\LSMASHSource.dll") LWLibavVideoSource("%source_file%", format = "YUV420P8");FFVideoSource|LoadPlugin("%startup_dir%Apps\Plugins\both\ffms2\ffms2.dll")FFVideoSource("%source_file%", cachefile = "%source_temp_file%.ffindex", colorspace = "YV12");AviSource|AviSource("%source_file%", Audio = False)$
    ### ###
    ### platform: win32
   ConvertToRGB()
    $select:msg:Select VirtualDub Plugin;DeLogo 1.3.2|LoadVirtualDubPlugin("C:\Program Files (x86)\VirtualDub-x86\plugins32\delogo.vdf","delogo") delogo;DonaldGraft Logo 1.7b2|LoadVirtualDubPlugin("C:\Program Files (x86)\VirtualDub-x86\plugins32\Logo.vdf","logo17b2") logo17b2;RegionRemove|LoadVirtualDubPlugin("C:\Program Files (x86)\VirtualDub-x86\plugins32\RegionRemove.vdf","RegionRemove") RegionRemove;Logoaway 4.01|LoadVirtualDubPlugin("C:\Program Files (x86)\VirtualDub-x86\plugins32\logoaway.vdf","logoawayv401") logoawayv401$$enter_text:Enter VirtualDub plugin settings ( Example: (1, "", "", "", "", "H:/mask2.bmp", 15, 40, 0, 0) )$
    ### ###
    """)
```
Here all paths lead to C:\Program Files (x86)\VirtualDub-x86\plugins32\  where are stored vdub plugins usually, if you have vdub installed somewhere else and paths differ just set the paths correctly in the code before ;) 

Now you need is get the settings from Virtualdub, to do this you load you video in virtualdub, apply your logo remover filter and do the settings for it,  once finished and satisfied with the results you go to "File" menu and select " Save processing Settings".

It will create a vdf file, you open this file in a text editor and it will look like this : 

> VirtualDub.audio.SetSource(1);
VirtualDub.audio.SetMode(0);
VirtualDub.audio.SetInterleave(1,500,1,0,0);
VirtualDub.audio.SetClipMode(1,1);
VirtualDub.audio.SetEditMode(1);
VirtualDub.audio.SetConversion(0,0,0,0,0);
VirtualDub.audio.SetVolume();
VirtualDub.audio.SetCompression();
VirtualDub.audio.EnableFilterGraph(0);
VirtualDub.video.SetInputFormat(0);
VirtualDub.video.SetOutputFormat(0);
VirtualDub.video.SetMode(3);
VirtualDub.video.SetSmartRendering(0);
VirtualDub.video.SetPreserveEmptyFrames(0);
VirtualDub.video.SetFrameRate2(0,0,1);
VirtualDub.video.SetIVTC(0, 0, 0, 0);
VirtualDub.video.SetCompression();
VirtualDub.video.filters.Clear();
VirtualDub.video.filters.Add("Region Remove");
VirtualDub.video.filters.instance[0].Config(100, 100, 128, 96, 0, 0, 0, 0, 0, 0, 10, 5, "");
VirtualDub.audio.filters.Clear();
VirtualDub.subset.Clear();
VirtualDub.subset.AddRange(0,1420);
VirtualDub.video.SetRange();

From this file all  you need is to copy the settings, it's the part in bold:  **(100, 100, 128, 96, 0, 0, 0, 0, 0, 0, 10, 5, "")** 

Then launch Staxrip, load your video file source, select " Virtualdub Plugin" : 
![alt text](https://img4.hostingpics.net/pics/89944820170518182404.png)

Next step you paste the settings you have copied from the vdf file : 
![alt text](https://img4.hostingpics.net/pics/82038620170518182541.png)

Then select the type of source file ( load you video normally in automatic mode first if you don't know which one to choose at this step ) : 
![alt text](https://img4.hostingpics.net/pics/46234620170518182547.png)

Then select the logo remover plugin you made the settings for : 
![alt text](https://img4.hostingpics.net/pics/11955120170518182742.png)

And it should work directly in Staxrip without anymore the need for framserving from vdub.

Note that some plugins don't export the full parameters so there might be some differences between the result in vdub and in Staxrip, MSU plugins don't export all for what i was told, the 4 ones here i did not tested them much as not using them beside Delogo and this was long time ago, so you need to test and see by yourself ^^

**Comment by Gabarito007** [comment]
jalba69, man, I'm impressed!
It's clear that you master all this stuff.
And more: you enjoy a lot to share your knowledge with others.
Very nice!

I'm afraid we're messing this room, where stax76 use to solve Staxrip problems.
Please, send me a message to `gabarito007 at gmail dot com` because I have few more questions.
See ya.
;)
