### ISSUE TITLE
Improvment : add .265 .h265 .hevc .hvc files reconized by the source file browser please

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#171]
Last thing i will bother you with ( I really hope ) : 

When selecting a file as source StaxRip recognize and filter automatically a bunch of file formats as seen here : 

![alt text](https://img4.hostingpics.net/pics/17389420170516183431.png)

Will it be possible to add also the following ones to the list please : 
.265
.h265
.hevc
 .hvc 

If you wonder about **.hvc** one it's the extension mp4box uses when it extracts a hevc stream from a mp4 using his own demuxing option, a mp4 containing x265 video stream will have the video track extracted as .hvc

Not a big deal but it will spare the need to switch to " all files (*)" and it's always better to have less files displayed as been filtered with the first option 

Thank you very much.

**Comment by stax76** [comment]
Thanks for reporting, it's fixed in the next build.

**Comment by jalba69** [comment]
Just saw they were added on last version, thanks a lot Stax
