### ISSUE TITLE
facing problems with FFMPEG

### ISSUE THREAD

**Issue by D-Prince** [stax76/staxrip#172]
facing some problems with latest **ffmpeg** (staxrip 1.4.0). when im trying to using x264(2 pass) through ffmpeg, its stop working in the middle of 1 pass. but x264 works fine individually. i didnt face this kind of problem while using **v1.3.7**.
how can i solve this problem?

**pc config:** W10(x64) pro, i5-7600k,  16GB ram, gtx 1060 gpu

**Comment by stax76** [comment]
Hi, you can solve it the same way almost any problem can be solved, replace components with alternatives. Use only a source filter and not any other filter, replace it with a alternative source filter, replace the ffmpeg build with the ffmpeg build from 1.3.7.

The problem can only be AviSynth or ffmpeg or the source, it's unlikely that the problem is caused by staxrip.

**Comment by D-Prince** [comment]
i see,  thanks,,,,  it only works with  "AviSynth" thou,  n also i tried replacing ffmpeg (v1.3.7) but no good. unsupported.

**Comment by D-Prince** [comment]
Disappointing. :( back to v1.3.7
i've tried every single source possible, i thought its working fine with AviSynth ( LWLibavVideoSource) but unfortunately not. it stops in the middle of 1st pass. tried re install every soft n its perfect OK with 1.4.0.
could u please check it and find out whats causing this problem?

**Comment by stax76** [comment]
Here it works.

https://pastebin.com/KLmn79QZ

**Comment by D-Prince** [comment]
it might work with ffmpeg 3.2.2 but not working with ffmpeg 3.1.5. 
btw, from where can i download 1.4.4.5 version, that you are using ?
is there any way to make staxrip 1.4.0.0 to support 3.2.4 (stable) /3.3.1 ?

**Comment by stax76** [comment]
on the main page:

https://github.com/stax76/staxrip

there is a download section where you can find test builds:

https://github.com/stax76/staxrip#download

alternatively you can use: Main Menu > Help > Web Site > Test Build

I only provide support for test builds.

**Comment by D-Prince** [comment]
thanks a lot.
