### ISSUE TITLE
1.4.4.1 - Crash while in demuxing process

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#173]
Hello, 

on a fresh installation with default settings, each time i load a source file it starts to demux it and it crashes.

Tried with avi, mov, mp4 input and each time it crashes.

Selecting an avi while having manual for input
On the options menu to select a source select " automatic"
it starts to demux and crash.

One log file from one of the crash reports : https://pastebin.com/665jPrVV

Thank you.

**Comment by jalba69** [comment]
Another different crash : 

Just open staxrip, select the re-mux3 script, select a container mkv or mp4 then this happens : 

https://img15.hostingpics.net/pics/31122720170517165147.png



No log file for this one

**Comment by jalba69** [comment]
Still happening with 1.4.4.2 sadly.

**Comment by stax76** [comment]
new build is uploading

**Comment by jalba69** [comment]
Seems fixed in 1.4.4.3, thanks a lot
