### ISSUE TITLE
1.4.4.4 : open MP4 "Container Options" crash the program 

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#174]
I'm sorry but found something else in last version : 

Open staxrip, don't load anything
Select MP4 for container
Click "Container Options" in the GUI and it crashes with this message : 

https://pastebin.com/wCa19aDj

No problem with MKV container or any other container in the list, only MP4 crash.

Really Sorry Stax :/

**Comment by stax76** [comment]
It was due to a performance optimization I did, populating the language drop down became significantly slower in a .NET or Windows update, it has also now much more languages, about 280 I think, I'll upload a fix shortly.

**Comment by stax76** [comment]
Should be up in 2 minutes.

**Comment by jalba69** [comment]
Hello, 
Seems to work fine now, will test a bit more and mess with some stuff as usual and hopefully will find nothing else as problem.

Thanks a lot Stax.
