### ISSUE TITLE
Twice Index file

### ISSUE THREAD

**Issue by Mike-83** [stax76/staxrip#176]
ver. 1.4.4.4  When choose Filter Setup --> Vaporsynth and Source - automatic and add a file -everything is fine. - Index with ffmsindex create  ( filename.ffindex)  in temp directory
But if leave Source as default - ffms2 then Index with ffmsindex create ( filename.ffindex)  in temp directory  
after that write "Writing index... done." and feel like hang, but in that time again read file and create (filename.mkv.ffindex) in source directory from which I add file

**Comment by stax76** [comment]
I added support for automatic source filter in filter setup profiles and made automatic default (without to force to reset the default filter setups), I think this was the reason and it also had a bug causing a crash, I'll upload a new build shortly.

**Comment by stax76** [comment]
Should be up in 2 minutes.

**Comment by Mike-83** [comment]
I tested new build and it`s work !  In automatic and in ffms2 as source create one index file.
Issue solved
Thanks for your work!!
