### ISSUE TITLE
crash open bluray or file 

### ISSUE THREAD

**Issue by slushay** [stax76/staxrip#177]
Exception

Ссылка на объект не указывает на экземпляр объекта.

System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в StaxRip.MuxerForm.MuxerForm_Shown(Object sender, EventArgs e) в D:\Projekte\VS\VB\StaxRip\Forms\MuxerForm.vb:строка 592
   в System.Windows.Forms.Form.OnShown(EventArgs e)
   в System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   в System.Windows.Forms.Control.InvokeMarshaledCallbacks()

**Comment by stax76** [comment]
Hi,

if this wasn't test build 1.4.4.5 then please try it first.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by slushay** [comment]
Ok, error does not repeat
