### ISSUE TITLE
mp4 

### ISSUE THREAD

**Issue by liceee** [stax76/staxrip#178]
Exception

未能从程序集“mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”中加载类型“System.ValueTuple`3”。

System.TypeLoadException: 未能从程序集“mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089”中加载类型“System.ValueTuple`3”。
   在 StaxRip.MainForm.ShowSourceFilterSelectionDialog(String inputFile)
   在 StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) 位置 D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:行号 1542

**Comment by stax76** [comment]
Hi,

1.4.4.5 should work with .NET 4.7.

.NET 4.7 is required on systems prior Windows 10 Version 1703 (Creators Update)

https://www.microsoft.com/en-us/download/details.aspx?id=55170
