### ISSUE TITLE
StaxRip window disappears after coming back from another user session

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#179]
I have more than one user on my PC.
I leave StaxRip working a long list of jobs.
I switch to another user and SR continues running in the other user environment.
When I come back the window is gone, but the program is still running.

Screenshots here:

All windows active and open, but SR window with active job is gone:

![screenshot 2017-05-20 00 35 50](https://cloud.githubusercontent.com/assets/10564090/26273355/5bedccd4-3cf4-11e7-9b04-de4829d64709.png)

Task manager showing StaxRip currently running:

![image](https://cloud.githubusercontent.com/assets/10564090/26273360/7fb2e2a8-3cf4-11e7-9c43-ec91eecd6d3c.png)

x264 is currently running:

![image](https://cloud.githubusercontent.com/assets/10564090/26273367/b6ba84d6-3cf4-11e7-9f28-07d561b21f37.png)

**Comment by Zcehtro** [comment]
I wanted to check if the window would pop up again after the current job completed so I unchecked every job on the job list and waited for the window to appear again.

It happened.
Out of nowhere, it just popped up, like a brand new window.

**Comment by stax76** [comment]
The build from today has totally different job processing, every job is a new instance which shuts down after completion, I switched user with WinKey+L, on Win 10 I cannot reproduce your issue with this build.

**Comment by Zcehtro** [comment]
I just noticed that StaxRip minimized to tray.
It might be that the program was minimized and I never realized it, and then when the job finished it popped back up.
If this is the case then big oops on my part.

On the same note, I haven't found options to configure how the program behaves when minimized and with the system tray icon.
Perhaps options to configure this:
- Minimize to task bar (this should be normal/default window behaviour)
- Minimize to system tray
- Show system tray icon at all times
- Show system tray icon at all times even when minimizing to task bar

**Comment by stax76** [comment]
If it's not difficult to implement I can add a tray option, please create a new issue otherwise I might forget it.

**Comment by Zcehtro** [comment]
Here you go: https://github.com/stax76/staxrip/issues/184
