### ISSUE TITLE
Save audio settings

### ISSUE THREAD

**Issue by burnchar** [stax76/staxrip#18]
Every time I encode a video which includes a lossless track, I need to switch from its format to FLAC and add "-down16" (and, on a note related to another request, remove "-core").
I somehow often forget to do at least one of these steps, then need to start all over much later.
First world problems, right?
It would be really great if StaxRip were to remember my previous audio transcoder settings, or even better, support profiles like it does for the audio transcoding.
I understand this would be tougher to implement than video profiles in some ways because not all profiles make sense for all videos. FLAC, for example, would be a terrible format if the source audio was MP3. This can just be something the user has to remember to set correctly, however.

![capture](https://cloud.githubusercontent.com/assets/681802/11704621/83057760-9ea6-11e5-9c39-a5c384cfe5bf.PNG)

**Comment by stax76** [comment]
The dialog is still somehow limited though I improved it much last year. I prefer and recommend to rip with MakeMKV which has some automation and conversion options though difficult to config. When you rip DTS-MA with eac3to you can convert it to FLAC with StaxRip later too, FLAC is supported by StaxRip's audio conversion options so you don't necessarily have to convert it while ripping. A relative simple way to implement some automation profiles for the eac3to dialog would be using a DataGridView I think, it's a good idea but I can't promise if and when I have time for it.

**Comment by stax76** [comment]
profiles will be supported in the next build

**Comment by burnchar** [comment]
Awesome!
Thank you for all you do for the community. It makes a difference.
