### ISSUE TITLE
Dump-Cover issue with file names having spaces.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#180]
Hello Stax, 

I noticed some issues when dumping covers from a MP4 when the filename have spaces in it, from the log file we can see this command for example : 

H:\StaxRip-x64-1.4.5.1-test\Apps\MP4Box\MP4Box.exe -dump-cover "H:\2016-05-10 17.11.03.mp4" -out H:\2016-05-10 17.11.03_temp\cover.jpg

I think the problem is that the last path for the output is missing the quotes "" around it so it causes some issues and an error message when filenames or paths have spaces in them.

Thanks a lot :)

**Comment by stax76** [comment]
Hello Yanak, next build fixes it.

**Comment by jalba69** [comment]
Seems fixed in last build, thanks a lot for the quick fix.
