### ISSUE TITLE
Add cover to MP4, picture filename should not be limited to "cover" only.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#181]
Hi Stax,

noticed that for adding a mp4 cover we need to have the name of the picture named "cover" or it won't be accepted and we will get a warning about it, on the GUI,

![pic5](https://img4.hostingpics.net/pics/56787920170522135222.png)
_Only the file extension should be checked here for MP4's, not the name of the input picture itself_

For MKV's i know you need to have a specific names for cover files and this should stay for mkv's,  but for MP4's as far as i know it does not matter, the cover can have whatever names for input  it does not matter as the cover will somehow be turned automatically by mp4 into "cover" that i know, at least never had any problem using a lot of different names for input cover, 

the output itself when using dump-cover command will always be "cover" tho, automatically set by mp4box.

So it will be nice to have this input file name limitation removed for MP4's when adding a cover please.

Thank you very much

**Comment by stax76** [comment]
Hi Yanak, I Changed it for the next build.

**Comment by jalba69** [comment]
Tested and seems to work with any input name now, perfect,

Thanks a million for all the nice work you put into this Stax
