### ISSUE TITLE
Some little GUI imperfections 

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#182]
Hi Stax, 

noticed that here in the batch muxer for mp3 the box for language selection is a bit too small : 
![pic1](https://img4.hostingpics.net/pics/27592220170521184601cr.png)

Also here in the Event Command Editor the 2 lines are overlapping each other  : 
![pic2](https://img4.hostingpics.net/pics/98703020170521185053.png)

Not a big deal or stopper at all but better report it.

Thank you.

**Comment by stax76** [comment]
Please try the last build. What DPI are you using?

**Comment by jalba69** [comment]
Hi stax, 

Just tested the last build and it seems fixed for both :
![pic](https://img15.hostingpics.net/pics/59081420170522232336cr.png)

according to one script you had posted some times ago on the forum to check this my DPI is 96/96.

Thanks a lot.

**Comment by stax76** [comment]
Some of the forms are designed at 144 DPI, in the last week I converted many forms to 288 DPI, today I tested down scaling from 288 to 144 DPI, next time I'll test 96 DPI. The command drop down button is perfectly aligned on my system.

**Comment by jalba69** [comment]
I never really tried to change the DPI on my setup, i know i can increase it a bit, right now it's a 100% with 96/96, might try 125 % tomorrow when pc will not be busy doing tasks but probably won't keep it, i'm fine with how it is on this not so young screen :p Would like to have 144 and more if financial ever allow it... one day maybe.

The text display seems always centered for me with all languages i selected in drop down box tho, it's good as it is for me.

Thanks a lot.

**Comment by stax76** [comment]
I use a 4K screen with 288 DPI, before I used Full HD screen with 144 DPI, both with 27". I've relative bad eyes. I just tried 96 DPI with the magnifier tool, there are lot's of issues that don't show with 144 or more DPI, most notably icons in menus and buttons are trimmed at the bottom.

**Comment by jalba69** [comment]
Tried quickly 125% for 120/120 DPI and I see the difference now : 
![pic](https://img4.hostingpics.net/pics/99224720170523132610cr.png)

Those little thing are the kind of stuff i could not even suspect and just consider normal on my setup, as long as it's not obvious like on things reported initially  :p 

This said i don't like much the 120dpi, on my 1080p 22" screen it looks too big and I'm no used to this, will return to 96 DPI but might serve some days when my eyes will be too tired, ( too often spending too much time in front of the screen).

I'm not sure but I believe there is still plenty of 96DPi screens around, wish I could upgrade for a larger screen with more DPI's for better comfort, a bit like yours.

Thanks a lot.

**Comment by stax76** [comment]
I've worked on 96 DPI support, it should be much better then the last build.

**Comment by jalba69** [comment]
Yup it renders way better now :
![pic](https://img4.hostingpics.net/pics/54584720170523231440crcrcr.png)
and it makes everything more compact at the same time.

Thanks a lot for all this Stax.

**Comment by stax76** [comment]
Hi Yanak, in the build from today all dialogs should scale well on 96 DPI.

**Comment by jalba69** [comment]
Seems all good after a quick exploration.

Thanks a lot.
