### ISSUE TITLE
Improvment - Add option to auto close Jobs list window when clicking start

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#183]
Hello Stax, hopefully my last post for today :p 

Saw the change for process running now separately for better performances, ain't a problem at all for me but would like to see a tiny option added if possible, either in the GUI or in the general settings : 

When clicking "Start" button in the Jobs list, the jobs list window closing itself automatically, maybe like this with a small tickbox : 
![pic3](https://img4.hostingpics.net/pics/16133720170521184810.png)
Or simply an option somewhere in the settings to auto close it when pressing Start Button. 

Right now even if there is only one job the window stay opens, we need to close it manually, and when the job is completed it stays open still like this : 
![pic4](https://img4.hostingpics.net/pics/40398820170521184820.png)
Apparently buttons are grayed out, it's not even possible to import a job so there is no reasons to keep it open imo.

Again not a big problem at all, but will be better to have this auto closing option instead of windows pilling up, at least from my point of view, not sure it it makes sense for you or other users point of view tho.

Thanks in advance.

**Comment by stax76** [comment]
I changed it to close if there is only one active job, if there are more it stays open because the user might want to start a second instance.

**Comment by jalba69** [comment]
Hi,
Just tested with one job, perfect as it is  for me.

Thank you very much.
