### ISSUE TITLE
[Feature] Program behaviour for system tray icon and task bar

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#184]
I suggested in another thread the concept of having options to configure how the program behaves when minimized and with the system tray icon.
Options to configure this would be like this:

- Minimize to task bar (this should be normal/default window behaviour)
- Minimize to task bar and show system tray icon at all times
- Minimize to system tray and show system tray icon at all times

I'm pretty sure these three cover all situations.

Thread where this originated: https://github.com/stax76/staxrip/issues/179#issuecomment-303756889

**Comment by stax76** [comment]
Thinking about it, I try to avoid adding features that are not very useful, which behavior would you like to use and why?

**Comment by Zcehtro** [comment]
I like to have it simple and not confusing.
If the program minimizes, I usually expect it to minimize to the taskbar like every program usually does.
When the program goes elsewhere it's because there's some added feature that makes it more complex and less simple.

Suggesting these features is only about giving more control to the user on how StaxRip operates; configuring it to work how the user wants it to work. Leaving the settings on a specified default should make it less confusing and less noticeable of the change to those that don't want it changed.

**Comment by stax76** [comment]
I've added a setting to minimize to tray instead of the task bar, it's not enabled by default and will be available in the next build.

**Comment by Zcehtro** [comment]
Cool. I'll test it when I dl it.

**Comment by stax76** [comment]
It's online now, I hope it works.
