### ISSUE TITLE
Video comparison tool, add more extensions automatically recognized.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#185]
Hello Stax,
one very minor thing : 

In the video comparison tool the only extensions "recognized"  automatically are .mkv .mp4 .png .webm and .m4v

I know that it supports more input formats, don't know to which extend tho,  but things like .mov .bmp .jpg .hvc etc could be added too.

Like i said it's not really an issue just icing on the cake.

Thanks a lot.

**Comment by stax76** [comment]
I changed it to use the same file types as the main dialog.

**Comment by jalba69** [comment]
Hello Stax and thank you,

But juts to be sure this will make it in another version ? I downloaded last 1.4.5.4 an does no seems to be implemented on this one , just asking to be sure.

Thanks

**Comment by stax76** [comment]
It's in the next version.

**Comment by jalba69** [comment]
Thanks for the confirmation.
