### ISSUE TITLE
AVS Script in temporary folder created on each keystroke when setting output filename

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#187]
When setting the filename for the target output file, I had a look at the temporary directory and found that StaxRip created a new AVS script file on each keystroke with the updated filename.

This screenshot says it all:

![image](https://cloud.githubusercontent.com/assets/10564090/26456330/5bc36c18-4132-11e7-859a-b080dddee451.png)

**Comment by stax76** [comment]
Which build are you using?

**Comment by Zcehtro** [comment]
1.4.5.3

**Comment by stax76** [comment]
I cannot reproduce it so it's triggered only by something special, please upload the project file.

**Comment by Zcehtro** [comment]
I don't have the project file anymore but I'll try to recreate it and see if the glitch repeats.

**Comment by Zcehtro** [comment]
Single file:
![image](https://cloud.githubusercontent.com/assets/10564090/26503801/c2d6c76c-4207-11e7-8805-1d627f384f2c.png)

Only demuxing the following:
![image](https://cloud.githubusercontent.com/assets/10564090/26503864/fa301bd2-4207-11e7-80ae-e0139970377c.png)

Added resize and then clip cutting:
![image](https://cloud.githubusercontent.com/assets/10564090/26503988/794a7336-4208-11e7-9793-adf7e3e4631b.png)

After that I got a msg that said that subtitle cutting wasn't supported so I disabled them:
![image](https://cloud.githubusercontent.com/assets/10564090/26504528/8a75796a-420a-11e7-807b-dbaba171e684.png)

Lastly I added the following code to the script:
![image](https://cloud.githubusercontent.com/assets/10564090/26504655/179a839e-420b-11e7-9821-61fcfc5ade27.png)

I just checked it out after this whole explanation and I couldn't recreate it... Perhaps I did something else that I didn't do now.
