### ISSUE TITLE
Under certain conditions StaxRip  does no check anymore to see if output already exist .

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#189]
Hi Stax,

The program seems to have a problem to recognize if a output file already exists under certain conditions , usually if the output path+name+extension already exists the program let us know about it with the output box painted in yellow  + text notification at the bottom..

But if for example you follow those steps : 

- Load a source, set audio and video to mux only, select container MKV for the output
- Start project, new output file is created.
- Now the output box turns yellow as there is an output file with the same name.
- Only change the output file name and start the muxing again, a new file with new name is created.
- Once done there will be no more indications that the output name is already existing.
- From here if you don't change the name of the output file, the previously created one will be erased and replaced for all the next modifications done on the project.

Apparently for some reasons the program does not check anymore to see if the output exists already or not once you done those steps.

This isn't a big deal when you encode a same project once or twice only, but when you start to trim/cut  some parts of a single video to get multiples short videos as output...  if you don't pay close attention and modify the output file name each time there will be no notification that the output path+name+extension selected already exists and there will be a rewrite of the file already existing.

This is under 1.5.0.0 stable version.

Thanks a lot for the nice work.

**Comment by stax76** [comment]
Hi,

it was always like this (from the string the assistant shows a hash value is calculated), I changed it to show also the target path in the assistant so the hash value will be different for every path.

**Comment by jalba69** [comment]
Thanks Stax,

Never noticed it until today while cutting/trimming some videos many times for multiples small outputs.

Thanks a lot for the hash change.

**Comment by jalba69** [comment]
Seems to work fine under 1.5.0.1

Thanks a lot for this change Stax.
