### ISSUE TITLE
Set "Donate" link to system native language or default to English

### ISSUE THREAD

**Issue by burnchar** [stax76/staxrip#19]
The "Donate" page shows a German PayPal link. I don't speak German :)
![capture](https://cloud.githubusercontent.com/assets/681802/11704673/029e48f8-9ea7-11e5-88ea-92ce987f148f.PNG)

![capture](https://cloud.githubusercontent.com/assets/681802/11704693/285cf404-9ea7-11e5-98c8-246e29150c27.PNG)

**Comment by stax76** [comment]
next build will use this link:

https://www.paypal.com/cgi-bin/webscr?cmd=_donations&business=L7R6AKUHJQLM6&lc=GB&no_note=1&cn=Message%3a&no_shipping=1&currency_code=EUR&bn=PP%2dDonationsBF%3abtn_donateCC_LG%2egif%3aNonHosted
