### ISSUE TITLE
Slider or another way to control processor speed

### ISSUE THREAD

**Issue by Gabarito007** [stax76/staxrip#191]
I'm facing some problems related to high temperatures of CPU when processing long videos.
When I use Virtualdub, rendering window has a slider to control "Speed limit" and, using that, I can keep my CPU core 0 under 95ºC.
I move slider to center or one step less, like this:

![hot temp 3](https://cloud.githubusercontent.com/assets/14959189/26704860/67d9b17a-4708-11e7-82cb-640b563d4e09.png)

But when I'm processing videos with Staxrip, I get this:

![hot temp 1](https://cloud.githubusercontent.com/assets/14959189/26704874/8f28180c-4708-11e7-9e60-142693647646.png)

I already try to reduce priority of x265.exe process...

![hot temp 2](https://cloud.githubusercontent.com/assets/14959189/26704887/a60704de-4708-11e7-8c9f-d27fba6268cb.png)
leaving it as lower as possible.

But it won't work.

So, is it possible to take some control over processing speed or some way to avoid high CPU temperatures?

**Comment by stax76** [comment]
I don't know what is possible, codec developers can probably answer this best.
