### ISSUE TITLE
New Demuxer : allow the extraction of video track(s) too please.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#192]
Hello Stax,

Will it be possible to have on the new demuxer tool an option to also extract the video track(s) please ? 

For Mkv and mp4/mov at least, for now with the demuxer present in 1.5.0.1 it is possible to extract all but the the video track(s). ( This said i have a doubt for chapters still possible to be extracted on MKV files like before, will try to gather one mkv file with chapters and test this tomorrow probably ) 

Thanks a lot

**Comment by stax76** [comment]
Hello Yanak,

mkv chapter extraction work here. Next build has support for video demuxing for all 4 demuxers. Do you know how to extract chapters with mp4box?

**Comment by jalba69** [comment]
Hello Stax, 

Thanks a lot, that's really great news.
For MP4box chapters there is 2 options : 

  **-dump-chap**                 Extracts chapter file
  **-dump-chap-ogg**       Extracts chapter file as OGG format

I don't have MP4's with chapters to test this but that's the commands for dumping chapters.

For MKV that's strange it works for you,  on the old GUI demuxer i had the possibility to extract it, on the new one nothing, same input file  : 

![pic](https://img15.hostingpics.net/pics/76854920170604123348.png)

Note that it was not automatically recognized on the old GUI, i have to manually tick the attachment box to get it extracted.

I can't share my file as it's way too big and will take one full day to upload it with my crappy internet speed sadly.

If i use my file as source directly i get the xml file  extracted if the option is set in " Options > Misc > Extract timecodes from VFR MKV files " 

Thank you very much.

**Comment by stax76** [comment]
please test if things actually work.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by jalba69** [comment]
Hi, 
just tried quickly the 1.5.0.3 version,

seems to work for demuxing MKV's using MKVextract, shows video and chapters in the GUI, extraction is done correctly for all content of the mkv, there is 2 files for chapters, one xml and the other in txt form, which is perfect.

But there seems to be a problem with some MP4's, after adding the input file if i click on mp4box for the demux tool selection it does nothing, demux window vanish and i never see the GUI window for demuxing choices, same when trying ffmpeg with some of those MP4's.

Also if a MP4 have more than one video track it demux only the first one, not sure if having MP4's with multiples video tracks is something common so it ain't big deal i think.

Will try a bit more and also try to gather some mp4 files having issues and upload them later at night so you can try by yourself and maybe find out what is the problem, i had no logs created on those files.

Thanks a lot, already fantastic to see it like it is now with all demuxing options.

**Comment by stax76** [comment]
Thanks for testing. It don't show the window if there is no audio and also no subtitles, I've changed it to always show the GUI when it's used as separate tool.

Regarding two video streams I don't want to waste time to implement that for every demuxing tool.

**Comment by jalba69** [comment]
That's it, the Mp4's having issues had no audio tracks, just one or 2 video tracks (and a cover probably for some of them.), you spare me the need to collect and upload stuff ^

And yes don't bother, multiple video tracks in a single file is something uncommon enough that it can be skipped easily.

Thanks a lot for all the efforts you put in making this fantastic tool even better Stax.
