### ISSUE TITLE
Custom menu with"DynamicMenuItem & TemplateProjects" doesn't work

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#193]
Hi Stax,

As i switch often of templates I tried to create a menu with templates selection for more easy and faster access like this : 

![pic](https://img15.hostingpics.net/pics/85056820170603191130.png)

But this does nothing when i click on it, other DynamicMenuItem's ID's seems to work, if i replace TemplateProjects by MuxerProfiles for example it works.

If i simply copy the already existing Templates submenu it does not work, 
if i move the already existing Templates menu it does work for the existing one, but a new created one will not work o_O.

Thanks a lot Stax.

**Comment by stax76** [comment]
The implementation supports every ID only once, that's good for me.

**Comment by jalba69** [comment]
Hi,

I see now, all becomes clear, i will juts move the templates menu to get it displayed where i want for quicker access then.

Thanks for the help Stax, as always you were perfect :)
