### ISSUE TITLE
Muxing using MP4Box 0.7.2-DEV-rev37 x64 failed with exit code: -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by lucandrea** [stax76/staxrip#194]
[Savages T00-1_staxrip - Copy.txt](https://github.com/stax76/staxrip/files/1049773/Savages.T00-1_staxrip.-.Copy.txt)

**Comment by stax76** [comment]
Hi, please try a test build, it has a newer MP4Box build.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by Matthies** [comment]
I can confirm the bug in mp4box coming with 1.5 release. And even better: I can confirm that it is fixed with mp4box coming with your test version 1.5.0.3
