### ISSUE TITLE
Custom TEMP folder path issues when processing only an audio file.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#195]
Hi Stax,

It is possible to only convert an audio file like seen here : 
http://forum.doom9.org/showthread.php?p=1806164#post1806164

But if on the options setting you select a path for the temp files directory this seems to have issues .

My path for temp files is  H:\TEMP\%source_name%_temp\ 
this path is automatically set in the GUI when i use " edit" menu and select my ramdisk H: drive where i have a TEMP folder, this works great when i use video source files tho.

![pic](https://img15.hostingpics.net/pics/13161320170605155644.png)

But when trying to convert audio only like on the link posted above this seems to create issues, the program stall and you have to terminate it when trying to convert an input audio to AAC for example, with a mp3 you try to convert to flac the encoding runs in a loop apparently.

It might be linked to the creation of the temp folder that is not done correctly or something related to the variable in the name if you set a custom Temp folder path.

If i select for TEMP folder path only the root of the H: drive it seems to works, if i select no custom path for the TEMP files it also works, only when selecting H:\TEMP\ it is messed up.

Thanks in advance.

**Comment by stax76** [comment]
Hi,

In the next build it does following:

If the temp dir does not exist it sets the temp dir to the dir of the audio file.

This temp dir will stick however in case you open a video after.

**Comment by jalba69** [comment]
Hi,

Seems ok presented like this, I'll try it when released.

Thank you
