### ISSUE TITLE
I am getting bigger filesizes with new 1.5.0.0 version

### ISSUE THREAD

**Issue by maupassant2** [stax76/staxrip#196]
Hi,
So yes, I noticed that my encodes with 1.5.0.0 versions are significantly larger than what I was getting with 1.4.0.0 with exact same settings. I use x265. Here are the settings : --crf 21 --preset veryfast --tune psnr --output-depth 10 --rd 4 --tu-intra-depth 3 --rdoq-level 2 --early-skip --b-intra --limit-modes --aq-mode 2 --qg-size 16 --ipratio 1.38 --pbratio 1.28 --me star --max-merge 3 --weightb --bframes 6 --rc-lookahead 50 --ref 6 --
I tested with the same 1.39 GB file (a MKV encoded with AVC). The file re-encoded with Staxrip 1.4.0.0 is 216 MB. But with  1.5.0.0  I get 270 MB. I tried with other files and get the same larger filesizes. And idea ?

**Comment by maupassant2** [comment]
I compared the MediaInfo for the two files. The problem is with the audio.

1.4.0.0
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 41 min 23 s
Bit rate mode               : Variable
Bit rate                    : 79.2 kb/s
Maximum bit rate            : 110 kb/s
Channel(s)                  : 2 channels
Channel positions           : Front: L R
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 spf)
Compression mode            : Lossy
Stream size                 : 23.4 MiB (11%)
Language                    : English
Encoded date                : UTC 2017-06-04 04:37:22
Tagged date                 : UTC 2017-06-04 05:20:07

1.5.0.0
Audio
ID                          : 2
Format                      : AAC
Format/Info                 : Advanced Audio Codec
Format profile              : LC
Codec ID                    : 40
Duration                    : 41 min 23 s
Bit rate mode               : Variable
Bit rate                    : 257 kb/s
Maximum bit rate            : 288 kb/s
Channel(s)                  : 6 channels
Channel positions           : Front: L C R, Side: L R, LFE
Sampling rate               : 48.0 kHz
Frame rate                  : 46.875 FPS (1024 spf)
Compression mode            : Lossy
Stream size                 : 76.2 MiB (29%)
Language                    : English
Encoded date                : UTC 2017-06-07 23:31:36
Tagged date                 : UTC 2017-06-08 00:11:27

**Comment by Gabarito007** [comment]
I think you already solve that.
Your second audio has 6 channels, but the first has just 2 (stereo).
Adjust your profile to match what you want and, maybe file sizes will mathes too.

**Comment by maupassant2** [comment]
Thanks.
