### ISSUE TITLE
Aspect Ratio problem when using NVIDIA H264

### ISSUE THREAD

**Issue by maupassant2** [stax76/staxrip#197]
Hi again,
I just started using NVIDIA H264, and it usually works fine, but with some files, I am not getting the aspect ratio I ask for. Here's one example. If you take the original 4:3 file and use x264, I ask for a 59:44 (1.340) DAR and I get what I asked for. If you use NVIDIA H264, I ask for the same DAR and get instead a 3.605 DAR ! And MediaInfo tells me that the original DAR was 3.606 ! I'm sending you the files if you want to test it.
[Original file.mp4.txt](https://github.com/stax76/staxrip/files/1066097/Original.file.mp4.txt)
[Staxrip file (NVIDIA h264).mp4.txt](https://github.com/stax76/staxrip/files/1066098/Staxrip.file.NVIDIA.h264.mp4.txt)
[Staxrip file (x264).mp4.txt](https://github.com/stax76/staxrip/files/1066096/Staxrip.file.x264.mp4.txt)

https://www.mediafire.com/?54ysjgy6i6yjtws

**Comment by stax76** [comment]
Hi, maybe it's following issue: https://github.com/rigaya/NVEnc/issues/8

**Comment by maupassant2** [comment]
Maybe. But as you said, NVEnc 3.09 gives an error code 1 with no output file that I can play.

**Comment by stax76** [comment]
I was getting playable output files, file extension h264/h265 playable with mpc-be. Until rigaya uploads a new build you have to use whatever nvenc version that works and mux with mkvtoolnix gui where you can set the DAR.

**Comment by maupassant2** [comment]
O.K. Thank you very much for your work and help.

**Comment by maupassant2** [comment]
O.K. I took a look at the h264 file with MediaInfo. Sorry to report that the problem persists. File output has a DAR of 3.606 even though I asked for 1.340.

**Comment by stax76** [comment]
I found an issue and reported it: https://github.com/rigaya/NVEnc/issues/8

Please always post full log files.

**Comment by stax76** [comment]
With the last test build it should work.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by maupassant2** [comment]
Actually, I just tried it with two other files, and the DAR I got was slightly wrong for the first file, very wrong for the second file (here's the log for this one).
[title00 (02)_staxrip.txt](https://github.com/stax76/staxrip/files/1070161/title00.02._staxrip.txt)

**Comment by stax76** [comment]
Yes sorry, even with using --dar instead of --sar for nvenc, MediaInfo still shows different values, I'll upload another build today that works around it by setting the AR with mkvmerge/mp4box.

**Comment by stax76** [comment]
new build: https://forum.doom9.org/showthread.php?p=1809562#post1809562

**Comment by maupassant2** [comment]
So far, so good. Thanks for your great work and support.
