### ISSUE TITLE
No 32Bits version?

### ISSUE THREAD

**Issue by hydropunk69** [stax76/staxrip#2]
Im trying to encode a test with some old filters but just works with the 32bit version.

**Comment by stax76** [comment]
Hello,

x86 is abandoned but the latest x86 release isn't very old:

http://code.fosshub.com/StaxRip/downloads

**Comment by hydropunk69** [comment]
there's a way to make some filters compatible with x64 version?

**Comment by stax76** [comment]
It's technically not possible.
