### ISSUE TITLE
Allow closing of "The format of the source file count not be detected"

### ISSUE THREAD

**Issue by burnchar** [stax76/staxrip#20]
When the following error occurs, the window shown below is completely uncloseable short of force-killing the process, which is harder than you might think because I often have 4 or more Staxrip processes running (and can't tell them apart in Task Manager). The 'X' button is ignored. Escape. ALT-F4...
The window appears after opening what I assume is a bad rip, right after entering "Movie Name". 

![capture](https://cloud.githubusercontent.com/assets/681802/11708709/9a730160-9ece-11e5-85cf-29b1074498e7.PNG)

![capture](https://cloud.githubusercontent.com/assets/681802/11708570/9e3d3dca-9ecd-11e5-8de5-a58608fe0150.PNG)

**Comment by stax76** [comment]
Hello Charles,

thanks for another generous donation and for all the feedback. I found what was locking the window.

cheers
Frank
