### ISSUE TITLE
MP4Box stopped working

### ISSUE THREAD

**Issue by nulledone** [stax76/staxrip#201]
Hello there I recently started using your program. Today I found a bug (i think). With default settings when you try to encode x265 in mp4 container MP4box gets error (0xC0000005) but when I remove tags from container options it works perfectly. As far as I know mp4 does not support tags in x265, that might be the reason it crashes.

**Comment by stax76** [comment]
Hi, maybe it was a mp4box issue that was fixed meanwhile, in the newest staxrip build 1511 it's working: https://pastebin.com/CHQuQK8t

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by nulledone** [comment]
Yes I can confirm that it is fixed. For your info error occured on 1500-stable. Thanks for the fast response keep up the good work.
