### ISSUE TITLE
Script file failed to load

### ISSUE THREAD

**Issue by mwsduelle** [stax76/staxrip#203]
First time using StaxRip; just wanted to compare it to HandBrake and I can't get it to load my test file.

[VTS_01_2_staxrip.log.txt](https://github.com/stax76/staxrip/files/1086951/VTS_01_2_staxrip.log.txt)

**Comment by stax76** [comment]
Hi, please try what the log file states. If you are new to all this you can get help at:

https://forum.videohelp.com/forums/11-Video-Conversion

> You can try to open the script with VirtualDub x64, if it don't open it could be a problem with the script or the AviSynth+ x64 setup, if StaxRip don't report a script error and the script looks valid then reinstalling AviSynth+ x64 might fix the problem, the setup is located at:
> 
> C:\Users\duelle\Desktop\StaxRip-x64-1.5.0.0\Apps\AviSynth+r2455.exe

**Comment by stax76** [comment]
Hi, I would like to close this issue if it's solved.
