### ISSUE TITLE
Wrong aspect ratio

### ISSUE THREAD

**Issue by eur0pa** [stax76/staxrip#204]
Latest unstable build 1.5.1.2, using provided NVEnc for NVIDIA H264 encoding.
The resulting rip is properly sized but has the wrong vertical aspect ratio. Seems a regression from a couple weeks ago:

![test](https://user-images.githubusercontent.com/4948454/27425671-78f71434-5739-11e7-8062-6d9294774e61.jpg)

```
NVEncC (x64) 3.12 (r525) by rigaya, Jun 19 2017 22:01:12 (VC 1900/Win/avx2)
NVENC API      v8.0
OS Version     Windows 10 x64 (15063)
CPU            Intel Core i5-2500K @ 3.30GHz [TB: 3.49GHz] (4C/4T)
GPU            #0: GeForce GTX 1060 6GB (10 EU) @ 1708 MHz (382.53)
Input Buffers  CUDA, 32 frames
Input Info     avcuvid: H.264/AVC, 1920x1080, 24000/1001 fps
Vpp Filters    crop: 0,140,0,140
Output Info    H.264/AVC high @ Level 4.1
1920x800p 1:1 23.976fps (24000/1001fps)
Encoder Preset quality
Rate Control   CQP  I:20  P:23  B:25
Lookahead      on, 32 frames, Adaptive I, B Insert
GOP length     240 frames
B frames       3 frames
Ref frames     4 frames, LTR: off
AQ             on(spatial, strength auto)
Others         mv:auto cabac deblock adapt-transform:auto bdirect:auto
encoded 199749 frames, 414.67 fps, 3120.77 kbps, 3099.41 MB
encode time 0:08:01, CPULoad: 10.11
frame type IDR   1017
frame type I     1017,  total size   118.24 MB
frame type P    55594,  total size  1581.25 MB
frame type B   143138,  total size  1399.92 MB

Video
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High@L4.1
Format settings, CABAC    : Yes
Format settings, ReFrames : 4 frames
Width                     : 1 920 pixels
Height                    : 800 pixels
Display aspect ratio      : 2.40:1
Frame rate                : 23.976 (24000/1001) FPS
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
```

**Comment by stax76** [comment]
Hi, please post the full log file.

**Comment by eur0pa** [comment]
Full log file attached as requested: [test.txt](https://github.com/stax76/staxrip/files/1094408/test.txt)

**Comment by stax76** [comment]
The log file looks OK, I've made a encode with your settings and see the problem, did this work before? If so which version? Here are old versions:

https://onedrive.live.com/?id=6BDD4375AC8933C6%212310&cid=6BDD4375AC8933C6

**Comment by stax76** [comment]
As workaround you can use avisynth/vapoursynth cropping, there are three hardware decoders possible, DGDecNV (great tool), DGDecIM and DSS2 + LAV Filters DXVA Copy Back, software decoding should also be fine.

**Comment by eur0pa** [comment]
If I'm not mistaken, the bug was fixed in 1.5.0.9 and regressed in 1.5.1.1 (NVEncC 3.11).

Decoding and cropping via Avisynth as a workaround fixes the issue.

**Comment by stax76** [comment]
https://github.com/rigaya/NVEnc/issues/10

**Comment by stax76** [comment]
It should work in the newest test build.
