### ISSUE TITLE
24 bit DTS audio encoding

### ISSUE THREAD

**Issue by JohnnyWestlake** [stax76/staxrip#205]
Hey, question or feature request : I'm encoding DTS audio and I'd like to be encoding at 24bit and not 16bit, but there's not an option to change it. Is this something easy to add? (or is it already there and I'm blind).

(For the record, the source is usually 24 Bit Dolby TrueHD or some other 24 bit audio source)

**Comment by stax76** [comment]
Hi, I'll investigate it.

**Comment by stax76** [comment]
I don't know if there is something that can be improved, staxrip would allow to add custom command line switches, I'm not an expert on DTS encoding, best place to ask about this topic is doom9 and hydrogenaud, please let me know if you find out more.
