### ISSUE TITLE
VS2013 runtime version

### ISSUE THREAD

**Issue by JustDobby** [stax76/staxrip#207]
Hi, just a minor thing:

On every new StaxRip version from you you're finding the VS2013 runtime msvcp120.dll not current, and offer a link to "your" version (which will happily perform a repair install), but on a new StaxRip it starts all over again.

It would seem that you're expecting an october 4th 2013 timestamp, whereas the link you supply yields a february 10 2016 timestamp (version 12.0.40649.5) on my system anyway.

Not really an issue but it keeps drawing my attention...

**Comment by stax76** [comment]
The topic is tricky, I found some info here:

https://blogs.technet.microsoft.com/askcore/2008/09/17/what-is-the-winsxs-directory-in-windows-2008-and-windows-vista-and-why-is-it-so-large/

Next build has version detection disabled for all three VC++ runtimes.
