### ISSUE TITLE
Batch settings for batch processing

### ISSUE THREAD

**Issue by Draghmar** [stax76/staxrip#208]
Hi
Currently when I have many files to encode I add them through the batch files, demux and then one by one I apply settings I want.
Is there a way to apply those settings to all files in a job list? I want them all to be the same. Maybe I'm missing some settings in UI...but I looked for it. :P

**Comment by stax76** [comment]
For normal batch processing first you customize your empty project and then you add your source files in batch mode.

**Comment by Draghmar** [comment]
Hm...Maybe I'm doing something wrong but it didn't work for me. At least not 100%. What I did:
1. Open app.
2. Set encode profile to custom one I've created based on NVIDIA H.265.
3. Set target bit rate to 8500.
4. Set audio to Just Mux.
5. Select source->File batch.
6. Add files and demux them (not sure if that's needed).
7. Create jobs.
8. Click Start in Jobs window.
After that I ended up with file that had 80Mb bit rate. Like it just set it to whatever is the max.

**Comment by stax76** [comment]
If you check the demux checkbox then it's only batch demuxing and indexing and not encoding.

If you want a fixed bitrate then you either have to define this in the options or use the newest test build which handles fixed bitrate differently, see the log file of the test build for more info.

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by Draghmar** [comment]
That was step 6, which leads to 7 and 8 and the latest do start encoding.

I don't see much difference in this new build in terms of options. I was using 1.4.4.7 before. 

The thing is my custom profile, which is based on default NVIDIA H.265, is set to VBR HQ. I know what it stands for but when I choose it I have two fields available: Size and Video Bitrate. When go through each file on the Jobs list one by one and set Video Bitrate to 8500 then everything works as I want. But I think by default Size field takes precedence and it tries to encode file so it has whatever is in this field - in case of empty project it has 5472 for 8500 bitrate. I'm assuming that because when file is loaded into project it always tries to set default file size and set bitrate to match that. And changing bitrate manually changes value in the field size.
Check attachment to get the idea.
![staxrip](https://user-images.githubusercontent.com/275348/27653321-08b3e6c4-5c3f-11e7-9250-b25ebdad8452.png)

**Comment by stax76** [comment]
> I'm assuming that because when file is loaded into project it always tries to set default file size and set bitrate to match that. And changing bitrate manually changes value in the field size.

The latest build should not behave like this, I just verified. It remembers which text box was last edited last, bitrate or size.

**Comment by Draghmar** [comment]
I've downloaded latest version (1.5.1.6) you have there to be sure and...It works! :) Thanks for you help!
