### ISSUE TITLE
Error Muxing using MP4Box 0.7.2-DEV-rev37 x64

### ISSUE THREAD

**Issue by YinnVI** [stax76/staxrip#209]
Error Muxing using MP4Box 0.7.2-DEV-rev37 x64

Muxing using MP4Box 0.7.2-DEV-rev37 x64 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.

[32mHEVC import - frame size 1920 x 1080 at 59.940 FPS
[32mHEVC Import results: 7433 samples (7436 NALUs) - Slices: 13 I 7420 P 0 B - 0 SEI - 13 IDR
[0m[32mIsoMedia import kanna_4 ID2.m4a - track ID 2 - Audio (SR 44100 - 2 channels)

StaxRip.ErrorAbortException: Muxing using MP4Box 0.7.2-DEV-rev37 x64 failed with exit code: -1073741819 (0xC0000005)

The exit code might be a system error code: The instruction at 0xp referenced memory at 0xp. The memory could not be s.

[32mHEVC import - frame size 1920 x 1080 at 59.940 FPS
[32mHEVC Import results: 7433 samples (7436 NALUs) - Slices: 13 I 7420 P 0 B - 0 SEI - 13 IDR
[0m[32mIsoMedia import kanna_4 ID2.m4a - track ID 2 - Audio (SR 44100 - 2 channels)

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 221
   at StaxRip.MP4Muxer.Mux() in D:\Projekte\VS\VB\StaxRip\General\Muxer.vb:line 293
   at StaxRip.MainForm.Encode() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2192
   at StaxRip.GlobalClass.RunJobRecursive() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 36

**Comment by stax76** [comment]
Hi,  it's probably already solved, please try the newest test build.

https://github.com/stax76/staxrip#support
