### ISSUE TITLE
Staxrip treating PAL (50fps) content as laced and dropping frames.

### ISSUE THREAD

**Issue by Mad-Matty** [stax76/staxrip#21]
One issue that has been introduced since Staxrip has see new development on Github is that when importing an avs which links to pal content, it will treat is as laced and half the fps.  This causes audio desync in the final encode.  This does not happen when importing 60 fps content.  The content is this case is taken from 50mhz game systems usually double res and not laced. 

What is happening is that "SelectEven().AssumeFPS(25)" is being auto applied to the imported avs.  I have gotten used to just clicking edit on the imported avs and deleting it, but I do occasionally forget to and have to re-encode the final video.

The correct and wanted behaviour is that Stax should never add anything to the imported avs.  If the script is wrong  then it is the users fault

**Comment by stax76** [comment]
Hello, thanks for reporting, I changed it to not change the script in case the source is avs or vpy, while testing this I found and fixed two other issues.
