### ISSUE TITLE
Feature request: overwrite option on macros in batch templates

### ISSUE THREAD

**Issue by JustDobby** [stax76/staxrip#210]
Hi,

FRQ: the possibility to override eg. in the mkv container configuration of a batch template the title field...

In my template there's let's say a %target_name% in the title field, but when I batch select a folder full of mkv files any existing title fields are kept instead of taking the field from the template..

**Comment by pahein2** [comment]
Yes please, this is has been becoming issue for me for years.

**Comment by stax76** [comment]
Hi, I'll investigate it but it'll take time since I'm doing a major rewrite at the moment.

**Comment by JustDobby** [comment]
Don’t rush it on my behalf – in this specific case a simple “mkvpropedit –e info –d title” would do the trick.. it would be just for that all-in-one feeling *grin*

 

Thank you for a great program!

**Comment by stax76** [comment]
Hi, it should work in the last test build.

https://forum.doom9.org/showthread.php?p=1810725#post1810725
