### ISSUE TITLE
Error Muxing MP4Box (2 input names)

### ISSUE THREAD

**Issue by Lentzeris** [stax76/staxrip#212]
When the encode is done and it tries to mux into an mp4 file, I am getting the error (with every video file, I am just posting an example):

> Error Muxing using MP4Box 0.7.2-DEV-rev79 x64
> 
> Muxing using MP4Box 0.7.2-DEV-rev79 x64 failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>           Muxing using MP4Box 0.7.2-DEV-rev79 x64
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> 
> "E:\My Documents\Downloaded Programs\Video (Play-Convert)\StaxRip\Apps\MP4Box\MP4Box.exe" -add C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_temp\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_out.h264#video -add "C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_temp\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS ID2 English_out1.m4a#audio:lang=eng:name=" -chap C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_temp\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_chapters.txt -itags encoder="StaxRip 1.5.1.6" -itags Writing frontend: StaxRip 1.5.1.6 -new C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS.mp4
> 
> Error - 2 input names specified, please check usage
> 
> 
> 
> StaxRip.ErrorAbortException: Muxing using MP4Box 0.7.2-DEV-rev79 x64 failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>           Muxing using MP4Box 0.7.2-DEV-rev79 x64
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> 
> "E:\My Documents\Downloaded Programs\Video (Play-Convert)\StaxRip\Apps\MP4Box\MP4Box.exe" -add C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_temp\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_out.h264#video -add "C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_temp\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS ID2 English_out1.m4a#audio:lang=eng:name=" -chap C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_temp\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS_chapters.txt -itags encoder="StaxRip 1.5.1.6" -itags Writing frontend: StaxRip 1.5.1.6 -new C:\MOVIES\The.Lost.City.of.Z.2016.1080p.BluRay.x264-GECKOS.mp4
> 
> Error - 2 input names specified, please check usage
> 
> 
>    at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 261
>    at StaxRip.MP4Muxer.Mux() in D:\Projekte\VS\VB\StaxRip\General\Muxer.vb:line 299
>    at StaxRip.MainForm.ProcessJob() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2548
>    at StaxRip.GlobalClass.RunJobs() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 37

I have been facing this problem with the last 3-4 unstable builds. It was not happening before.

**Comment by stax76** [comment]
Hi, the problem might be:

-itags encoder="StaxRip 1.5.1.6" -itags Writing frontend: StaxRip 1.5.1.6

Please post the full log file and screenshots of the main dialog and: Container Options > Options

**Comment by Lentzeris** [comment]
When I cleared the "tags" from "Container Options" and encoded a short sample video, it finished without errors. As soon as I encode a whole new movie, I will post the full log file, so that you can figure out what the problem with the tags is. Thanks for now...

**Comment by Lentzeris** [comment]
After I run a totally new encode, there were no errors reported, since I had already removed the tags from the template. So, it is now certain that the error happened because of the tags in container options.

**Comment by stax76** [comment]
For the next build I improved the help for mp4box tags, there are two ways to show the help:

1: click ? in the title bar
2: right click the label

You will see:

> **Tags**
> Tags added to the MP4 file.
> 
> Syntax: prop1=val1:prop2=val2
> 
> Supported iTunes tag modifiers:
> album_artist usage: album_artist=album artist
> album usage: album=name
> tracknum usage: track=x/N
> track usage: track=name
> artist usage: artist=name
> comment usage: comment=any comment
> compilation usage: compilation=yes,no
> composer usage: composer=name
> created usage: created=time
> disk usage: disk=x/N
> tool usage: tool=name
> genre usage: genre=name
> name usage: name=name
> tempo usage: tempo=integer
> writer usage: writer=name
> group usage: group=name
> cover usage: cover=file.jpg,file.png
> encoder usage: encoder=name
> gapless usage: gapless=yes,no
> all usage: all=NULL

This help is due to runtime generation always in sync with mp4box

```
            Task.Run(Sub()
                         Dim stdOut = ProcessHelp.GetErrOut(Package.MP4Box.Path, "-tag-list")
                         BeginInvoke(Sub() tags.Help = "Tags added to the MP4 file." + BR2 + "Syntax: prop1=val1:prop2=val2" + BR2 + stdOut)
                     End Sub)
```

I search my code and there is only one place with -itags so you must have entered it yourself, at the bottom of the container options dialog there is a command line preview when you are in doubt.
