### ISSUE TITLE
Log windows popup

### ISSUE THREAD

**Issue by steuerlexi** [stax76/staxrip#213]
Please add an option do prevent the LOG window to pop up when encoding a file. This is annoying when you do batch processing of many files.

Thank you

**Comment by stax76** [comment]
Some things are already implemented but because of the code in this area was changed recently there night be issues. I need to know which build you were using and under which circumstances did it pop up.

Was the window normal or maximized or was it minimized and if it was minimized was in the taskbar or in the tray?

**Comment by steuerlexi** [comment]
I am using the latest release. I mean the LOG screen which shows you how far the encoding has come. Every new file let it pop up in batch processing of many files

**Comment by stax76** [comment]
Should be fixed in the next built, thanks for the report.

**Comment by steuerlexi** [comment]
Awesome. thank you

**Comment by steuerlexi** [comment]
I found out that when you minimize the LOG screen. Then it works. Sorry

**Comment by stax76** [comment]
Yes but not 100% reliably, even then it shortly pops up the first time after you minimize it.

**Comment by steuerlexi** [comment]
ok, yes that is true. Would be great if there was button on the Log screen, where you can choose., or something like that.

**Comment by stax76** [comment]
You mean to choose where to minimize, tray or taskbar?

**Comment by stax76** [comment]
Build is online now.

https://forum.videohelp.com/threads/369913-StaxRip-Encoder-GUI/page6#post2490759

**Comment by steuerlexi** [comment]
Awesome. I will test today

**Comment by stax76** [comment]
Please note that I'll be uploading a new built in a few minutes.

**Comment by steuerlexi** [comment]
Ok, then I will wait
