### ISSUE TITLE
GUI Breaks when moving between screens of different DPI

### ISSUE THREAD

**Issue by JohnnyWestlake** [stax76/staxrip#215]
I have a multimonitor setup with two different DPI screens on Windows 10 Creators Update. When dragging any StaxRip window between screens of different DPI, the GUI breaks and starts position or sizing incorrectly.

Currently using 1.5.1.4

![1](https://user-images.githubusercontent.com/2319473/27860706-97b2862e-6175-11e7-8e0f-153aac52afbc.jpg)
![2](https://user-images.githubusercontent.com/2319473/27860707-97c29500-6175-11e7-821a-b35ccc2df05f.jpg)
![3](https://user-images.githubusercontent.com/2319473/27860708-97cb3106-6175-11e7-9778-a47ece46bff0.jpg)
![4](https://user-images.githubusercontent.com/2319473/27860710-97cc19b8-6175-11e7-9954-6f26935e8fc2.jpg)
![5](https://user-images.githubusercontent.com/2319473/27860711-97cd2ac4-6175-11e7-81c9-fce74b62c3c7.jpg)
![6](https://user-images.githubusercontent.com/2319473/27860712-97cf004c-6175-11e7-9387-191bf1c593c0.jpg)
![7](https://user-images.githubusercontent.com/2319473/27860709-97cc25e8-6175-11e7-8de5-84ef658f4167.jpg)

**Comment by stax76** [comment]
From my current code base dynamic DPI changing is probably very difficult to implement. I could change it that one monitor uses virtual scaling, it's the thing that gives the awful blurry look, only one monitor would use that.

**Comment by stax76** [comment]
In the next build I changed it using virtual scaling on one monitor, full support is currently not in sight. I hope it's OK, thanks for reporting.

**Comment by stax76** [comment]
Build is online now.

https://forum.videohelp.com/threads/369913-StaxRip-Encoder-GUI/page6#post2490759
