### ISSUE TITLE
Video BlackBar

### ISSUE THREAD

**Issue by D-Prince** [stax76/staxrip#217]
how can i remove black bar from video? 
like this one , 
<img src="http://keepimg.com/images/x.jpg" alt="x.jpg" border="0" />

i want to remove those black bar from one of my video.

**Comment by stax76** [comment]
In the toolbar click Crop to open the crop dialog and in the crop dialog right-click to show the context menu and select auto crop in the menu. This will add a crop filter to the avisynth/vapoursynth script.
