### ISSUE TITLE
Can't add another preferred language to audio?

### ISSUE THREAD

**Issue by Magneticdud** [stax76/staxrip#218]
![Screenshot](https://user-images.githubusercontent.com/2940598/28012005-b148f788-6564-11e7-9ba9-c3fdd3a6857a.png)
I want to add another language to the audio dialog, so it gets automatically checked when i import some video.

I want to add japanese, I wrote ita,eng,und,jpn (also tried jap), but when I close staxrip, it gets back to ita,eng,und

**Comment by stax76** [comment]
It's by design, it works by using: Project > Save As Template

**Comment by Magneticdud** [comment]
ah, yes, i missed that. It works
