### ISSUE TITLE
When adding the QTGMC filter, please load the TDeint plugin as well.

### ISSUE THREAD

**Issue by overclockwise** [stax76/staxrip#220]
When adding the QTGMC filter, please load the TDeint plugin as well. See: http://avisynth.nl/index.php/QTGMC - "Optional Plugins and Scripts"

QTGMC has a SourceMatch setting that requires AviSynth to load TDeint. This option _greatly_ increases encode quality on high quality interlaced sources. This errors out in StaxRip since TDeint isn't loaded along with QTGMC.

**Comment by stax76** [comment]
Thanks for the report, until I upload the next build you can use a comment as workaround to make staxrip load it.

# TDeint(

**Comment by stax76** [comment]
I missed it in the build from today but it's locally changed now so it will definitively be in the next build.

**Comment by overclockwise** [comment]
Thanks! I greatly appreciate it.
