### ISSUE TITLE
System.ArgumentNullException

### ISSUE THREAD

**Issue by Grief** [stax76/staxrip#224]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                        Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.5.0.0
Windows    : Windows 10 Pro 1703
Language   : Russian (Russia)
CPU        : Intel(R) Core(TM) i5-4690K CPU @ 3.50GHz
GPU        : NVIDIA GeForce GTX 1080
Resolution : 1920 x 1080
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                         Exception
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

System.ArgumentNullException: Значение не может быть неопределенным.
Имя параметра: fileName
   в System.IO.FileInfo..ctor(String fileName)
   в StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) в D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:строка 1607

**Comment by stax76** [comment]
Hi, please try the newest build:

https://github.com/stax76/staxrip/blob/master/md/test-build.md
