### ISSUE TITLE
Delete temp files causes issues

### ISSUE THREAD

**Issue by justheguy** [stax76/staxrip#225]
When set to auto delete temp files i get these errors when the job finishes, output is not affected 
https://i.imgur.com/9OvMl68.png
https://i.imgur.com/CMs2Xnl.png
https://i.imgur.com/62LoQw7.png

**Comment by stax76** [comment]
I hope it works:

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by justheguy** [comment]
Issue fixed with latest. Thanks

**Comment by stax76** [comment]
Thanks for the report then.
