### ISSUE TITLE
Wrong qaac kbps calculate

### ISSUE THREAD

**Issue by mouset447** [stax76/staxrip#226]
qaac --tvbr 50 staxrip says 318 kbps, but qaac tvbr with 50 have 100 kbps!

the kbps is wrong calculate!

Qaac (Quicktime) 5.1-48KHz | 2.0-48KHz
------ -------------- --------- | ---------
-V 1 AAC-LC 119 Kb/s | 46 Kb/s
-V 9 AAC-LC 136 Kb/s | 53 Kb/s
-V 18 AAC-LC 158 Kb/s | 61 Kb/s
-V 27 AAC-LC 177 Kb/s | 69 Kb/s
-V 36 AAC-LC 198 Kb/s | 74 Kb/s
-V 45 AAC-LC 240 Kb/s | 95 Kb/s
-V 54 AAC-LC 277 Kb/s | 108 Kb/s
-V 64 AAC-LC 314 Kb/s | 120 Kb/s
-V 73 AAC-LC 351 Kb/s | 134 Kb/s
-V 82 AAC-LC 385 Kb/s | 147 Kb/s
-V 91 AAC-LC 450 Kb/s | 173 Kb/s
-V 100 AAC-LC 507 Kb/s | 195 Kb/s
-V 109 AAC-LC 581 Kb/s | 224 Kb/s
-V 118 AAC-LC 638 Kb/s | 247 Kb/s
-V 125 AAC-LC 704 Kb/s | 276 Kb/s

**Comment by stax76** [comment]
Looks OK to me, the calculation and output depends on the channel count, did you look at the created bitrate in the output file using the built in MediaInfo GUI (right-click the output file and select MediaInfo).

Qaac (Quicktime) **5.1-48KHz** | 2.0-48KHz
------ -------------- --------- | ---------
-V 1 AAC-LC 119 Kb/s | 46 Kb/s
-V 9 AAC-LC 136 Kb/s | 53 Kb/s
-V 18 AAC-LC 158 Kb/s | 61 Kb/s
-V 27 AAC-LC 177 Kb/s | 69 Kb/s
-V 36 AAC-LC 198 Kb/s | 74 Kb/s
-V 45 AAC-LC 240 Kb/s | 95 Kb/s
-V 54 AAC-LC **277 Kb/s** | 108 Kb/s
-V 64 AAC-LC 314 Kb/s | 120 Kb/s
-V 73 AAC-LC 351 Kb/s | 134 Kb/s
-V 82 AAC-LC 385 Kb/s | 147 Kb/s
-V 91 AAC-LC 450 Kb/s | 173 Kb/s
-V 100 AAC-LC 507 Kb/s | 195 Kb/s
-V 109 AAC-LC 581 Kb/s | 224 Kb/s
-V 118 AAC-LC 638 Kb/s | 247 Kb/s
-V 125 AAC-LC 704 Kb/s | 276 Kb/s

**Comment by mouset447** [comment]
Ah ok. qaac is 5.1, is 2.0 on it works! Tanks!
