### ISSUE TITLE
Exeption on default convert script

### ISSUE THREAD

**Issue by kliffgomel** [stax76/staxrip#228]
StaxRip x64 1.5.3.1
Default script "Convert Bluray Video (BT709) to 10bit 400nits (MaxFALL) High Dynamic Range Video" does not work properly. The script does not correctly detect the loaded x265 project and does not start. If in the text of the script in a check condition the name of the encoder is replaced with "x265Encoder" by "x265Enc", then the script is launched, but an exception is occurs.

NullReferenceException

System.NullReferenceException: 
   в StaxRip.x265Params.OnValueChanged(CommandLineParam item) в D:\Projekte\VS\VB\StaxRip\Encoding\x265Enc.vb:строка 918
   в StaxRip.CommandLine.CommandLineParams.RaiseValueChanged(CommandLineParam item) в D:\Projekte\VS\VB\StaxRip\General\CommandLine.vb:строка 45
   в StaxRip.BasicVideoEncoder.ImportCommandLine(String commandLine, CommandLineParams params) в D:\Projekte\VS\VB\StaxRip\Encoding\VideoEncoder.vb:строка 388

**Comment by stax76** [comment]
I've renamed all encoders while I was working on the new x264 GUI.

The exception stems from code added for a new feature added recently:

> new: at the bottom of the video encoder option dialogs there is a menu item to import a command line from the clipboard

A fixed build is online:

https://github.com/stax76/staxrip/blob/master/md/changelog.md
