### ISSUE TITLE
Just cutting a movie

### ISSUE THREAD

**Issue by JoergWausW** [stax76/staxrip#235]
I just tried to cut out a part of an existing video:

I selected Audio->Just mux and Video->Just mux, Container->mp4 (as the original video)
In the preview I selected 5 minutes out of 22 (not from the beginning).

After running, the output included the whole 22 minutes. Is this a mp4-issue?

Using mkv as container worked better - the cut video starts at the first keyframe after the selection start (I think the key frame before the selection start would be better to have the selected area completely in the cut video)

Even better: Is there a way to only re-encode from the frame at the selection start to the next keyframe, and the rest just being merged? (Same at the end in case of referenced frames later)

Or can the container hold the information to not show the excluded frames? (probably not supported by players).

**Comment by stax76** [comment]
mkvmerge has cut/trim features that to my knowledge mp4box don't has.

> Even better: Is there a way to only re-encode from the frame at the selection start to the next keyframe, and the rest just being merged? (Same at the end in case of referenced frames later)

I don't know if there is freeware that can do this, I know one commercial app:

http://www.solveigmm.com/en/products/video-splitter/#

**Comment by stax76** [comment]
AviDemux might support mp4 cut/trim.

**Comment by JoergWausW** [comment]
I thought the cutting is done by avisynth. At least the trim command is included in the avisynth-script:
>-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>                      AviSynth Script
>-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>
>LoadPlugin("C:\Programme Portable\StaxRip\Apps\Plugins\avs\MPEG2DecPlus\MPEG2DecPlus64.dll")
>MPEG2Source("E:\Test\801\VIDEO_TS\VTS_01_1_temp\VTS_01_1.d2v")
>Trim(13016, 13523)

Shouldn't any demuxer continue from here with a trimmed output?

**Comment by stax76** [comment]
It's not possible to use avisynth or vapoursynth without decoding, if you output mkv it's mkvmerge that cut/trims. There is currently an active thread about this topic at doom9 btw.

**Comment by JoergWausW** [comment]
So this AviSynth Script quoted above is actually not necessary for the output.

Before I signed in here today I registered at doom9 yesterday, but I felt not very welcome there, when you have to wait 5 days before you can do anything... :-(
Can you be more specific about this active thread, please? I failed to nail it down.

**Comment by stax76** [comment]
Most tool authors of the tools used by staxrip have a support thread at doom9, staxrip too.

https://forum.doom9.org/showthread.php?t=174644
