### ISSUE TITLE
No audio in output (.m4v)

### ISSUE THREAD

**Issue by nulledone** [stax76/staxrip#236]
Might be a source related issue but it seems like audios in all(*) .m4v files are not recognized. And encoded output has no audio.

*The m4v files I have tested were encoded with HandBrake 1.0.1 before. You may want to check the attached sample.

Sample: [test.zip](https://github.com/stax76/staxrip/files/1167572/test.zip)

I copy pasted this from an older comment that you probably didn't notice.

**Comment by stax76** [comment]
StaxRip defines:

m4a: audio only
m4v: video only
mp4: audio+video

it's a corner case like ogg and ogm, it was reported before, I don't know which tools output m4v for audio video nowadays.

**Comment by stax76** [comment]
I've asked at doom9, next build will recognize audio.
