### ISSUE TITLE
Jobs window cropped when screen size < 1280x720

### ISSUE THREAD

**Issue by samkatakouzinos** [stax76/staxrip#237]
Jobs window cropped when screen size < 1280x720

Below 1280x720 the left side of the Jobs window is cropped. 
This affects the use of the Start button and viewing of the Jobs list. 
Tabbing to Start button the correct number of times still works so I assume a cropping issue.

1. Jobs window when screen size >= 1280x720;
   ![>= 1280x720](https://lh3.googleusercontent.com/-wyU9Inqyn50/WXczGvUkdRI/AAAAAAACDTQ/4L41ypQ9SZ4ay4JDBV32PpmyuANhxiHXwCHMYCw/s0/StaxRip_2017-07-25_22-01-28.png)  

1. Jobs window when screen size < 1280x720;
   ![< 1280x720](https://lh3.googleusercontent.com/-KcebK5Hgq98/WXczCmivR9I/AAAAAAACDTM/M0_sn_NPk5UfyPXFe1befIeQ48WZhXfEwCHMYCw/s0/StaxRip_2017-07-25_22-01-11.png) 

P.S. This also made me aware that the Jobs window is not resizable which would be a nice addition for working with long file path names (maybe should be another issue in itself)

**Comment by stax76** [comment]
I hope it's fixed in the next build, resize will be available.

**Comment by samkatakouzinos** [comment]
Version 1.6 commit f37db85 
Jobs window displays correctly when screen size < 1280x720. 
Tested at 1024x768. 
Thank you.
