### ISSUE TITLE
Add ability to use external fdkaac encoder

### ISSUE THREAD

**Issue by Soberia** [stax76/staxrip#238]
We need HE-AACv2 for super low bitrates (NeroAAC included in eac3to and ffmpeg's acc not good enough and qaac only support HE-AAC and LC-AAC)
I know about license issues but compiled fdkaac.exe can be imported by user to StaxRip (like MeGUI did)
and why AviSynth+ must installed by setup file unlike the other apps witch pre-inistalled?

-Thanks in advance for your hard-working

**Comment by stax76** [comment]
fdkaac cauld be added relative easy. Portable avisynth and vapoursynth is more difficult, the pipe tools or encoder must support it, I can look how megui does it.

**Comment by Soberia** [comment]
Thanks for your reply, I appreciate that
So I can wait for the future updates ... maybe god with you

**Comment by stax76** [comment]
Thanks, for fdkaac you can try the new build.

https://github.com/stax76/staxrip/blob/master/md/changelog.md
