### ISSUE TITLE
Error Video encoding using VCEEnc 3.06 x64

### ISSUE THREAD

**Issue by jocer71** [stax76/staxrip#245]
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.6.0.0
Windows    : Windows 10 Pro 1703
Language   : Slovak (Slovakia)
CPU        : Intel(R) Core(TM)2 Duo CPU     E8400  @ 3.00GHz
GPU        : Radeon (TM) RX 480 Graphics
Resolution : 1680 x 1050
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            Process Blu-Ray folder using eac3to
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"C:\Program Files\StaxRip\Apps\eac3to\eac3to.exe" "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\BDMV\PLAYLIST\"

Source Drive Type: Fixed
1) 00100.mpls, 00042.m2ts, 1:36:26                                             
   - Chapters, 10 chapters                                                     
   - h264/AVC, 1080p24 /1.001 (16:9)                                           
   - DTS Master Audio, English, multi-channel, 48kHz                           
   - AC3, Czech, multi-channel, 48kHz                                          
   - AC3, Hungarian, multi-channel, 48kHz                                      
   - AC3, Polish, multi-channel, 48kHz                                         
   - AC3, Russian, multi-channel, 48kHz                                        
   - AC3, Thai, multi-channel, 48kHz                                           
   - AC3, English, stereo, 48kHz                                               

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
             Process playlist file using eac3to
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"C:\Program Files\StaxRip\Apps\eac3to\eac3to.exe" C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\BDMV\PLAYLIST\ 1) -progressnumbers

M2TS, 1 video track, 7 audio tracks, 26 subtitle tracks, 1:36:26, 24p /1.001   
1: Chapters, 10 chapters                                                       
2: h264/AVC, 1080p24 /1.001 (16:9)                                             
3: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz                     
   (core: DTS, 5.1 channels, 1509kbps, 48kHz)                                  
4: AC3, Czech, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB                   
5: AC3, Hungarian, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB               
6: AC3, Polish, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB                  
7: AC3, Russian, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB                 
8: AC3, Thai, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB                    
9: AC3 Surround, English, 2.0 channels, 192kbps, 48kHz, dialnorm: -27dB        
10: Subtitle (PGS), English                                                    
11: Subtitle (PGS), Arabic                                                     
12: Subtitle (PGS), Bulgarian                                                  
13: Subtitle (PGS), Chinese                                                    
14: Subtitle (PGS), Chinese                                                    
15: Subtitle (PGS), Chinese                                                    
16: Subtitle (PGS), Korean                                                     
17: Subtitle (PGS), Croatian                                                   
18: Subtitle (PGS), Czech                                                      
19: Subtitle (PGS), Estonian                                                   
20: Subtitle (PGS), Hebrew                                                     
21: Subtitle (PGS), Hungarian                                                  
22: Subtitle (PGS), Latvian                                                    
23: Subtitle (PGS), Lithuanian                                                 
24: Subtitle (PGS), Polish                                                     
25: Subtitle (PGS), Portuguese                                                 
26: Subtitle (PGS), Romanian                                                   
27: Subtitle (PGS), Russian                                                    
28: Subtitle (PGS), Thai                                                       
29: Subtitle (PGS), Turkish                                                    
30: Subtitle (PGS), Ukrainian                                                  
31: Subtitle (PGS), Chinese                                                    
32: Subtitle (PGS), Czech                                                      
33: Subtitle (PGS), Hungarian                                                  
34: Subtitle (PGS), Russian                                                    
35: Subtitle (PGS), Thai                                                       

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
              Demux M2TS using eac3to 3.31 x86
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"C:\Program Files\StaxRip\Apps\eac3to\eac3to.exe" "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\BDMV\PLAYLIST\" 1) 2: C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv 3: "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID3 English.dtsma" 4: "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID4 Czech.ac3" 1: "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp_chapters.txt" 10: "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID10 English.sup" 18: "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID18 Czech.sup" 32: "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID32 Czech.sup" -progressnumbers

M2TS, 1 video track, 7 audio tracks, 26 subtitle tracks, 1:36:26, 24p /1.001
1: Chapters, 10 chapters
2: h264/AVC, 1080p24 /1.001 (16:9)
3: DTS Master Audio, English, 5.1 channels, 24 bits, 48kHz
(core: DTS, 5.1 channels, 1509kbps, 48kHz)
4: AC3, Czech, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
5: AC3, Hungarian, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
6: AC3, Polish, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
7: AC3, Russian, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
8: AC3, Thai, 5.1 channels, 640kbps, 48kHz, dialnorm: -27dB
9: AC3 Surround, English, 2.0 channels, 192kbps, 48kHz, dialnorm: -27dB
10: Subtitle (PGS), English
11: Subtitle (PGS), Arabic
12: Subtitle (PGS), Bulgarian
13: Subtitle (PGS), Chinese
14: Subtitle (PGS), Chinese
15: Subtitle (PGS), Chinese
16: Subtitle (PGS), Korean
17: Subtitle (PGS), Croatian
18: Subtitle (PGS), Czech
19: Subtitle (PGS), Estonian
20: Subtitle (PGS), Hebrew
21: Subtitle (PGS), Hungarian
22: Subtitle (PGS), Latvian
23: Subtitle (PGS), Lithuanian
24: Subtitle (PGS), Polish
25: Subtitle (PGS), Portuguese
26: Subtitle (PGS), Romanian
27: Subtitle (PGS), Russian
28: Subtitle (PGS), Thai
29: Subtitle (PGS), Turkish
30: Subtitle (PGS), Ukrainian
31: Subtitle (PGS), Chinese
32: Subtitle (PGS), Czech
33: Subtitle (PGS), Hungarian
34: Subtitle (PGS), Russian
35: Subtitle (PGS), Thai
Creating file "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp_chapters.txt"...
v02 Extracting video track number 2...
a03 Extracting audio track number 3...
s10 Extracting subtitle track number 10...
a04 Extracting audio track number 4...
a04 Removing AC3 dialog normalization...
s32 Extracting subtitle track number 32...
s18 Extracting subtitle track number 18...
v02 Muxing video to Matroska...
a03 Creating file "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID3 English.dtsma"...
a04 Creating file "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID4 Czech.ac3"...
s10 Creating file "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID10 English.sup"...
s18 Creating file "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID18 Czech.sup"...
s32 Creating file "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID32 Czech.sup"...
Added fps value (24 /1.001) to MKV header.
Video track 2 contains 138722 frames.
Subtitle track 10 contains 1532 captions.
Subtitle track 18 contains 1470 captions.
Subtitle track 32 contains 44 captions.
eac3to processing took 24 minutes, 18 seconds.
Done.

Start:    15:23:49
End:      15:48:10
Duration: 00:24:21

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv

General
Complete name         : C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv
Format                : Matroska
Format version        : Version 1
File size             : 21.3 GiB
Duration              : 1 h 36 min
Overall bit rate mode : Variable
Overall bit rate      : 31.7 Mb/s
Encoded date          : UTC 2017-07-30 13:23:53
Writing application   : eac3to
Writing library       : Haali DirectShow Matroska Muxer 1.13.138.14
ErrorDetectionType    : Per level 1
CRC_Error_Pos         : 232

Video
ID                    : 1
Format                : AVC
Format/Info           : Advanced Video Codec
Format profile        : High@L4.1
Format, CABAC         : Yes
Format, ReFrames      : 4 frames
Muxing mode           : Container profile=@0.0
Codec ID              : V_MPEG4/ISO/AVC
Duration              : 1 h 36 min
Bit rate mode         : Variable
Bit rate              : 31.0 Mb/s
Maximum bit rate      : 34.0 Mb/s
Width                 : 1 920 pixels
Height                : 1 080 pixels
Display aspect ratio  : 16:9
Frame rate mode       : Constant
Frame rate            : 23.976 (24000/1001) FPS
Color space           : YUV
Chroma subsampling    : 4:2:0
Bit depth             : 8 bits
Scan type             : Progressive
Bits/(Pixel*Frame)    : 0.624
Stream size           : 20.9 GiB (98%)
Default               : No
Forced                : No

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                    Index with ffmsindex
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"C:\Program Files\StaxRip\Apps\Plugins\both\ffms2\ffmsindex.exe" C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.ffindex

Writing index... done.

Start:    15:48:31
End:      15:51:07
Duration: 00:02:35

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                      AviSynth Script
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv", colorspace = "YV12", \
              cachefile = "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.ffindex")

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     Script Properties
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

source frame count : 138722
source frame rate  : 23.976024
source duration    : 01:36:25.8630000
target frame count : 138722
target frame rate  : 23.976024
target duration    : 01:36:25.8630000

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                Audio Source File MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                Audio Source File MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

General
Complete name         : C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID3 English.dtsma
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : MA / Core
File size             : 2.55 GiB
Overall bit rate mode : Variable / Constant
FileExtension_Invalid : dts dtshd

Audio
Format                : DTS
Format/Info           : Digital Theater Systems
Format profile        : MA / Core
Mode                  : 16
Format, Endianness    : Big
Bit rate mode         : Variable / Constant
Bit rate              : Unknown / 1 509 kb/s
Channel(s)            : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 93.750 FPS (512 spf)
Bit depth             : 24 bits
Compression mode      : Lossless / Lossy
General
Complete name         : C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp ID4 Czech.ac3
Format                : AC-3
Format/Info           : Audio Coding 3
File size             : 441 MiB
Duration              : 1 h 36 min
Overall bit rate mode : Constant
Overall bit rate      : 640 kb/s

Audio
Format                : AC-3
Format/Info           : Audio Coding 3
Format, Endianness    : Big
Duration              : 1 h 36 min
Bit rate mode         : Constant
Bit rate              : 640 kb/s
Channel(s)            : 6 channels
Channel positions     : Front: L C R, Side: L R, LFE
Sampling rate         : 48.0 kHz
Frame rate            : 31.250 FPS (1536 spf)
Bit depth             : 16 bits
Compression mode      : Lossy
Stream size           : 441 MiB (100%)
Service kind          : Complete Main

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
         Error Video encoding using VCEEnc 3.06 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

Video encoding using VCEEnc 3.06 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            Video encoding using VCEEnc 3.06 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

cmd.exe /S /C call ""C:\Program Files\StaxRip\Apps\VCEEnc\VCEEncC64.exe" --avvce --codec hevc --level 6.2 --cbr 6000 -i C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv -o "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Going in Style 2017 DTS-HD MA 5.1 EN, DD 5.1 CZ_out.hevc""

'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
            Video encoding using VCEEnc 3.06 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

cmd.exe /S /C call ""C:\Program Files\StaxRip\Apps\VCEEnc\VCEEncC64.exe" --avvce --codec hevc --level 6.2 --cbr 6000 -i C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Temp.mkv -o "C:\Users\Jojo\Videos\GOING_IN_STYLE_HDCLUB\Temp\Going in Style 2017 DTS-HD MA 5.1 EN, DD 5.1 CZ_out.hevc""

'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Start:    15:58:36
End:      15:58:37
Duration: 00:00:00

**Comment by Fencat** [comment]
Its a guess but try moving staxrip to a different folder (as in dont use "Program Files")

Setup section of the readme say this:

It's not recommended to start StaxRip from a location without full write access so 'C:\Program Files' shouldn't be used. StaxRip utilizes dozens of tools and some of this tools might require write access to their start-up directory.

**Comment by jocer71** [comment]
After the program is moved, the error is repeated
StaxRip 1.5 works well even when placed in program files
Any ideas?

**Comment by Fencat** [comment]
Sorry no idea then it was just a guess for an easy fix sorry it didnt help.

You will have to wait for stax76 to look at it.

**Comment by stax76** [comment]
Thanks for the report, it should be fixed in the next build.

**Comment by jocer71** [comment]
Thanks to it works from version 1.6.0.2.
