### ISSUE TITLE
Starxrip Wndows Problem With Bluray

### ISSUE THREAD

**Issue by D-Prince** [stax76/staxrip#246]
im currently using v1.6. while opening Blu-Ray file (32GB), After demuxing Staxrip window disappears. but task manager showed its still running. so, i've waited around 30-35m. but nothing happened. no new window. how to solve this problem ? here is the log - 

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                     System Environment
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

StaxRip    : 1.6.0.0
Windows    : Windows 10 Pro 1703
Language   : English (United States)
CPU        : Intel(R) Core(TM) i5-7600K CPU @ 3.80GHz
GPU        : NVIDIA GeForce GTX 1060 6GB
Resolution : 1600 x 900
DPI        : 96

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

G:\A\00002.m2ts

General
ID                       : 0 (0x0)
Complete name            : G:\A\00002.m2ts
Format                   : BDAV
Format/Info              : Blu-ray Video
File size                : 32.5 GiB
Duration                 : 1 h 46 min
Overall bit rate mode    : Variable
Overall bit rate         : 43.7 Mb/s
Maximum Overall bit rate : 48.0 Mb/s

Video
ID                       : 4113 (0x1011)
Menu ID                  : 1 (0x1)
Format                   : AVC
Format/Info              : Advanced Video Codec
Format profile           : High@L4.1
Format, CABAC            : Yes
Format, ReFrames         : 4 frames
Codec ID                 : 27
Duration                 : 1 h 46 min
Bit rate mode            : Variable
Maximum bit rate         : 35.0 Mb/s
Width                    : 1 920 pixels
Height                   : 1 080 pixels
Display aspect ratio     : 16:9
Frame rate               : 23.976 (24000/1001) FPS
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Scan type                : Progressive

Audio #1
ID                       : 4352 (0x1100)
Menu ID                  : 1 (0x1)
Format                   : DTS
Format/Info              : Digital Theater Systems
Format profile           : MA / Core
Mode                     : 16
Format, Endianness       : Big
Muxing mode              : Stream extension
Codec ID                 : 134
Duration                 : 1 h 46 min
Bit rate mode            : Variable / Constant
Bit rate                 : Unknown / 1 509 kb/s
Channel(s)               : 6 channels
Channel positions        : Front: L C R, Side: L R, LFE
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 spf)
Bit depth                : 24 bits
Compression mode         : Lossless / Lossy

Audio #2
ID                       : 4353 (0x1101)
Menu ID                  : 1 (0x1)
Format                   : DTS
Format/Info              : Digital Theater Systems
Format profile           : MA / Core
Mode                     : 16
Format, Endianness       : Big
Muxing mode              : Stream extension
Codec ID                 : 134
Duration                 : 1 h 46 min
Bit rate mode            : Variable / Constant
Bit rate                 : Unknown / 768 kb/s
Channel(s)               : 2 channels
Channel positions        : Front: L R
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 spf)
Bit depth                : 16 bits
Compression mode         : Lossless / Lossy

Audio #3
ID                       : 4354 (0x1102)
Menu ID                  : 1 (0x1)
Format                   : DTS
Format/Info              : Digital Theater Systems
Format profile           : MA / Core
Mode                     : 16
Format, Endianness       : Big
Muxing mode              : Stream extension
Codec ID                 : 134
Duration                 : 1 h 46 min
Bit rate mode            : Variable / Constant
Bit rate                 : Unknown / 1 509 kb/s
Channel(s)               : 6 channels
Channel positions        : Front: L C R, Side: L R, LFE
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 spf)
Bit depth                : 16 bits
Compression mode         : Lossless / Lossy

Audio #4
ID                       : 4355 (0x1103)
Menu ID                  : 1 (0x1)
Format                   : DTS
Format/Info              : Digital Theater Systems
Format profile           : MA / Core
Mode                     : 16
Format, Endianness       : Big
Muxing mode              : Stream extension
Codec ID                 : 134
Duration                 : 1 h 46 min
Bit rate mode            : Variable / Constant
Bit rate                 : Unknown / 768 kb/s
Channel(s)               : 2 channels
Channel positions        : Front: L R
Sampling rate            : 48.0 kHz
Frame rate               : 93.750 FPS (512 spf)
Bit depth                : 16 bits
Compression mode         : Lossless / Lossy

Text #1
ID                       : 4608 (0x1200)
Menu ID                  : 1 (0x1)
Format                   : PGS
Codec ID                 : 144

Text #2
ID                       : 4609 (0x1201)
Menu ID                  : 1 (0x1)
Format                   : PGS
Codec ID                 : 144

Text #3
ID                       : 4610 (0x1202)
Menu ID                  : 1 (0x1)
Format                   : PGS
Codec ID                 : 144

Text #4
ID                       : 4611 (0x1203)
Menu ID                  : 1 (0x1)
Format                   : PGS
Codec ID                 : 144

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
               Process M2TS file using eac3to
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

H:\staxrip\StaxRip-x64-1.6\Apps\eac3to\eac3to.exe G:\A\00002.m2ts -progressnumbers

M2TS, 1 video track, 4 audio tracks, 4 subtitle tracks, 1:46:36, 24p /1.001    
1: h264/AVC, 1080p24 /1.001 (16:9)                                             
2: DTS Master Audio, 5.1 channels, 24 bits, 48kHz                              
   (core: DTS, 5.1 channels, 1509kbps, 48kHz)                                  
3: DTS Master Audio, 2.0 channels, 16 bits, 48kHz                              
   (core: DTS, 2.0 channels, 768kbps, 48kHz)                                   
4: DTS Master Audio, 5.1 channels, 16 bits, 48kHz                              
   (core: DTS, 5.1 channels, 1509kbps, 48kHz)                                  
5: DTS Master Audio, 2.0 channels, 16 bits, 48kHz                              
   (core: DTS, 2.0 channels, 768kbps, 48kHz)                                   
6: Subtitle (PGS)                                                              
7: Subtitle (PGS)                                                              
8: Subtitle (PGS)                                                              
9: Subtitle (PGS)                                                              

-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
              Demux M2TS using eac3to 3.31 x86
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

H:\staxrip\StaxRip-x64-1.6\Apps\eac3to\eac3to.exe G:\A\00002.m2ts -progressnumbers

M2TS, 1 video track, 4 audio tracks, 4 subtitle tracks, 1:46:36, 24p /1.001
1: h264/AVC, 1080p24 /1.001 (16:9)
2: DTS Master Audio, 5.1 channels, 24 bits, 48kHz
(core: DTS, 5.1 channels, 1509kbps, 48kHz)
3: DTS Master Audio, 2.0 channels, 16 bits, 48kHz
(core: DTS, 2.0 channels, 768kbps, 48kHz)
4: DTS Master Audio, 5.1 channels, 16 bits, 48kHz
(core: DTS, 5.1 channels, 1509kbps, 48kHz)
5: DTS Master Audio, 2.0 channels, 16 bits, 48kHz
(core: DTS, 2.0 channels, 768kbps, 48kHz)
6: Subtitle (PGS)
7: Subtitle (PGS)
8: Subtitle (PGS)
9: Subtitle (PGS)

Start:    7:37:29 AM
End:      7:37:30 AM
Duration: 00:00:01

on Background > 
<img src="http://www.keepimg.com/images/P-30f1320.png" alt="P-30f1320.png" border="0" />

**Comment by stax76** [comment]
It might be caused by the source filter used, TS/M2TS is the most difficult container to parse for a source filter.

If this is a Blu-ray source then I recommend MakeMKV, eac3to with MKV output works too.

**Comment by D-Prince** [comment]
yep, it worked , thanks :)
