### ISSUE TITLE
Issues opening .avs files

### ISSUE THREAD

**Issue by RealTehreal** [stax76/staxrip#248]
First: Thank you very much for this great tool. It's always been working like a charm.

Now the issue: Yesterday I've updated from 1.4.0.0 to 1.6 - now I get an error when I try to open an .avs file.

```
Failed to load script.

FFIndex: Can't open 'video.mp4'
(E:\temp\avsfile.avs, line 2)
```
This happens with version 1.5 too. The latest version without this problem is 1.4.0.0, to which I've fallen back for now.

Please tell me if there is anything I can do / test / provide to you.

kr

**Comment by stax76** [comment]
It might be script specific, with a simple script I wasn't able to reproduce it, what is the content and location of the script?

**Comment by RealTehreal** [comment]
It happens when using relative paths to media files:

```
z:\test.avs
===========
LoadPlugin("c:\AviSynth+\plugins64+\ffms2.dll")
FFmpegSource2("video.mp4", vtrack=-1, atrack=-1, cache=True, cachefile="", fpsnum=60, fpsden=1, threads=-1, timecodes="", seekmode=1, overwrite=False, width=-1, height=-1, resizer="BICUBIC", colorspace="", rffmode=0, adjustdelay=-1, utf8=False, varprefix="")
```

It works this way though:
```
z:\test.avs
===========
LoadPlugin("c:\AviSynth+\plugins64+\ffms2.dll")
FFmpegSource2("Z:\video.mp4", vtrack=-1, atrack=-1, cache=True, cachefile="", fpsnum=60, fpsden=1, threads=-1, timecodes="", seekmode=1, overwrite=False, width=-1, height=-1, resizer="BICUBIC", colorspace="", rffmode=0, adjustdelay=-1, utf8=False, varprefix="")
```

Is staxrip possibly parsing the .avs file, looking for media files and handing the paths (from within the .avs file) to another cmd tool? This could be the reason why it then won't find the relative file path.

kr

**Comment by stax76** [comment]
It is parsing the avs/vpy file to find out the video source file but it only works if the source filter ends with 'Source' and not 'Source2', staxrip will probably still work even if it can't find a video source file.

In your case it was something else, it creates a new temp dir and saves the script there, it was changed because of a request:

https://forum.doom9.org/showthread.php?p=1804905#post1804905

I don't know if both can be supported easily at the same time and what is more important.

**Comment by stax76** [comment]
I'll add a option to define for which file types no _temp dir should be created.

**Comment by RealTehreal** [comment]
Ah I see. Yeah, such an option would be nice. Thanks in advance.

**Comment by stax76** [comment]
I'm not adding a option for the file types, two things I did:

1. Make the detection of the video source file more reliable, example that will work:

```
path = "video.mp4"
FFmpegSource2(path)
```

2. Detect if the video source file is a relative path and then set the temp dir to the folder of the avs file.

**Comment by stax76** [comment]
Please test if it works:

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Comment by RealTehreal** [comment]
Works like a charm again. Thanks for resolving this issue. Keep up the good work :+1:
