### ISSUE TITLE
Two MP3 Audio Streams in Xvid

### ISSUE THREAD

**Issue by rkolja** [stax76/staxrip#25]
Hi,

I've noticed that if you want to create an AVI file (Xvid profile) with two audio streams, the current BETA will only encode the first stream.

I've enclosed the log-file.
If you need further input, please let me know.

Cheers,
rkolja
[test-log.txt](https://github.com/stax76/staxrip/files/72274/test-log.txt)

**Comment by derfry** [comment]
Hi,

I have a similar problem. It seems that the same filename is used for the audio temp files if you want to use the same codec for both audio streams. My target video contains two audio streams, but both are in the same language. If you use different codecs, e.g. AAC for the first and MP3 for the second stream, it works fine.

Cheers,
Fry

**Comment by stax76** [comment]
Next release should have everything fixed.
