### ISSUE TITLE
ISSUE  - how to add job (file) while encoding (is it possible?)

### ISSUE THREAD

**Issue by isvahid** [stax76/staxrip#251]
hi i have a problem (STAXRIP 1.6)
i set a batch to encode files (i.e 4 files), when files are encoding i want to add another file to the job list (or queue list) but i get an error.

is it possible to add file while encoding? if not please add this feature very usefull

**Comment by Fencat** [comment]
Not sure what error you are getting but simply opening a new instance of staxrip and adding a new job works for me. it gets added to the same queue/jobs list.

**Comment by isvahid** [comment]
tnx a lot, i didnt know about opening new staxrip and add a job, i just simply click on Jobs (on job proccessing) and drag and drop ! for 2 years my fav software was VidCoder (with Drag and Drop)!
