### ISSUE TITLE
test build page not found

### ISSUE THREAD

**Issue by DandyClubs** [stax76/staxrip#252]
StaxRip x64 1.6.0.2 unstable test build

Help -> Website -> test build

https://github.com/stax76/staxrip/blob/master/md/test-build.md

page not found

maybe change address

**Comment by stax76** [comment]
Thanks for reporting, it's fixed in the next build, the new address is:

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Comment by stax76** [comment]
It's online now.

https://github.com/stax76/staxrip/blob/master/md/changelog.md
