### ISSUE TITLE
How to enable vapoursynth instead of avisynth

### ISSUE THREAD

**Issue by Helenerineium** [stax76/staxrip#253]
When opening a file, staxrip shows a message:
Unicode filenames are not supported by AviSynth.
VapourSynth supports unicode, it can be enabled at:
Filters > Filter Setup > VapourSynth (I can't find it)
Don't know how to enable Vapoursynth instead of avisynth
(Vapoursynth already installed, Status:OK)
Hopes to get step-by-step instructions
Thank you

**Comment by stax76** [comment]
In the main dialog is a filters listView, it has a context menu (right-click), there is also a label button on top of the listView that shows the menu on left-click, this button has the caption 'Filters'.

**Comment by Helenerineium** [comment]
I am not aware of that I can click the words that are colored.
Thank you.
