### ISSUE TITLE
Issue : VSFilterMod,MKV toolnix 13 and NVEncC64

### ISSUE THREAD

**Issue by joske1964** [stax76/staxrip#254]
These are the problems I ran into with version 1.6 of Staxrip:
I got an error when using VSFilterMod and solved this by using VSFilterMod64 instead.
You can download VSFilterMod64 at https://code.google.com/archive/p/vsfiltermod/downloads
Also the Changelog of MKV toolnix 13.0.0.0 made me worry, so I instantly moved to MKV toolnix 14.0.0.0.
The link where the changes can be found for MKV toolnix is this: https://mkvtoolnix.download/doc/NEWS.md
See here the part of the changelog I am worried about:
HEVC/h.265 parser: fixed wrong frame order & timestamp calculation
in certain situations when SPS (sequence parameter sets) or PPS (picture
parameter sets) change mid-stream. This is the HEVC/h.265 equivalent of
#2028.
Furthermore I instantly updated to NVEncC64 3.17 instead of 3.14 due to problems with chroma 4:2:2 and 4:4:4.
Link can be found here:
https://github.com/rigaya/NVEnc/releases
And last but not least, I am unable to load more than 1 file at the same time into staxrip when I am reencoding 2 streams
at the same time with NVEncC64 and have a lot of heavy tasks open in the background. Since it will automaticly
stop the loading of the source file when it's just about done. It will become a background process that never stops
or does anything. This is due to the heavy load and multitasking not waiting properly for the window to the ready.
Only 1 file will be loaded and the rest will all go to background processes that never end or do anything.

**Comment by stax76** [comment]
I think I used 2-3 different VSFilter derivatives before and each had their own issues so I'm not gonna change it again, I hardly remember why I changed it before since I'm not using it myself.

The apps in the test builds are mostly up to date, if it's not requests are always welcome.

https://github.com/stax76/staxrip/blob/master/md/changelog.md

For the process issue, such things are difficult to reproduce and there are other issues reported which are also difficult to reproduce so a clean, detailed and comprehensive explanation would greatly help me to reproduce and fix, so far I cannot make a lot sense out of your description.

**Comment by joske1964** [comment]
Computer Used:
Windows 10 Pro x64 NL up-to-date
Disks:
C: 2xSamsung 830 SSD in Raid 0 512GByte in total
D: 2xWestern Digital Raptor in Raid 0 1.2TByte in total
Processor: i7 4790K @stock speed (4400 with Turbo Boost)
Memory: 16GB Corsair Vengeance 2133Mhz DDR3 @stock speed (2133 Mhz)
https://uk.pcpartpicker.com/product/Rn3RsY/corsair-memory-cmy16gx3m2a2133c9r
Videocard: MSI 1080GTX GAMING X 8G @stock speed (1822Mhz)
Motherboard: Gigabyte GA-Z97X-UD3H rev. 1.0 BIOS update F9
StaxRip installation location: D:
Blu-ray Disk Images location: D:
StaxRip Workdirectory location: C:
Settings and installed software used:
https://drive.google.com/open?id=0B_w0SPyAj5qLUUtUSU9DaUlRMW8
StaxRip Settings location: D:
There are 2 issues that occure:
1: When 2 Blu-rays are being reencoded from the workdirectory and I try to open multiple Blu-rays at the same time and let them being demuxed into the workdirectory only 1 will finish the rest will all become a background process after it's been totally processed. So after the subtitles have been redone to idx/sub it stops and fails to load the basic window from staxrip where you can select the source and put all the settings. It gives no error at all whatsoever and just becomes a background process. This whole process is done while having multiple tasks in the background that read and write a lot on both disks and keep the processor at 100% load at ALL times.
2: When more than 10 jobs are open in the jobmanager it gives a "jobs.dat could not be opened due to it being used by another process" error. After that the 2 reencodes that were busy are finished and than the jobmanager stops.
My best guess is one of the drives is too slow to keep up with jobs.dat.

**Comment by stax76** [comment]
If I understand right then you have 2 staxrip instances working on the shared job list and at the same time open BD folders for eac3to demuxing with another one or more staxrip instances in parallel, correct?

**Comment by joske1964** [comment]
Yes

**Comment by stax76** [comment]
The newest test build has a change that might fix 1.)

**Comment by joske1964** [comment]
I have tested both the test version and v1.6 now with a brand new m.2 ssd and on both versions the issue no longer occures. So it was definately the raptor harddisks being too slow
