### ISSUE TITLE
x265 options improvement

### ISSUE THREAD

**Issue by Helenerineium** [stax76/staxrip#255]
![x265-analyis](https://user-images.githubusercontent.com/30746806/28999719-2a1bd402-7a85-11e7-8067-ed8ca328091a.png)
![x265-ratecontrol2](https://user-images.githubusercontent.com/30746806/28999720-2a3aae68-7a85-11e7-9f22-283618f8ff21.png)
Test build 1.6.02
In x265 options
Analyis: min-cu-size is wrongly display as 3
Rate Control: Cb Qp Offset should be put together with Cr Qp Offset(--crqpoffs)
No problem encoding
![image 1](https://user-images.githubusercontent.com/30746806/28999781-2b2cede8-7a87-11e7-80b4-ae1ea2610d29.png)
I want to ask about Comp.Check and Aimed Quality, there are not x265 parameters, and I don't understand the explanations when right-click.

**Comment by stax76** [comment]
> Analyis: min-cu-size is wrongly display as 3
> Rate Control: Cb Qp Offset should be put together with Cr Qp Offset(--crqpoffs)

It should be fixed in the next build.

Comp.Check and Aimed Quality are related to the compressibility check, if you are not using compressibility check you can ignore it, it's not easy to explain, please ask in the forum.

**Comment by stax76** [comment]
The new build is online.

https://github.com/stax76/staxrip/blob/master/md/changelog.md
