### ISSUE TITLE
Templates do not preserve settings after update

### ISSUE THREAD

**Issue by Zcehtro** [stax76/staxrip#257]
I've been away some time and the last version I was on was 1.5.0.7.
I upgraded to 1.6.0.0 and noticed that although my custom templates were still there in the menus, the settings they managed were not saved.

Perhaps, include an updater for templates that updates old settings to new ones, so that they don't get outdated?

**Comment by Zcehtro** [comment]
Just saw in the changelog that there's a new GUI for x264.
I suppose that the profile settings are saved per encoder, so the new GUI for x264 is treated like a new encoder.
Hence why the settings aren't preserved.

Hmmmm.....

**Comment by stax76** [comment]
I've reset the video encoders while working on the x264 GUI. Sometimes I write migration code, other times I just reset, it depends on the situation.
