### ISSUE TITLE
Issue: Concerning StaxBackup

### ISSUE THREAD

**Issue by pwacooijmans** [stax76/staxrip#258]
Dear Stax76,

Hereby I would REALLY like to ask you to make an update for StaxBackup the amazing GUI for Robocopy.
There is an issue with it so you can't backup selections, just everything.

Many thanks for writing this tool in the first place, best backup tool EVER.

With Kind Regards,

P. Cooijmans

PS: I know I shouldn't discuss StaxBackup here but I can't find the site for it anymore :(

**Comment by stax76** [comment]
I don't remember it and don't have the source code. I've a CLI app called util.exe which contains many tools I wrote for personal use, it contains my robocopy GUI I currently use for my backups.

https://postimg.org/image/5hrp9reyd/

**Comment by pwacooijmans** [comment]
Thank you SO much for this.

Where can I download util.exe?

**Comment by stax76** [comment]
I gave up releasing small tools, I can upload it but need to review it first.

**Comment by pwacooijmans** [comment]
That's fine, just tell me where I can download it when it is uploaded. Many thx for doing this.

**Comment by stax76** [comment]
Use at your own risk.

https://drive.google.com/open?id=0B-gPKiJYuKuIWmZUOVA5eGw3c0E

**Comment by pwacooijmans** [comment]
Thank you SO much for this! Works perfectly!
