### ISSUE TITLE
VP8 WebM support?

### ISSUE THREAD

**Issue by uNderdog101** [stax76/staxrip#259]
Any chance of adding support for encoding VP8/Vorbis WebMs?

I absolutely love Staxrip for encoding to VP9/Opus, but it's too bad it can't also do VP8 encoding, since certain sites on the net don't allow uploading of VP9 format WebMs.

The alternatives I've found aren't great; WebMconverter is pretty mediocre and only really got its ease of use going for it, and Xmedia Recode is buggy and stops working properly on my system if I update to a version newer than a year old one (2pass encoding crashes and the audio sound tinny even if I don't change any settings). FFMPEG could certainly accomplish greatness by itself, but, ya know, I'm an idiot, so I suck at the command line.

**Comment by uNderdog101** [comment]
Awesome. Was this already planned, or did I actually affect change through inquiry?

**Comment by stax76** [comment]
It wasn't planned, always feel free to post feedback, good or bad.
