### ISSUE TITLE
MKVs, softsubs, chapters and titles

### ISSUE THREAD

**Issue by ahmedflix25** [stax76/staxrip#26]
1-if I have an MKV file with embed softsub file and I convert it with the app to MKV the sub will still there as softsub we need option to make the app burn it to the video (hard sub) and make it an mp4 or any other container
2-the same goes for chapters if the convert it as mkv it will remain there but if I change it to mp4 I will lose the chapters/menu list also we need option to keep those 
3-if the video file have a title and I convert it with the app it will lose it's title

**Comment by stax76** [comment]
There is a option at Tools | Advanced | Hardcoded Subtitles

Title will be kept for MKV output in the next build.

MP4 support is limited.

Please write only one issue per time and try to describe a bit better.

**Comment by ahmedflix25** [comment]
that option Tools | Advanced | Hardcoded Subtitles add only spirited subs files not the embedded ones with mkvtoolnix
the subs I meant 
http://imgur.com/dyv9DvO
the chapters I meant
http://imgur.com/lILxaln

next time I will great app by the way, thanks

**Comment by stax76** [comment]
Personally I don't use subtitles so I don't have experience with it, for a subtitle request I would need a very clean and very detailed description.

**Comment by ahmedflix25** [comment]
like audio and video with MKVs you can add subtitles tracks (as soft sub) and chapters track 
the program can easily add a spirited subtitle file for hardcoding but it can't get the subtitle if it was embedded to the mkv as track

**Comment by stax76** [comment]
I'm sorry but it's very bad English with hardly details, I simply don't understand.

**Comment by ahmedflix25** [comment]
MKVs files has video track, audio tracks, subtitle tracks and chapters track
your program can detect the video and audio tracks but not the other two
and Tools | Advanced | Hardcoded Subtitles option works only for standalone subs files only

**Comment by ahmedflix25** [comment]
if I had file.mkv + subfile.ass I can hardcoded sub with Tools | Advanced | Hardcoded Subtitles option
but if the subtitle file was embedded within the mkv file as a track like that image http://imgur.com/dyv9DvO
then I can't hardcode it with the video

**Comment by stax76** [comment]
Did you saw the container options (muxing dialog)?

**Comment by stax76** [comment]
When I have time I add mkv input support to the hardcoded feature, until then you can demux the subtitle using StaxRip's demuxing dialog.

**Comment by ahmedflix25** [comment]
thanks, great app
