### ISSUE TITLE
nvhsp added to nvenc hdr content

### ISSUE THREAD

**Issue by pwacooijmans** [stax76/staxrip#261]
I have a feature request for NVEncC64 encoded videos with HDR on a 10x0 Nvidia card. Could you please add nvhsp.exe as a post process for hdr content specially for those kind of reencodes with NVEncc64 to add the HDR10 Metadata?
It's totally free and this is the website:
https://github.com/SK-Hardwired/nv_hevc_hdr_patcher
This would save me tons of time instead of having to type everything myself manually in a bat file. This is simply because it can go straight to an MKV instead of having to do the post process manually.
PS: of course this doesn't work together with the OLD region settings (PAL) in V1.6 of staxrip.

So my idea is to add an on and off switch for hdr content and if it's on you can enter the things needed by nvhsp to add HDR10 Metadata specially for nvenc videos. The on and off switch means it will either do or skip the nvhsp after the h265 reencode and put it into an mkv.

Many thanks for the backup tool and hopefully you can make this work too.

**Comment by stax76** [comment]
I usually don't add HDR features, I've added an event after the video encoder and a macro to get the encoder name, there are two ways you will be able to do it either with a powershell extension which is difficult or with a event command (Tools > Advanced > Event Command), here is a event command example using dos/batch:

![unbenannt](https://user-images.githubusercontent.com/11410540/29174139-ad4036b2-7de5-11e7-8875-6b370fcc8fbf.png)

**Comment by pwacooijmans** [comment]
Thank you SO much for this

**Comment by stax76** [comment]
A new build should be online in 1-2 minutes.

**Comment by foXaCe** [comment]
hello i use this settings

-masterdisplay G(15000,30000)B(7500,3000)R(32000,16500)WP(15635,16450)L(4000000,1) -maxcll 400,400

but the HDR do not works why ?

**Comment by pwacooijmans** [comment]
Hello, which videocard do you have? Only the 10x0 series from nvidia
support this. Second your maxcll are odd...avg is the same as max


Op 11 nov. 2017 12:24 p.m. schreef "foXaCe" <notifications@github.com>:

**Comment by foXaCe** [comment]
yes it is a 1060.
what are the [-params] that you use?

**Comment by pwacooijmans** [comment]
I use properties with mpc-be to see the correct values. Mpc-be is a very
small mediaplayer with mediainfo intergrated.


Op 11 nov. 2017 12:30 p.m. schreef "foXaCe" <notifications@github.com>:

**Comment by pwacooijmans** [comment]
These are the correct parameters when translating from mediainfo:
Inferno (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '10000,3647'
La La Land (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,0)`
-maxcll '1000,640'
Passengers (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '1529,380'
Patriots Day (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15634,16450)L(10000000,0)`
-maxcll '1000,510'
The Huntsman - Winter's War (2016) (Extended Edition) -colorprim bt2020
-transfer smpte-st-2084 -chromaloc 2 -videoformat pal -colormatrix bt2020nc
-full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,50)`
-maxcll '1000,400'
The Martian (2015) (Extended Edition)  -colorprim bt2020 -transfer
smpte-st-2084 -chromaloc 2 -videoformat pal -colormatrix bt2020nc
-full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,0)`
The Shallows (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '1933,709'
The Smurfs 2 (2013) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '1132,923'

For the dutch version of these movies.

It's pretty easy once you know what you are doing: the string is 'G(X times
50000, Y times 50000)B(X times 50000, Y times 50000)R(X times 50000, Y
times 50000)WP(X Times 50000,Y Times 50000)L(X Times 10000, Y Times 10000)'
-maxcll 'MAX times 1, AVG times 1'

Op 11 nov. 2017 12:30 p.m. schreef "foXaCe" <notifications@github.com>:

**Comment by pwacooijmans** [comment]
And further more make sure you do NOT set PAL settings IN staxrip itself,
since that is the OLD version of PAL.

2017-11-11 12:30 GMT+01:00 foXaCe <notifications@github.com>:

**Comment by pwacooijmans** [comment]
https://drive.google.com/open?id=0B_w0SPyAj5qLNnBrWFJINVFYQlU

Here are some templates for StaxRip you can use.

2017-11-11 12:45 GMT+01:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by foXaCe** [comment]
ok thank you. I will test

**Comment by foXaCe** [comment]
ok thank you, all work very good.
thank for you help

**Comment by Biatscho** [comment]
How you get ur nvhsp to work ????, cant get it working ...... (when it writes the vui it deletes my sei data) staxrip 1.7.0.5 running
tried with 1.6.7 still no luck ?????
do you got a step by step guide wich settings u use in nvenc sei (not the specifics for movies just standards to tryout and fill ins to the nvhsp command

**Comment by pwacooijmans** [comment]
https://drive.google.com/open?id=0B_w0SPyAj5qLNnBrWFJINVFYQlU

Hereby I send you a google link with the some premade templates....I am
very sorry but I don't have the time to explain everything.
This should get you in the right direction though.

Keep in mind this does NOT work properly with the latest nvidia drivers.
You better try a bit older ones.

I definately need to update this when I get the time for it....but so far
haven't gotten to it.

Have fun and take care.

2018-01-31 17:43 GMT+01:00 Biatscho <notifications@github.com>:

**Comment by pwacooijmans** [comment]
These are the correct parameters when translating from mediainfo:
Inferno (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '10000,3647'
La La Land (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(10000000,0)`
-maxcll '1000,640'
Passengers (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '1529,380'
Patriots Day (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15634,16450)L(10000000,0)`
-maxcll '1000,510'
The Huntsman - Winter's War (2016) (Extended Edition) -colorprim bt2020
-transfer smpte-st-2084 -chromaloc 2 -videoformat pal -colormatrix bt2020nc
-full_range tv -masterdisplay `G(13250,34500)B(7500,3000)R(
34000,16000)WP(15635,16450)L(10000000,50)` -maxcll '1000,400'
The Martian (2015) (Extended Edition)  -colorprim bt2020 -transfer
smpte-st-2084 -chromaloc 2 -videoformat pal -colormatrix bt2020nc
-full_range tv -masterdisplay `G(13250,34500)B(7500,3000)R(
34000,16000)WP(15635,16450)L(10000000,0)`
The Shallows (2016) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '1933,709'
The Smurfs 2 (2013) -colorprim bt2020 -transfer smpte-st-2084 -chromaloc 2
-videoformat pal -colormatrix bt2020nc -full_range tv -masterdisplay
`G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50)`
-maxcll '1132,923'

For the dutch version of these movies.

It's pretty easy once you know what you are doing: the string is 'G(X times
50000, Y times 50000)B(X times 50000, Y times 50000)R(X times 50000, Y
times 50000)WP(X Times 50000,Y Times 50000)L(X Times 10000, Y Times 10000)'
-maxcll 'MAX times 1, AVG times 1'



2018-01-31 17:43 GMT+01:00 Biatscho <notifications@github.com>:

**Comment by pwacooijmans** [comment]
Oh and make bloody sure you actually have a 10x0 nvidia card 9x0 won't
work...since it does NOT support HDR

2018-01-31 17:58 GMT+01:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
NVIDIA Driver 385.69 is the last driver to work properly with this, after
that nvenc stops to work correctly. It's waiting for a major update on
nvenc before this will be fixed. And NVEnc version 3.17 is kinda stable.
Anything below that and you will get problems.

**Comment by pwacooijmans** [comment]
I use properties with mpc-be to see the correct values. Mpc-be is a very
small mediaplayer with mediainfo intergrated.



2018-01-31 17:43 GMT+01:00 Biatscho <notifications@github.com>:

**Comment by pwacooijmans** [comment]
And last but not least:

Why do I use these versions of the software and not more recent ones:
-MKVToolNix 14.0.0.0 (ALSO IN STAXRIP!!!!...you HAVE to manually replace
the files) Why? After version 14.0.0.0 from MKVToolNix the team has started
rebuilding MKVToolNIX ENTIRELY. This process will take YEARS. Yes they do
put out versions very frequently. But EVERY EMBL library update means they
HAVE to rebuild MKVToolNix. So I stick with the old library TILL a new EMBL
library is added. That means the version is finally somewhat stable and
most bugs have been fixed. So keep in mind ALWAYS Stay 1 EMBL Library
behind!
-NVEnc 3.17 (ALSO IN STAXRIP!!!....you MAY have to manually replace these
files) This version was the first kinda stable version to work properly
with nvhsp. After that there have been updates I know, however these
updates were made on current drivers from NVIDIA meaning some important
features were removed like -weightp and things like that.
-StaxRip test version: This is because 1.6.0.0 was totally buggy and this
is probably the last version that works with nvhsp properly. 1.6.7 has a
half intergrated "nvhsp" that StaxRip itselfs tries to do. However it lacks
a LOT of features that real nvhsp has. Yes I know it's a test version....so
it's not bug free either. The most important thing you have to remember is
that this version will not support more then a max of 8 jobs in the queue
due to a memory leak. Rest of it works fine.
StaxRip 1.7 makes use of MKVToolNix 20.0.0.0 which means it is based on a
different commandline command so you can't copy MKVToolNix 14.0.0.0 into
1.7 and make it work. Also 1.7 has a futher intergrated own version of
nvhsp...however still not with all the features neccesary.
-Why do I set a PAL region? Simply because a LOT of TVs do NOT support NO
region specified and PAL region is the Dutch region. There is a map
included in the google drive link I sent you earlier.
-And last but not least: I made profiles of the new standard blu-ray discs
with "lossless" quality. Of course it's not 100% lossless however the naked
eye won't see the difference. The subjective lossless h265 from h264 files
is a very interesting one. It basicly means you can encode any old blu-ray
25GB or 50GB into 12000kilobits per second h265 and if you play the video
normally you shouldn't be able to see a difference in quality. However if
you stop the video you will see a change. This I can support with math.
Just lookup on Wiki what the subjective test results are for h265 compared
to h264. You will see it's 62.something % reduction on avg for 1080p. This
means that you can reduce the bitrate by 56% (also from the same article)
and it's for all 1080p movies. Normally a standard 50GB blu-ray movie in
1080p has a bitrate between 25000 and 40000 for the more modern blu-rays.
The new blu-ray discs at 4k HDR need at LEAST 25000kilobits per second avg
in h265 codec with a max of 40000 to at least see an improvement in quality
over the old blu-ray. Simply put: Don't try to reencode 4K lower than
25000kilobits avg or you are better off with the old 1080p version. This is
because of the extra features added to 4K HDR blu-rays like color depth and
so on and so on. Then why did I choose for 25000kilobits and not higher?
This has to do with the TVs again. Since there are PLENTY of TVs that do
NOT support bitrates in 4K HDR over 25000kilobits. So it's just because of
compatibility.
-PS: Forget about streaming to google chromecast ultra or any other media
player. The ONLY mediaplayer that supports 4K HDR properly atm is the
nvidia shield pro 2017 with the 500GB hdd in combination with kodi or a PC
with a 10x0 graphics card connected to a tv. Maybe the new playstation
and/or xbox also work however I have no clue about that. And YES YOU WILL
NEED WIRED 1gigabit ethernet. 100Mbit is too slow and will result in a LOT
of lag and desync issues. So you can say for sure that ANY mediaplayer with
100Mbit can NOT properly support 4K HDR streams. Wifi in very very rare
cases works, but more than 90% of the time it ends up in lagfest. The best
movie to test if your player is up for the task is Inferno. This movies is
made so that it causes extreme bitrate spikes. Especially the scene where
Tom Hanks is in the fake hospital near the start of the movie. It's basicly
a performance test for mediaplayers.

2018-02-01 3:00 GMT+01:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
Sorry I meant the NVidia Shield TV Pro of course with 500Gb harddisk. Why
the harddisk?...kodi takes up a LOT of space and the 16GB flash memory you
get on the lower model is frustratingly slow AND you will run out of space
quick if you want to install games or anything else.

2018-02-01 4:09 GMT+01:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
The NVidia Shield TV Pro 2017 500GB is meant for streaming movies over your
ethernet connection. It can however store movies on the 500GB harddisk but
a NAS or PC network Share is more ideal. It ALSO has a build in google
chromecast ultra so that also works ...funny thing is it actually works
better than the chromecast ultra itself due to the WAAAAY faster processor
the shield has.

2018-02-01 4:18 GMT+01:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by pwacooijmans** [comment]
Oh and the last thing....you said not specifics for movies....this is a
pretty common mistake due to the legacy of the h264 standard. ALL movies
WITH HDR have a specific setting, because they were made on a specific
monitor with a specific setting for professional use. IF you do NOT set
these specific settings the device you play the movie from in most cases
will NOT play back in HDR, simply because it does NOT know how to translate
the specific monitor settings correctly to the playback monitor so that the
movie looks correctly. The WHOLE idea behind HDR is to END the ENDLESS
tweaking of colors due to differences between monitors. No monitor is
exactly the same as a second same type of monitor, so in order to make the
colors on every monitor somewhat the same there have been made a LOT of
rules what makes an HDR monitor an HDR monitor. If you have a decent HDR
monitor it lets the playback device know the display string as shown in
earlier e-mails so it can calculate back what the correct colors for THAT
specific movie are on the CURRENT monitor. This is all factory standard and
yes still you can of course tweak your monitor to your likings. However
without those settings most devices don't know what to do with the HDR
stream OR play it back at some random factory default that doesn't make any
sense. Hope this makes some things clear about the somewhat new HDR
standard. It's just one of the major problems movies studios kept running
in to. If you have 40 people making a movie on 40 different computers you
get 40 different color strings. So in order to make a movie look okay they
needed this standard else the increase of color depth would reveal a LOT of
artifects....not because they ARE artifects...but simply monitors that
didn't have the proper alignment. So to say it in math, color: 127,127,127
would be different on each monitor so some movie editors would make it
128,126,129 to make it look right on THEIR monitor, hench the issues.

2018-01-31 17:43 GMT+01:00 Biatscho <notifications@github.com>:

**Comment by pwacooijmans** [comment]
HDR is one of the main reasons that real 4K HDR content from a playback
device connected to a TV only works via the hdmi 2.0 port because of the
master display string and such on most current TVs.

2018-02-01 7:31 GMT+01:00 Pieter Cooijmans <pwacooijmans@gmail.com>:

**Comment by Biatscho** [comment]
@foXaCe 
just insert these settings
--max-cll 1000,602
--master-display G(13250,34500)B(7500,3000)R(34000,16000)WP(15635,16450)L(40000000,50) 
in command line
