### ISSUE TITLE
Option to disable chapters when demuxing MKV

### ISSUE THREAD

**Issue by dustsigns** [stax76/staxrip#267]
When demuxing MKV files using default settings, one can select which audio and subtitle tracks to extract. However, a file named chapters.xml is always created as well and automatically added to the container. It is possible to remove it via the container options, but it would be nice to have an option for this so that it can be decided for each template (or globally) whether to automatically add chapter information. When processing many files with a template, it is a tedious task to remove all chapters manually.

**Comment by stax76** [comment]
It should be possible to disable it globally at: Main Menu > Tools > Settings > Demuxing > mkvextract > Edit > Chapters Demuxing

If staxrip is configured to show the demuxing GUI it can be disabled there manually, disabling it per template when demuxing is automated is not supported. It's probably possible via powershell extension, if you have questions about it please post here:

https://github.com/stax76/staxrip/issues/200

**Comment by dustsigns** [comment]
Ah, the new version has an option for this. Nice. Thanks for the fast reply.

**Comment by dustsigns** [comment]
@stax76: Unfortunately, it seems that the option in the new version is ignored. Even when I uncheck "Chapters demuxing" in the settings (as you suggested), a chapters.xml file is demuxed and automatically added in the container options. There is even a line in the log file stating:

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>        Demux ogg chapters using mkvextract 13.0.0 x64
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

This is a bit odd considering that the input file is an MKV. The audio and video demuxing above it states

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>            Demux mkv using mkvextract 13.0.0 x64
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

The settings look like this:

![unbenannt](https://user-images.githubusercontent.com/11800082/29584558-7409d120-8784-11e7-81e5-9057f43f0e10.png)

**Comment by stax76** [comment]
Only happens when the demuxing GUI is disabled, I'll investigate it.

**Comment by stax76** [comment]
It should be fixed in the next build.
