### ISSUE TITLE
only last Subtitle used?

### ISSUE THREAD

**Issue by JoergWausW** [stax76/staxrip#268]
[Version 1.6.0.0]
I have a DVD with several subtitle tracks.
After using VSRip I opened the MKV->Cointainer Options->Subtitles dialogue and Added the idx file.
All subtitle tracks are shown. (*)
When I mark one of them and hit "play" I get the correct result. So the idx-file has to be ok.

May be important: It is a cut track (first 30 minutes out of 3 hours)

I enabled them all and started the fun.

When I open the resulting file in VLC-Player the subtitle menu shows all subtitle tracks, but each one is the same: the last one in the list of enabled subtitles in the list (*). e.g. I enable french and dutch. No matter which subtitle track I choose, I get dutch subtitles, because dutch is lower in the list (I tested with other selections).

I also tried different settings like preferred language -> all (I found that in a previous issue) - it didn't help.

So here the results of my investigation, reduced to the important stuff:

**********************
***log file extract***
**********************
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
              Muxing using mkvmerge 13.0.0 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

command line ends like this:

--subtitle-tracks 0 
--forced-track 0:0 
--default-track 0:0 
--language 0:swe "E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0 ID0_cut_.idx" 
--subtitle-tracks 0 
--forced-track 0:0 
--default-track 0:0 
--language 0:eng "E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0 ID0_cut_.idx" 
--global-tags E:\VIDEO_TS\VTS_01_1_temp\Test7_tags.xml 
--ui-language en

(...)
output shows:
(...)

mkvmerge v13.0.0 ('The Juggler') 64bit
...
'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0 ID0_cut_.idx' track 0: Using the output module for the format 'VobSub'.
'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0 ID0_cut_.idx' track 0: Using the output module for the format 'VobSub'.

**************************
***end log file extract***
**************************

I guess the track number is lost somewhere.
Before, this happened:

**********************
***log file extract***
**********************
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
           Cut subtitle using mkvmerge 13.0.0 x64
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

"C:\Programme Portable\StaxRip\Apps\MKVToolNix\mkvmerge.exe" 
-o "E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0 ID0_cut_sub.mkv" E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0_cut_mm.avi 
--subtitle-tracks 8 E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0.idx 
--split parts-frames:0-63696 
--ui-language en

mkvmerge v13.0.0 ('The Juggler') 64bit
'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0_cut_mm.avi': Using the demultiplexer for the format 'AVI'.
'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0.idx': Using the demultiplexer for the format 'VobSub'.
'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0_cut_mm.avi' track 0: Using the output module for the format 'VfW compatible video'.
'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0.idx' track 8: Using the output module for the format 'VobSub'.
The file 'E:\VIDEO_TS\VTS_01_1_temp\VTS_01_0 ID0_cut_sub.mkv' has been opened for writing.
The cue entries (the index) are being written...
Multiplexing took 1 second.
**************************
***end log file extract***
**************************

this was done for each subtitle track.

2 Problems:
1) the cut file is overwritten, this way only the last track survives in that "%0_0.idx"-file
2) the muxing command is only looking for the same file for each subtitle track

**Comment by stax76** [comment]
I'll investigate it but before I have to work on a issue that causes the main dialog being missing after demuxing.

**Comment by stax76** [comment]
It should be fixed in the next build. Since you are probably a PAL user I cannot recommend your workflow, I guarantee you that you will get async issues with certain DVDs. It's better to use MakeMKV, that workflow is not affected by this bug and is generally better for both DVD and Blu-ray.

**Comment by JoergWausW** [comment]
I'm still just starting...
I guess you are referring to mkvmerge. I didn't change anything about the mkv-tools and left the defaults set by StaxRip untouched. I'll have to look into it how to change that when I have more time. Couldn't find anything obvious in <30 s.

**Comment by stax76** [comment]
With vsrip you get one idx containing multiple streams, when you rip with MakeMKV to MKV which staxrip demuxes with mkvextract you get multiple single idx files, in that case you are not using vsrip and dgmpgdec. The MakeMKV route is generally recommended over any other route, in particularly with PAL where you don't need field processing with dgdecode.

**Comment by JoergWausW** [comment]
After installing MakeMKV I understood what you are talking about. Thanks.
