### ISSUE TITLE
Allow resizable 'Merge' dialog window

### ISSUE THREAD

**Issue by samkatakouzinos** [stax76/staxrip#271]
When choosing Source, Merge Files the Merge dialog window appears. 
This is not a resizable window. 

Requests:
1. Allow this window to resize so that I can see full file paths. 
2. And/Or allow tooltips when hovering over rows to display full file paths.

Request 1, is enough.   
Request 2, is nice touch.

**Comment by stax76** [comment]
Thanks for the feedback, it should be better in the build from today:

https://forum.doom9.org/showthread.php?p=1815695#post1815695

**Comment by samkatakouzinos** [comment]
Thank you.
