### ISSUE TITLE
Crash when hitting Play button in subtitles tab

### ISSUE THREAD

**Issue by dustsigns** [stax76/staxrip#273]
When adding a subtitle in the "Subtitles" tab in the "Container" window, selecting it and deleting it again via the "Remove" button, the "Play" button stays enabled. When clicking on it (after deletion), StaxRip crashes with a NullReferenceException.

This issue also occurs when subtitles are automatically added. In this case, it is not necessary to add another subtitle - just remove all the existing ones as described above, click the "Play" button and observe a NullReferenceException.

The log shows the following stacktrace:

> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
>                          Exception
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> 
> System.NullReferenceException: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
>    bei StaxRip.SubtitleControl.bnPlay_Click() in D:\Projekte\VS\VB\StaxRip\Controls\SubtitleControl.vb:Zeile 425.
>    bei StaxRip.SubtitleControl._Lambda$__R41-1(Object a0, EventArgs a1)
>    bei System.Windows.Forms.Control.OnClick(EventArgs e)
>    bei System.Windows.Forms.Button.OnClick(EventArgs e)
>    bei StaxRip.UI.ButtonEx.OnClick(EventArgs e) in D:\Projekte\VS\VB\StaxRip\UI\Controls\Controls.vb:Zeile 1080.
>    bei System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
>    bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
>    bei System.Windows.Forms.Control.WndProc(Message& m)
>    bei System.Windows.Forms.ButtonBase.WndProc(Message& m)
>    bei System.Windows.Forms.Button.WndProc(Message& m)
>    bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
>

**Comment by stax76** [comment]
Thanks for reporting, it should be fixed in the next build.
