### ISSUE TITLE
2-pass options

### ISSUE THREAD

**Issue by PeterStaxrip** [stax76/staxrip#275]
Hi,

Wondering where these have gone on 1.6.  Seems to be no method of targeting output size or bitrate in this version.

Thanks

**Comment by stax76** [comment]
For most codecs there is a Mode option in the Basic tab.

**Comment by PeterStaxrip** [comment]
Thanks,

Sorry for opening this, I realize these merely disappeared from the main drop down menu.  I'm wondering is it easy to copy over the menu items from earlier versions.

Is there any method of batch encoding at a constant bitrate?  What it tends to do is recompute to the target size each time in the two box dialogue for the bitrate/target size.

**Comment by stax76** [comment]
> Sorry for opening this, I realize these merely disappeared from the main drop down menu. I'm wondering is it easy to copy over the menu items from earlier versions.

No, edit current profiles or create new profiles or use constant rate factor, you can customize almost everything.

> Is there any method of batch encoding at a constant bitrate? What it tends to do is recompute to the target size each time in the two box dialogue for the bitrate/target size.

It remembers what was changed last, bitrate or file size so yes, it's possible.

**Comment by stax76** [comment]
I wrote something about it here:

https://github.com/stax76/staxrip/wiki/Frequently-Asked-Questions

**Comment by PeterStaxrip** [comment]
Thanks stax.  Really quick feedback.  The best encoder front end ever.
