### ISSUE TITLE
Is OneDrive link valid?

### ISSUE THREAD

**Issue by samkatakouzinos** [stax76/staxrip#276]
In https://github.com/stax76/staxrip/blob/master/md/changelog.md

the link https://onedrive.live.com/redir?resid=604D4754F64B0ABC!4140&authkey=!ANUm9V3vTPmEFNI&ithint=folder%2c7z

ends up at https://onedrive.live.com/?cid=604d4754f64b0abc&id=604D4754F64B0ABC%214140&authkey=%21ANUm9V3vTPmEFNI

with the following message for me:
"This item might not exist or is no longer available."

**Comment by stax76** [comment]
Here it works.

**Comment by samkatakouzinos** [comment]
@stax76 may you try opening it in an incognito window please? 
I feel that your authentication and credentials allows you to see it.

**Comment by Helenerineium** [comment]
same here, but since I use google drive, this is not a problem for me

**Comment by stax76** [comment]
With firefox incognito mode it asks for login here. I think google drive don't require login.

**Comment by samkatakouzinos** [comment]
Both Google and Microsoft drive solutions offer ability to share a folder to the public with read-only permission. 

I assert your Google Drive is working correctly as I use it for beta downloads. Even added it to my Google Drive account as a 'Shared with me'. 

Your OneDrive folder that contains beta downloads may not be setup to share publicly with read-only permissions. 

Here is an example OneDrive folder shared publicly with read-only permissions:
![Example OneDrive sharing settings](https://lh3.googleusercontent.com/-VJQ6YCp9-sw/WZ4ewbTxY0I/AAAAAAACEA4/bEvDgXlqon8Ad6xsicXbIjgKyp8hhacHQCHMYCw/s0/chrome_2017-08-24_10-33-03.png)

The above was initiated with the 'Share' button in that row above (New, Upload, Share, Download, Move to, Copy to). 

Please review your share settings. 
If there is a need for a new OneDrive link that works then so be it. 
I'd find that acceptable.

**Comment by stax76** [comment]
I'm not very good and need to improve in everything web related. I've replaced it now, thanks for reporting, this is the new link:

https://1drv.ms/f/s!ArwKS_ZUR01goCzIRemxotXY_zz-

**Comment by samkatakouzinos** [comment]
It works!  Please update https://github.com/stax76/staxrip/blob/master/md/changelog.md and 
- replace https://onedrive.live.com/redir?resid=604D4754F64B0ABC!4140&authkey=!ANUm9V3vTPmEFNI&ithint=folder%2c7z 
- with https://1drv.ms/f/s!ArwKS_ZUR01goCzIRemxotXY_zz- 

P.S. You just became very good with web related :)
