### ISSUE TITLE
Default Temp Directory is not automatically applied correctly.

### ISSUE THREAD

**Issue by OnbekendHH** [stax76/staxrip#277]
I've setup to use a specific Temp Dir vor the Temp files, yet when ripping a bluray eac3to defaults to another directory. (See ScreenShot).
Would it be possible to correct this error?
Thanks!
![2017-08-26 09_52_02-eac3to](https://user-images.githubusercontent.com/7472445/29739737-3535af64-8a45-11e7-83dc-0ab70d27ac74.png)

**Comment by stax76** [comment]
I can probably improve it.

**Comment by stax76** [comment]
Is the last test build working better?

**Comment by OnbekendHH** [comment]
Hey, man... thanks a lot for taking on this issue! :-)
How can I download the latest "nightly"/beta build?

**Comment by stax76** [comment]
You're welcome. Here is the link:

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Comment by OnbekendHH** [comment]
Yes!... Seems to be working very nicely! Thx!
