### ISSUE TITLE
VCEEnc `The filename, directory name, or volume label syntax is incorrect`

### ISSUE THREAD

**Issue by jkldgoefgkljefogeg** [stax76/staxrip#279]
> Error Video encoding using VCEEnc 3.06 x64
> 
> Video encoding using VCEEnc 3.06 x64 failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 
> 
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> Video encoding using VCEEnc 3.06 x64
> -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
> 
> cmd.exe /S /C call "C:\enctools\StaxRip-x64-1.6\Apps\VCEEnc\VCEEncC64.exe --codec hevc --level 5.1 --vbaq --motion-est full-pel --pre-analysis auto --vbr 10000 -i "D:\AMD Relive\2017.07.31-22.11_temp\2017.07.31-22.11.avs" -o "D:\AMD Relive\2017.07.31-22.11_temp\2017.07.31-22.11_out.hevc""
> 
> The filename, directory name, or volume label syntax is incorrect.
> 
> 
> 
> StaxRip.ErrorAbortException: Video encoding using VCEEnc 3.06 x64 failed with exit code: 1 (0x1)
> 
> The exit code might be a system error code: STATUS_WAIT_1
> 
> The exit code might be a system error code: Incorrect function.
> 

The path is not properly escaped? Report from https://forum.doom9.org/showthread.php?p=1814040#post1814040

**Comment by jkldgoefgkljefogeg** [comment]
It works correctly when VCEEncC64.exe, input and output path are all double quoted.  Windows 10 x64

**Comment by stax76** [comment]
Which staxrip build is it? You can find the latest here:

https://github.com/stax76/staxrip/blob/master/md/changelog.md

**Comment by jkldgoefgkljefogeg** [comment]
It was on 1.6-stable-x64

**Comment by stax76** [comment]
There was a fix:

1.6.0.2 unstable test build

    fix: incorrect command line generated for VCEEnc

**Comment by jkldgoefgkljefogeg** [comment]
Indeed this is fixed in 1.6.1.2 unstable test build. Sorry for the noise
