### ISSUE TITLE
Error AviSynth 

### ISSUE THREAD

**Issue by fmohican** [stax76/staxrip#281]
I don't know what i doing wrong.

That happens when i try to encode with your new version ( 1.6.7 )
https://pastebin.com/xiDqsEPZ

When i try to use "Preview"
![untitled](https://user-images.githubusercontent.com/8583317/30165608-4d0529fa-93e9-11e7-8868-de8a3d012c32.png)

Code Editor :
![code editor](https://user-images.githubusercontent.com/8583317/30165637-6b082128-93e9-11e7-806b-a16bd3e69ffc.png)

All Other files
[debug.zip](https://github.com/stax76/staxrip/files/1284797/debug.zip)

**Comment by stax76** [comment]
Does the script open in VirtualDub x64?

**Comment by fmohican** [comment]
I don't know
That script work on previous version (StaxRip x64 1.3.4.0 Stable Final Release)

**Comment by stax76** [comment]
Try to open it with VirtualDub x64 and with mpv.net x64, right-click the filters and choose 'Play' to play it with mpv.net (mpv.net is only included in the newest test build).

**Comment by fmohican** [comment]
Isn't work.
![untitled](https://user-images.githubusercontent.com/8583317/30169649-b0183972-93f5-11e7-859f-fb2fb0ae7624.jpg)
and on MPV.Net display a black screen at last second's

**Comment by stax76** [comment]
Then it's a avisynth problem, to get help with avisynth doom9 is the best address.
