### ISSUE TITLE
"ExecuteScriptFile" in custom menu does not accept macros in path

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#283]
Hello Stax,
Trying to use a custom menu with "executeScriptFile" and a macro for path doesn't seems to work.

Using the file browser to select the path of the scrip manually or entering full path location of the ps1 file works perfectly but if i try to use a macro for the path i get an error message telling me the file is missing when i then try to use the custom menu.

Custom menu : 
![ICustom menut](https://img11.hostingpics.net/pics/18527120170911102420.png)
Tried this for path : 
%script_dir%WaterMark.ps1
and this 
"%script_dir%WaterMark.ps1"

The returned path by this macro is correct and leads to the correct file ( tested in "preview code" ), the hint at the bottom says we can use macros for path, so unless i am doing something wrong it doesn't work as expected here.

Thanks a lot.

**Comment by stax76** [comment]
Hi Yanak,
it should work in the next build.

**Comment by jalba69** [comment]
Thanks a lot Stax.

**Comment by jalba69** [comment]
All working nice in last versions, thanks again Stax76.
_Closing it._
