### ISSUE TITLE
selecting nvidia h265 hw decoder crops video twice

### ISSUE THREAD

**Issue by douchebanner** [stax76/staxrip#284]
hi, so i got this 4k video, i crop it, resize it and if i select the hw decoder instead of avisynth the resulting video gets cropped again. if i select avisynth the video gets the cropping i had selected.

Input Info     avcuvid: VP9, 3840x2160, 25/1 fps
Vpp Filters    crop: 656,368,656,370/cspconv(nv12 -> yv12(16bit))
resize(spline36): 1216x684 -> 1920x1080
cspconv(yv12(16bit) -> p010)

that pc has an old cpu so thats why hw decoding would be interesting to me

i attached the log below, thanks

[hw decoder test_staxrip.log.txt](https://github.com/stax76/staxrip/files/1292511/hw.decoder.test_staxrip.log.txt)

**Comment by stax76** [comment]
Hi,
I understand and have reported it:

https://github.com/rigaya/NVEnc/issues/10#issuecomment-328562385

**Comment by stax76** [comment]
It should be fixed in the newest build.

https://github.com/rigaya/NVEnc/issues/10#issuecomment-330196097

https://github.com/stax76/staxrip/blob/master/md/changelog.md
