### ISSUE TITLE
TS Stream (.srt) cutting broken sinds 1.6.1.9

### ISSUE THREAD

**Issue by AdPatat** [stax76/staxrip#291]
The cutting of the sound and video is OKÉ but the cutting of the subsstream (srt) not.
In ver. 1.6.1.7 was everything OKÉ.
GrTz AdPatat

PS If you want i have a right (1.6.1.7) log and a wrong (1.6.1.9) logfile.... Where an i upload these?

**Comment by stax76** [comment]
You can upload log files to paste bin (enable auto expire). I made a test and everything was fine, did you cut in the middle of a subtitle or between? If you can upload both log file and sample file I would try to reproduce it and report it to the mkvmerge author, mkvmerge is the tool staxrip uses for cutting.

**Comment by AdPatat** [comment]
Hi Stax,
After stream cleaning with TSDoctor, I cut at the begin, the end and the adverts of course, the 2 versions of staxrip use the same mkvmerge, thats why i'll come to you ;-). In ver. 1.6.1.7 and before was everything OKÉ.
Here the logs.
Safe House - S02E03 - Aflevering 3_bad https://pastebin.com/peCuaKLf
Safe House - S02E03 - Aflevering 3_good https://pastebin.com/eakC0Dr1
GrTz AdPatat

**Comment by stax76** [comment]
According to the log file subtitle cutting is not happening but there are also no subs in the final muxing, in fact 'srt' isn't found in the entire log file. Are you sure you have added subs and enabled subs in the container options dialog?

Unrelated but out of interest, how do you get SRT subs from TS dvb subs?

**Comment by AdPatat** [comment]
> Unrelated but out of interest, how do you get SRT subs from TS dvb subs?
When you are "cleaning and raw cutting" the TS dvb steam with TSDoctor you get the .srt stream [888] out of it and of course the fixed TS stream.
Both rips are made with the same files (.ts and .srt)

**Comment by stax76** [comment]
Can you confirm that there was/is a active SRT file listed in the Subtitles tab of the container options dialog?

**Comment by AdPatat** [comment]
Yes of course, but... i've installed StaxRip 1.7.0.0 for now, made a recording from ITV and its working as always.
Thanks for your time and effort Stax.
GrTz AdPatat
