### ISSUE TITLE
"Assistant" in project options issues.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#293]
Hi Stax, 

testing a bit and in 1.7.0.0 the "assistant" we can find in " project options"  settings seems to have some issues : 

- Remind to set filters and remind to cut seems to work nicely.

- Remind to crop seems to have no effect, no message or warning.

- Remind to do a compressibility check seems to have no effect either.

- Disabling " remind to not oversize" seems to have no effect.
Loading a file and upscaling it leaves the warning message at the bottom of the program and the fields for size with orange color background while this option is disabled

Possibly also a problem with remind about aspect ratio not getting disabled when option is disabled orange background still but harder to test this one, only changed aspects manually ) 

Thanks a lot as always.

**Comment by stax76** [comment]
Hi Yanak,

> Remind to crop seems to have no effect, no message or warning.

it needs the crop filter enabled but I removed this restriction (next build).

> Remind to do a compressibility check seems to have no effect either.

it should work in two pass mode.

> Disabling " remind to not oversize" seems to have no effect.

the implementation was missing so I removed it (next build).

**Comment by jalba69** [comment]
Thanks Stax, 
I understand now, remind to crop is a bit useless indeed is it needs a crop already done to remind us about cropping :p 

Compressibility check i forgot it was for 2 passes yes, sorry about that, I'll have to recheck some of my settings and try again in 2 passes mode.

Had an issue yesterday with staxrip 1.7.0.0 on launch, telling me he could not access a file, did not payed much attention to the error displayed and just closed it...
On the restart i discovered that it deleted all my templates and replaced them with the default ones, all custom ones gone... hopefully i had a not too old backup of my Staxrip settings folder, no log files or anything for this sadly. 
If it ever happens again I'll pay more attention and report it... loosing all my custom templates had been a pain for me, for now I will just back them up more often :p 

BTW : AVSMeter 2.6.6 is out.

Thanks a lot

**Comment by stax76** [comment]
I did a quick code review but I couldn't find anything that would delete the templates folder.

**Comment by jalba69** [comment]
Trust me it happened, 
The error message was about a file somehow used by another program and locked somehow, not sure at 100% but i think it was "SettingsV2.dat". Nor can't remember exactly if i also restored this file from the backup folder after copying and renaming it in combination with the templates, probably did... it was just after the morning coffee and I was not really wide awaken so it's hard to remember each steps...

I have regular backups so it was not a big deal anyways.

**Comment by jalba69** [comment]
Managed to get it happen again : 

![pic](https://img15.hostingpics.net/pics/81276920171012120651.png)
The French part says The process could not access the file settings v2.dat because the file was already used by another process .
No log file created.

Seems like it happened with a bit brutal double click on the main .exe combined with my mouse having little troubles lately and doing double clicks instead of single clicks once in a while... 
Seems like it ended up in a double click made twice quickly, launching the program twice almost at the same time, might be possible to reproduce using a macro to launch Staxrip twice quickly.

While the error message is still up it's possible to copy the settings folder to restore it later, or copy the entire Staxrip folder to back it up, once error message window is closed the settings return to default and custom templates get deleted and replaced by default ones.

Since it's a end user problem i don't think anything is needed to be done, or maybe try to create a backup of the potentially replaced files, copy all templates and settingsv2.dat to the backup folder, if the files are accessible and not locked, in this case just skip what is locked and restore default settings of course, i don't know, seems like it's something that won't happen to many users so probably jut need to be careful.

Thank you.

**Comment by jalba69** [comment]
PS : Now that the warning about remind to not oversize is gone we still have the notifications when we upscale : 

![](https://img15.hostingpics.net/pics/91357520171012152638.png)

In orange or the line at the bottom of the program, not sure if it is possible to disable this or not.

**Comment by stax76** [comment]
I added error handling for this:

- fix: for the rare case of the settings failing to load staxrip will offer the options Retry, Reset, Exit

I removed the assistant messages for upscaling and changed the message for the aspect ratio error, new message is:

Use the resize slider to correct the aspect ratio error or click next to encode anamorphic.

**Comment by jalba69** [comment]
Thanks for the fix, will prevent unexpected losses working like this.

The assistant message is a bit annoying when you do upscaling and adds a couple more clicks on the "next" button to pass them but i can live with that i guess :p

Thanks a lot for all Stax.
