### ISSUE TITLE
Problem with BDSup2Sub and long filenames

### ISSUE THREAD

**Issue by hakai** [stax76/staxrip#294]
~~Conversion of sup-Files to sub causes an exception, if the Filename of the (extracted) sup-file contains a minus sign, e.g. _Star Wars - Episode....sup_~~ (Hope you don't mind the german output on the exception)

System.InvalidOperationException: Diesem Objekt ist kein Prozess zugeordnet.
   bei System.Diagnostics.Process.EnsureState(State state)
   bei System.Diagnostics.Process.get_HasExited()
   bei StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:Zeile 283.
   bei StaxRip.MainForm.ConvertBluRaySubtitles() in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:Zeile 2351.
   bei StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:Zeile 2151.

**Comment by hakai** [comment]
After running a few more tests, the problem was not related to the minus sign itself. It was just a coincidence that removing it made the filename short enough to not trigger the bug.

Instead it is caused by the filename with extension being longer than 51 characters. It is **not** related to the length of the path, just the filename. The above exception still applies.

Running the program call from a DosPrompt works without error btw, even for longer filenames.

**Comment by stax76** [comment]
It should be fixed in the newest build:

https://github.com/stax76/staxrip/blob/master/md/changelog.md
