### ISSUE TITLE
[Suggestions] Continue on error

### ISSUE THREAD

**Issue by Symbai** [stax76/staxrip#298]
I really like this tool because it supports nvenc but it crashes for me on 25 of 100 files and its getting annoying the program always shutdown itself when a third party has thrown an error.

Would it be possible to just log this error and continue with the other files in the job queue?
Right now I cannot leave the computer as when it thrown an error on the second file, nothing except the first file has been encoded when i come back.

**Comment by stax76** [comment]
There is some continue mechanism, some error dialogs close after 2 minutes and job processing continues. 

It might be possible to improve it but I would need samples and log files.

**Comment by Symbai** [comment]
Sample: https://mega.nz/#!V5t1ECYZ!Lvg_L0caLgbsUjNPUIcImtdZVdi3i2FWWOtRbRGMCBY
Template: 
https://mega.nz/#!Ux1THSTD!zf5YGW6m498NHImudFpLBucGYjP7GtxqpCNRPuytnaI

Log file in #296

**Comment by stax76** [comment]
I've examined the code, continue is not something that can be changed easily, the code is very complex, much likely it was working in the past before all processing was rewritten for parallel processing.

**Comment by Symbai** [comment]
Aww :( Thanks for taking a look on it though
