### ISSUE TITLE
add some features

### ISSUE THREAD

**Issue by ahmedflix25** [stax76/staxrip#3]
add support for chapters and embedded subtitles
make it possible to delete temporary files save as default i have to remark it for each job
option to auto add and hardcode subtitles that have video same name

**Comment by stax76** [comment]
I can improve things but you'll have to write much more and a little bit cleaner.

**Comment by ahmedflix25** [comment]
i have to check this every job because app doesn't save the setting 
![screenshot 36](https://cloud.githubusercontent.com/assets/7858946/8414415/1f07e48e-1e98-11e5-9248-56edb9a41bae.png)

There is no chapters support like that one if there is a video with one and i encode it with staxrip 
![screenshot 39](https://cloud.githubusercontent.com/assets/7858946/8414669/e1965ec6-1e99-11e5-977d-99780cb44258.png)
staxrip removes chapters

if there is a mkv or mp4 with embedded subtitle i can't hardcode it 
From Mediainfo
> Audio
> ID                          : 2
> Format                      : AAC
> Format/Info                 : Advanced Audio Codec
> Format profile              : HE-AAC / LC
> Codec ID                    : A_AAC
> Duration                    : 23mn 42s
> Channel(s)                  : 2 channels
> Channel positions           : Front: L R
> Sampling rate               : 44.1 KHz / 22.05 KHz
> Compression mode            : Lossy
> Delay relative to video     : 33ms
> Language                    : Japanese
> Default                     : Yes
> Forced                      : No
> 
> Text #1
> ID                          : 3
> Format                      : ASS
> Codec ID                    : S_TEXT/ASS
> Codec ID/Info               : Advanced Sub Station Alpha
> Compression mode            : Lossless
> Language                    : Arabic
> Default                     : Yes
> Forced                      : No
> 
> Text #2
> ID                          : 4
> Format                      : ASS
> Codec ID                    : S_TEXT/ASS
> Codec ID/Info               : Advanced Sub Station Alpha
> Compression mode            : Lossless
> Language                    : English
> Default                     : No
> Forced                      : Yes
the app must add it atomically like audio channels also subs with the same video name at the same folder
that error comes out when i try to add a sub from the mkv
![screenshot 37](https://cloud.githubusercontent.com/assets/7858946/8414696/16ca3ce8-1e9a-11e5-8dd1-5e7b5cd9d53b.png)
![screenshot 38](https://cloud.githubusercontent.com/assets/7858946/8414694/149eb4b2-1e9a-11e5-9187-92e7715b7de8.png)

more support for windows 32bit please

**Comment by stax76** [comment]
> i have to check this every job because app doesn't save the settings

StaxRip uses projects for jobs and templates, on startup StaxRip loads a default template which you can customize, go to: Project > Safe As Template

> There is no chapters support like that one if there is a video with one and i encode it with staxrip 

If you rip with MakeMKV StaxRip can extract and include the chapter file, there is a option for extracting chapters in the demuxing settings of StaxRip 32-Bit, in the muxing dialog there is a option to define the path to a chapter file. A editor is not included but there should be third party editors available.

> if there is a mkv or mp4 with embedded subtitle i can't hardcode it

There is a option at Tools/Advanced/Hardcoded Subtitle, it supports TextSub/VobSub so only certain subtitle file formats, no PGS from Blu-ray or MKV or MP4. StaxRip can demux the subtitles, the old StaxRip version you use should have a option to demux in the settings.

Is there a particular reason you don't use StaxRip x64? 32-Bit has been discontinued a long time ago and a huge amount of progress has been made meanwhile. StaxRip supports AviSynth+ x64 and VapourSynth x64, a lot plugins are included and many more are available. 32-Bit support definitively won't come back, it's too much work for too little benefit.

If you create a issue on the github issue tracker then please use it not for more then one issue. You can also use the support thread at videohelp if you like.
