### ISSUE TITLE
FixedBitrate NOT FIXED,is a BUG?

### ISSUE THREAD

**Issue by Yuanuo** [stax76/staxrip#30]
I need, need to x264 code and fixed code rate of 600kbps Mp4, but even if I opened fixed rate function, the result is not fixed, and sometimes 740kbps, or 800kbps, and so on, so I DEBUG the code, the Encode method of this class is found in the BatchAudioProfile there seems to be some problems:

Public Class BatchAudioProfile
    Inherits AudioProfile
...................
    Public Overrides Sub Encode()
...................
            If g.WasFileJustWritten(targetPath) Then
                File = targetPath
                Bitrate = Calc.GetBitrateFromFile(File, p.TargetSeconds)

**//*This line always evaluates a value change, rather I specify a fixed bit rate*.**
                **p.VideoBitrate = CInt(Calc.GetTotalBitrate - Calc.GetAudioBitrate())**

**//*Whether it should be changed to*:**
**p.VideoBitrate = If(p.FixedBitrate > 0, p.FixedBitrate, CInt(Calc.GetTotalBitrate - Calc.GetAudioBitrate()))**

                If Not p.VideoEncoder.QualityMode Then
                    Log.WriteLine("Video Bitrate: " + bitrateBefore.ToString() + " -> " + p.VideoBitrate.ToString)
                End If

                Log.WriteLine(MediaInfo.GetSummary(File))
            Else
....

Also, in NullAudioProfile Encode method with the same code, fix, don't forget. Thank you!

**Comment by stax76** [comment]
Hello, thanks for finding the according code, it's now fixed (locally).
