### ISSUE TITLE
H.265/HEVC isn't supported by the graphics card

### ISSUE THREAD

**Issue by Symbai** [stax76/staxrip#300]
Throws error saying its not supported but the graphics card supports it. 
Happens when another program in background uses cuda/nvenc (in my case each time with Adobe Premiere Pro CC 2017)

**Comment by Brainiarc7** [comment]
What's the make of your GPU?

Consumer GPUS are limited to 2 simultaneous NVENC sessions.

**Comment by Symbai** [comment]
GTX 1080 (yes consumer). However only Staxrip (once instance) and adobe premiere was running but maybe adobe uses more than 1. Still the error message is confusing in this case

**Comment by Brainiarc7** [comment]
Yes, more than 2 NVENC sessions trigger the error.

**Comment by Symbai** [comment]
Ok thanks
