### ISSUE TITLE
"Process Event Command" Odd behavior

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#302]
Hey Stax, 
found something odd with Process Event Command, on a clean default profile follow those steps : 

- Launch Staxrip with default parameters, default template.
- Go to tools > Advanced > Process Event Command
- On the Event Commands manager click on + to Add a New Event. 
- Don't touch name "???" and "Event Project Loaded" , leave those 2 as they are by default. 
- For command select "DynamicMenuItem"  then "MuxerProfiles" for the ID. Click Ok to save and exit this menu

- Go to Project > Save as template and save current (default startup) template then exit Staxrip.
- Open staxrip with the default template we just saved. Load an input video file in it, and check logs you will see this : 
```
--------------------- Process Event Command '???' ---------------------
Event: After Project Loaded
Command: DynamicMenuItem
Parameter ID: MuxerProfiles
```
- Now go to tools > Advanced > Process Event Command and delete the event command we just created. Close Staxrip , launch it again and input a video file .
- Check logs, the process event command is still there : 
```
--------------------- Process Event Command '???' ---------------------
Event: After Project Loaded
Command: DynamicMenuItem
Parameter ID: MuxerProfiles
```

No way to get rid of this now...
Creating again the same event command having the same default name and commands then deleting it and saving the template before existing program will produce 2 of those entries in the log file  the next times you will load some input files in this template and so on .

Not sure what is going on with this but i doubt it is supposed to work like this. ^^

Thanks a lot Stax.

**Comment by stax76** [comment]
The log is part of the project/template/job structure, I changed it to log event commands only if the source file is not empty.

**Comment by jalba69** [comment]
I'm not sure if either i do not understand correctly the answer or maybe you misunderstood the report.

The thing is that the event command example i gave still remains active and seems to be executed by Staxrip ( and reported in the log ) even once the event command itself it is deleted / removed from the events commands list.

I will try post some pics later if needed in case it's not clear.

**Comment by stax76** [comment]
No I don't believe it's active/executed, it's just the log entry saved in the settings structure.

**Comment by jalba69** [comment]
You know better than me , just wanted to be sure something was not overlooked.
I'll test it on the next version after the change for log display.

Thanks a lot Stax.

**Comment by jalba69** [comment]
Tested in last 1.7.0.2, all seems good now, 
Thanks again.
