### ISSUE TITLE
"VSFilterMod.dll not found" error message, but it's present!

### ISSUE THREAD

**Issue by luffy95** [stax76/staxrip#303]
I am using windows 7 64 bit and when I add a subtitle I get this error message:
![staxrip_2017-10-05_15-41-11](https://user-images.githubusercontent.com/12600234/31233089-a6df6c5a-a9e3-11e7-82e8-1d8d81bb6200.png)

`Cannot load file 'C:/Disck/Films/StaxRip-x64-1.7.0.0-stable/Apps/Plugins/both/VSFilterMod/VSFilterMod.dll'. Platform returned code 126:
‏The specified module could not be found.

(C:\Disck\Films\Lost.S01E01.108..._temp\Lost.S01E01.1080p.BluRay-[My-Film]_new.avs, line 2)`

**Comment by stax76** [comment]
Here it's fine, please post the script:

Filters > Preview Code

And please post the output from:

Main Menu > Apps > AVSMeter

Do this twice with and without opened source file.

**Comment by luffy95** [comment]
Thanks, but I installed Microsoft Visual C++ 2015 Redistributable (x64) - 14.0.24215 (as it was suggested by someone in a german forum) and it worked.
everything is normal.

**Comment by stax76** [comment]
Next build will detect this, since it depends on MSVCP140.dll staxrip will ask for VC++ 2017 and not VC++ 2015
