### ISSUE TITLE
Suggestion : add tooltip showing icon names used in the menu editor

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#306]
Hello Stax, 
With latest 1.7.0.2 build the menus were reset, I have a load of custom menus, will take a bit of time but i will copy them from previous build and add them again, only really painful thing is that i had set custom icons for the menus i created and also for almost all the default ones of Staxrip, or replaced some existing ones too.

Sadly this is a very long process to do all this again especially since i need to find out again those icons i used previously and it ain't easy without knowing them names... so if i may i will suggest that we have a little tooltip in the menu editor showing the icon name when we pass the mouse over it, a bit like here :

![example](https://img15.hostingpics.net/pics/77333020171010101000cr.jpg)

Not a big deal as it won't happen a lot to do all over again but will be nice, of course if it ain't taking a lot of efforts and too much time to implement this .

Thank you Stax.

**Comment by stax76** [comment]
I remember I wanted to show it in a label but something didn't work as expected. Now I tried again and it seem to work so it's a little bit strange. Build should be online in a minute.

**Comment by jalba69** [comment]
Fantastic, will serve for the next times, spent quite some time to rebuild my menus and restore most of my icons, this will be so helpful the next time i'll have to do a similar thing or restart on a new settings.

You even added "fa_" prefix for font awesome ones, just perfect :)

Thank you very much.
