### ISSUE TITLE
Error when processing Job queue 1.7.0.2 - 1.7.0.3

### ISSUE THREAD

**Issue by Fencat** [stax76/staxrip#307]
Tried updating from the stable 1.7.0.0 but getting the following error on 1.7.0.2 - 1.7.03 when starting a job in the queue. Tested with completely default settings.
Had to completely reinstall staxrip to get rid of this error, the normal just copy old version back did not work, had to wipe settings or I would get same error on any version. 
After some trial and error I have found 1.7.0.0 and 1.7.0.1 works fine but 1.7.0.2 and 3 introduce this error and only way to get back is reinstall with wipe of settings.

Crash seems to happen at the audio encode stage if that helps.
 
FileLoadException (1.7.0.3)

Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)

System.IO.FileLoadException: Could not load file or assembly 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at StaxRip.Scripting.RunPowershell(String code)
   at StaxRip.GlobalCommands.ExecutePowerShellScript(String scriptCode) in D:\Projekte\VS\VB\StaxRip\General\GlobalCommands.vb:line 274
   at StaxRip.GlobalCommands.ExecuteScriptFile(String filepath) in D:\Projekte\VS\VB\StaxRip\General\GlobalCommands.vb:line 247
   at StaxRip.GlobalClass.RaiseAppEvent(ApplicationEvent appEvent) in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 547
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isEncoding) in D:\Projekte\VS\VB\StaxRip\Forms\MainForm.vb:line 2166

**Comment by stax76** [comment]
You can try to run:

Main Menu > Tools > Scripts > Re-mux

This will tell you if powershell runs generally because that seem to the your problem, I don't see why it shouldn't run because I didn't change something in that area and nobody else reported it and I tested it on Win 7and Win 10 without noticing problems. I also don't see how it relates to settings or audio encoding. Did you install a anti virus software recently?

**Comment by Fencat** [comment]
Trying to run Re-mux crashes with the same error so that seems to be the reason..

The strange thing is this also crash on 1.6.1.6 1.7.0.0 and 1.7.0.1 where I have no problem adding the same files and running the jobs. 
On 1.7.0.2 and 1.7.0.3 any job I have tried has crashed with this error.

So well dont know why the earlier versions lets me complete the jobs and the later dont but well this is probably the underlying reason anyway. Is there anything I can do try to fix this error?

**Comment by stax76** [comment]
Try if powershell works generally:

Main Menu > Tools > Scripts > Re-mux

I don't understand why powershell is used however, did configure staxrip to run a script by event?

There is one default script handling an even, disable it by renaming it.

C:\Users\Frank\AppData\Roaming\StaxRip\Scripts\AfterSourceLoaded.ps1

**Comment by Fencat** [comment]
Try if powershell works generally:

Main Menu > Tools > Scripts > Re-mux

If I do this I get the error above. And no I have not configured any scripts that I know of atleast.
I have been testing with a completly new unziped version of Staxrip just adding a random mkv file (have tried different files) by using the batch process using the default settings that are there when you first open staxrip.

Renamed that file and it now works again.
So, what does this file do? Do I need it and if so how can I fix powershell?

**Comment by stax76** [comment]
It's not really needed, it does the following:

> Sets a deinterlace filter if the MediaInfo property 'ScanType' returns 'Interlaced'

http://staxrip.readthedocs.io/powershell.html#aftersourceloaded-ps1

There is still the questions why powershell isn't working on your system.

**Comment by Fencat** [comment]
I'll leave it disabled for now then thank you. Any ideas on what I can do to fix the problem would be most welcome anyway though. Might there be something I need to install/update?

Judging from the error message its looking for a dll called System.Management.Automation but I dont seem to have it for some reason....

Either way thank you very much for taking the time to help me!

**Comment by stax76** [comment]
The DLL that fails to load is included in the startup folder. I have no idea why it fails. Which OS version do you run? Ideal would be the newest which is Win 10 1703.

**Comment by Fencat** [comment]
I'm running Windows 7 Pro Sp1 and updating to windows 10 is not really an option at the moment so guess I need to try find an update to powershell and see if that helps.

If you are interested I'll report back if I find something but for now you can consider this solved then as we know the reason for the crash.

Thank you very much for your time and help!

**Comment by stax76** [comment]
It's probably installed otherwise staxrip would ask to install it, link is here:

https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by Fencat** [comment]
That did the trick, seems to be working as it should now. 
Dont know if it was a faulty installation or if it updated something but it helped.

Thank you again!
