### ISSUE TITLE
Add .hvc extension to the list of supported tracks for MP4box muxing please.

### ISSUE THREAD

**Issue by jalba69** [stax76/staxrip#309]
Hello Stax,

Often manually demuxing with MP4Box some MP4's as the program built-in demuxer does not allow to extract multiple videos tracks from MP4's having more than one, it extracts the first video track with .265 extension if we select the demux video option and that's all, if there is a second video track it pass invisible under the radar.

For example dumping all content of a .x265 mp4, all videos and audio tracks with this command : 
"%app:MP4Box%" -raw * "%source_file%"

I end up with the videos extracted having **.hvc** extension assigned by MP4box by default. 
Problem is when i try to remux it into a MP4 Staxrip does not let me do it : 
![](https://img15.hostingpics.net/pics/17878820171017151406.png)
I have to rename it .265 or .hevc

.hvc was added some times ago to the "Settings > Source Filters" but probably forgotten to be added here in the mp4box supported extensions for muxing.

Thank you as always :)

**Comment by stax76** [comment]
Hi, I've added it locally.

**Comment by jalba69** [comment]
Thanks a lot Stax.
