### ISSUE TITLE
StuxRip doesn't recognize 64bit Avisynth+ installation

### ISSUE THREAD

**Issue by Zwulf87** [stax76/staxrip#31]
Well,

title says everything. After indexing a movie StuxRip keeps on telling me that Avisynth+ is not installed, even after selecting the dll file manually.

OS: Win10 Education x64
StuxRip: 1.3.1.7 beta
Avisynth+: MT-r1825

Best regards

**Comment by Yuanuo** [comment]
Experienced the same problems are resolved:
1, uninstall Avisynth
2, install Avisynth+
3, and staxrip can automatically recognize.

**Comment by Zwulf87** [comment]
By now I found out that there is a much easier way. As I said, I have installed the MT version of Avisynth+. So all I had to do is to change the version numer in StuxRip into "r1825 MT x64". It is exactly the same with StuxRip 1.3.2.0pre release.

Now, the issue is solved by workaround :-).


HAND

**Comment by stax76** [comment]
Yes it detects different versions and says that you can use it by editing the date with F12.

**Comment by haytam97** [comment]
Can i download Avisynth+ manuel without steup ?
