### ISSUE TITLE
v1.3.1.7: wrong audio indizes when muxing streams only

### ISSUE THREAD

**Issue by morpheusxx** [stax76/staxrip#32]
I'm using StaxRip x64 : 1.3.1.7 to encode TV captures to h.265 by Intel Quicksync encoder. Encoding works fine, but I found an issue with muxing the result:

My source file contains 4 audio streams, I want to use the AC3 stream without reencoding. So I selected "mux only" for the AC3 stream. Unfortunately the resulting file had a MP2 audio included.

I could remux the files by taking the command line of mkvmerge from log and decreased the track number by 1:

"StaxRipX64\Apps\MKVToolNix\mkvmerge.exe" -o "F:\Capture\Batch\S2E1.mkv" --noaudio --nosubs --no-chapters --no-attachments --no-track-tags --no-global-tags --default-duration 0:50.000000fps "F:\Capture\Batch\S2E1 temp files\S2E1_out.hevc" --novideo --nosubs --no-chapters --no-attachments --no-track-tags --no-global-tags --audio-tracks **3** --language **3**:ger "F:\Capture\Batch\S2E1.ts" --ui-language en

I had to modify the bold **3** -> **2**.

It looks to me like a common difference between starting counting by 1 vs. 0:

mkvmerge -i shows:
File 'F:\Capture\Batch\S2E2.ts': container: MPEG transport stream
Track ID 0: video (MPEG-4p10/AVC/h.264)
Track ID 1: audio (MP2)
**Track ID 2: audio (AC3/EAC3)**
Track ID 3: audio (MP2)
Track ID 4: audio (MP2)

In staxrip log:
Audio #**3**
ID : 66 (0x42)
Menu ID : 1 (0x1)
Format : AC-3
Format/Info : Audio Coding 3

**Comment by stax76** [comment]
Hello, it might be a bug, if you can reproduce it please mail me the log file and if possible upload a sample clip to media fire or somewhere else.
