### ISSUE TITLE
Update f3kdb plugin

### ISSUE THREAD

**Issue by Cyberavater** [stax76/staxrip#325]
@stax76 Replace ur f3kdb plugin with this one
https://onedrive.live.com/?authkey=%21AJgT9vilE6ClKVU&cid=C1FACEB7B51DAE61&id=C1FACEB7B51DAE61%21417581&parId=root&action=locate
the one u added doesn't work check it if ya like.

**Comment by stax76** [comment]
thx for the report, it's fixed in the build from today.

https://github.com/stax76/staxrip/blob/master/changelog.md
