### ISSUE TITLE
Unknown value "smpte-st-2084" for "--transfer"

### ISSUE THREAD

**Issue by wolfhowling** [stax76/staxrip#329]
Error Video encoding using NVEnc 3.22 (1.7.0.0)

Video encoding using NVEnc 3.22 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 3.22 -------------------

C:\Users\wolfhowling\Downloads\StaxRip-x64-1.7.0.0-stable\Apps\NVEnc\NVEncC64.exe --vbrhq 15000 --codec h265 --preset quality --output-depth 10 --ref 6 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte-st-2084 -i M:\CONVERTING\gg_temp\gg.avs -o M:\CONVERTING\gg_temp\gg_out.h265

Error: Unknown value "smpte-st-2084" for "--transfer"

StaxRip.ErrorAbortException: Video encoding using NVEnc 3.22 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

------------------- Video encoding using NVEnc 3.22 -------------------

C:\Users\wolfhowling\Downloads\StaxRip-x64-1.7.0.0-stable\Apps\NVEnc\NVEncC64.exe --vbrhq 15000 --codec h265 --preset quality --output-depth 10 --ref 6 --colormatrix bt2020nc --colorprim bt2020 --transfer smpte-st-2084 -i M:\CONVERTING\gg_temp\gg.avs -o M:\CONVERTING\gg_temp\gg_out.h265

Error: Unknown value "smpte-st-2084" for "--transfer"

   at StaxRip.Proc.Start() in D:\Projekte\VS\VB\StaxRip\General\Proc.vb:line 338
   at StaxRip.NVEnc.Encode() in D:\Projekte\VS\VB\StaxRip\Encoding\NVEnc.vb:line 82
   at StaxRip.GlobalClass.ProcessVideo() in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 225
   at System.Threading.Tasks.Parallel.<>c__DisplayClass4_0.<Invoke>b__0()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at StaxRip.GlobalClass.ProcessJob(String jobPath) in D:\Projekte\VS\VB\StaxRip\General\GlobalClass.vb:line 137

**Comment by drSHLEFF** [comment]
NVEnc changed this option, use custom "--transfer smpte2084"

![inked2017-11-29 1 _li](https://user-images.githubusercontent.com/11748220/33358066-6e67a648-d4d7-11e7-867b-28e383b117d8.jpg)

**Comment by wolfhowling** [comment]
That fixed it, thanks.
