### ISSUE TITLE
Disable Audio Demux When No Audio Selected

### ISSUE THREAD

**Issue by devlin85** [stax76/staxrip#33]
If I don't want audio it shouldn't waste time extracting and converting it to flac. Real time waster.

**Comment by stax76** [comment]
Hello, can you mail me a log file?

**Comment by jhangyu** [comment]
Same question, Staxrip always demux audio whatever I set in "Batch file" mode, it's very annoying
I just want to use command line to convert audios in video files

**Comment by stax76** [comment]
Please share more details about your particular use case.

**Comment by jhangyu** [comment]
This is my convert setting:
http://imgur.com/kADUxvN
This is my audio command line setting:
http://imgur.com/iYJuJaT

It always first extract dts and covert to wav, finally execute my command and fail....
Where can I set staxrip to pass the extract process?

**Comment by stax76** [comment]
please try a new test build:

https://github.com/stax76/staxrip/blob/master/md/test-build.md

- added new option to disable audio and subtitle demuxing
- the batch audio profile uses now always batch execution, the PATH variable knows the location of ffmpeg, eac3to and BeSweet, the temp files directory is set as current directory, if input files is empty all files are excepted

take a look at the log file as it shows the batch file content, I've also replaced the command line default audio profile with this:

ffmpeg -i "%input%" -hide_banner -y "%output%"

I've not reset the default profiles so it can only be seen when the audio profiles are manually reset which can be done in the profiles editor or in the advanced menu.

Please close the issue if it solves the problem.

**Comment by jhangyu** [comment]
Hi !
Thank you for update the new version  
I've test this new test build and it works 💯, I don't need to add and wait indexing and check out the mux option one by one anymore :)
But cause of this issue isn't mine, I can't close it whatever :/

**Comment by stax76** [comment]
Next build will also skip demuxing if both audio profiles are 'No Audio', I think this issue is now solved so I close it.
