### ISSUE TITLE
Audio only WEBM files are not automatically recognized. 

### ISSUE THREAD

**Issue by nulledone** [stax76/staxrip#356]
While I was combining few videos I chopped out from YouTube with "youtube-dl" I saw that some audio files are using **WEBM** container. And sadly StaxRip won't recognize them as audio for the file that is being encoded. I can manually choose **WEBM** file as an audio and encode without any problems.

Additional explanation:

When there are 2 files with same names Staxrip will combine them if one is audio and other is video, but when the audio file is **WEBM** Staxrip ignores it.

Edit:Opus-->WEBM

**Comment by stax76** [comment]
I couldn't reproduce it, could you upload sample files?

**Comment by nulledone** [comment]
I just realized that title was misleading(sorry about that) and it should be 'WEBM' instead of 'OPUS'. Those .WEBM files include opus audio but as the extension is WEBM they are not recognized as audio. I can rename .webm to .opus as a workaround with no issues. 

You can get sample files from most videos using "-f bestaudio,bestvideo [youtubeURL]" commandline with youtube-dl.

**Comment by stax76** [comment]
You mean audio only webm without video? That don't appear much sane, it should rather be mka, webm is matroska container, opus is ogg/ogm container I think.

**Comment by nulledone** [comment]
According to MediaInfo

> General
> Complete name               : C:\sample.webm
> Format                      : WebM
> Format version              : Version 4 / Version 2
> File size                   : 3.39 MiB
> Duration                    : 3 min 21 s
> Overall bit rate            : 141 kb/s
> Writing application         : google/video-file
> Writing library             : google/video-file
> 
> Audio
> ID                          : 1
> Format                      : Opus
> Codec ID                    : A_OPUS
> Duration                    : 3 min
> Channel(s)                  : 2 channels
> Channel positions           : Front: L R
> Sampling rate               : 48.0 kHz
> Bit depth                   : 16 bits
> Compression mode            : Lossy
> Language                    : English
> Default                     : Yes
> Forced                      : No

According to Wikipedia (webm)
> Container for
> VP8/VP9/AV1 (video)
> Vorbis/Opus (audio)

And also (opus)
> Contained by
> Ogg, Matroska, WebM, MPEG-TS, MP4


In my opinion it is better not to implement it as this may and will cause issues in next builds, renaming the extension does the trick, and if someone encounters this they'll probably figure this workaround.
