### ISSUE TITLE
Seems like last the last release archive is broken (1.3.2.0)

### ISSUE THREAD

**Issue by olegcherr** [stax76/staxrip#37]
7-Zip cannot extract many **dll** and **exe** files from `StaxRip_x64_1.3.2.0.7z`.
Seems like it's broken.

![image](https://cloud.githubusercontent.com/assets/3730074/13494760/b16a6b6e-e15f-11e5-8ff3-d0771edcde41.png)

PS: `StaxRip_x64_1.3.1.7_beta.7z` is Okay.

**Comment by stax76** [comment]
try to re-download everything with a different browser

**Comment by olegcherr** [comment]
Solved. Sorry ))
