### ISSUE TITLE
KNLMeansCL: fatal error!

### ISSUE THREAD

**Issue by kchiem** [stax76/staxrip#38]
StaxRip x64 v1.3.2.0

[Log-KNLMeansCL.txt](https://github.com/stax76/staxrip/files/160054/Log-KNLMeansCL.txt)

**Comment by stax76** [comment]
it works here, system problem?

http://forum.doom9.org/showthread.php?t=171379

**Comment by kchiem** [comment]
Not sure, the same system runs v1.3.1.7_beta without problems.  There was an ongoing v1.3.1.7_beta encode going on when I was testing v1.3.2.0 with KNLMeansCL, not sure if that made a difference.

**Comment by kchiem** [comment]
Ok, I think I found the problem.  I have a GTX480 and that has OpenCL 1.1.  KNLMeansCL dropped support for that and only supports OpenCL 1.2 starting with their 0.7 releases, which is what you upgraded to in v1.3.2.0 vs v1.3.1.7_beta.

**Comment by kchiem** [comment]
Ok, I downgraded the KNLMeansCL dll in my v1.3.2.0 copy to v0.6.11 and it works again.
