### ISSUE TITLE
blu-ray to HDR script error loading Vapoursynth

### ISSUE THREAD

**Issue by quinton-ashley** [stax76/staxrip#387]
I get the following error when trying to use the blu-ray to HDR script.  These menus don't exist, how do I fix this?

Load Vapoursynth first
Filters -> Filter Setup -> Vapoursynth

**Comment by quinton-ashley** [comment]
```
PS C:\Program Files\Git> from vapoursynth import core
from vapoursynth import core
At line:1 char:1
+ from vapoursynth import core
+ ~~~~
The 'from' keyword is not supported in this version of the language.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ReservedKeywordNotAllowed
```

I'm using the latest version of Windows 10.  Am I doing this correctly?

**Comment by quinton-ashley** [comment]
oh okay!  I got that.  The script still throws the same error though.

**Comment by Revan654** [comment]
Not sure, if you have everything installed then it could be a permission issue. Make sure you using Python cmd line and not basic windows cmd line or powershell.

Personally I would just use Avisynth and setup the codec for HDR.

**Comment by Revan654** [comment]
Also Did you change the filter system in Staxrip? from AVS to VS?

**Comment by quinton-ashley** [comment]
How do I do that?

**Comment by Revan654** [comment]
It's in the left corner right above Source.

**Comment by pwacooijmans** [comment]
I am very sorry but vapoursynth doesn't support the right YUV standard to make hdr work....you will HAVE to use avisynth instead.

**Comment by quinton-ashley** [comment]
Yeah I looked into what the script was doing and it's limiting the output to 400 nits as well.  That's not real HDR so I'm not interested in using the script.  I did figure out how to change vapoursynth though thanks @Revan654

**Comment by pwacooijmans** [comment]
Are you willing to share that info with me maybe? I am interested as well.
Many thx in advance.

2018-06-04 8:00 GMT+02:00 Quinton Ashley <notifications@github.com>:
