### ISSUE TITLE
Allow custom x265 options

### ISSUE THREAD

**Issue by superunderscore** [stax76/staxrip#40]
I would like to use an x265 option that isn't available from the dropdown menu.

**Comment by skarekrow** [comment]
Have you looked at options>other 1>custom switches?

Options is located [here] (http://imgur.com/NrHV2Le)

**Comment by superunderscore** [comment]
Ah thanks, didn't notice it.

**Comment by stax76** [comment]
Next built will have it accessible via the quick search feature. :-)
