### ISSUE TITLE
Where is the language file

### ISSUE THREAD

**Issue by bluesky-dark** [stax76/staxrip#427]
I want to translate the UI into Chinese to use it more easily, but I can't find the language file.

**Comment by Revan654** [comment]
There isn't one, Language is coded into each Form and each form has to be changed to language you want within the designer and it's listed under language. Then during compile time it will use the language selected.

You also have to make any changes to any hardcoded language reference.

**Comment by bluesky-dark** [comment]
Thank you for your answer.It seems that I can only use the English UI.
