### ISSUE TITLE
Local temp directory bug

### ISSUE THREAD

**Issue by kchiem** [stax76/staxrip#43]
When encoding a Bluray folder on the network, it asks for a local temp directory.  Given:

\local\path\movie

It ends up creating a new directory at:

\local\path\movieTemp

And using that instead.  \local\path\movie remains empty.

**Comment by stax76** [comment]
I made a few changes and upload a new test build in a few days.

**Comment by stax76** [comment]
new build: https://github.com/stax76/staxrip/wiki/Test-Build
