### ISSUE TITLE
Delete temp files directory has no effect?

### ISSUE THREAD

**Issue by 44vince44** [stax76/staxrip#44]
Hello stax76,
The setting " Options > Misc > Delete temp files directory " seems not to work. After a finished task, the temp files are still there. I tried several temp folder location settings.
Currently, my temp files directory is C:\Temp\UsrZKTmp\%source_name%\
using Windows10x64.
Thank you for the good work ;)

**Comment by stax76** [comment]
Temp dir will only be deleted when it ends with _temp, next version will show a warning

**Comment by 44vince44** [comment]
Thanks Stax76, I guess you mean "temp files" which is the default, I tried it and it worked indeed. Thanks again.

**Comment by stax76** [comment]
in the test build default was changed to _temp because it's shorter and the windows 260 char max path limitation is less likely to happen, also the test build adds enclosing quotes to paths only if the path has any blanks

**Comment by 44vince44** [comment]
Many thanks for the information and for all the work ;)
