### ISSUE TITLE
System.IO.IOException when closing multiple instances at the same time

### ISSUE THREAD

**Issue by burnchar** [stax76/staxrip#45]
When I:
1. Start a file batch encode of about 6 files
2. Open three additional StaxRip Instances, pressed F6, and had each start an item in the queue
3. Cancel all encodes
4. Right-click on the Windows Taskbar icon representing all Staxrip instances
5. Click "Close all windows"

I get the following exception noted in the bottom of the attached log file.

I suspect all StaxRip instances are trying to write the same shared config file at once.

[Log.txt](https://github.com/stax76/staxrip/files/172280/Log.txt)

**Comment by stax76** [comment]
Thanks for reporting, it should be
      fixed in the next build.
