### ISSUE TITLE
A crop to the input video defaults NVEnc to 1920x520p

### ISSUE THREAD

**Issue by dvasiliu** [stax76/StaxRip#46]
Hi,

I am not sure how to solve this problem but it seems that if an input video is cropped in staxrip to 1920x800 the Nvidia Encoder will handle it as 1920x520p. This is referring to the latest version of staxrip 1.3.2 and NVENC SDK 6.0. Also, is there a documentation of what command lines or options we could use with NVENC ?  

I noticed that if I do not crop the input video, the encoder will handle it as 1080p : 
NVEnc 2.00?3 (x64), using NVENC API v6.0
OS Version         Windows 10 (x64)
CPU                Intel Core i7-4930K @ 3.40GHz (6C/12T)
GPU                #0: GeForce GTX TITAN X (24 EU) @ 1076 MHz (362.00)
Input Buffers      CUDA, 32 frames
Input Info         Avisynth 2.60(yv12)->nv12 [AVX], 1920x1080, 24000/1001 fps
Output Info        H.265/HEVC main
1920x1080p 1:1 23.976fps (24000/1001fps)

**Comment by stax76** [comment]
please post the full log to paste.bin, make it expire after 30 days
