### ISSUE TITLE
H 265 template

### ISSUE THREAD

**Issue by Xenas2127** [stax76/staxrip#47]
im having trouble finding the right h265 setting, instead of having a smaller file it somehow gets bigger.
im not sure if this would help but im using a gtx 960
[http://i.imgur.com/zmUVg4x.jpg]
do you guys have any suggestions? or maybe you guys have a template

**Comment by 44vince44** [comment]
You are using NVidia encoder, which is not recommended if you want to take advantage of the hevc encoding features. You should definitely use x265 encoder if you want proper results. I have tested all those 265 encoders, and found out that NVidia is the worst, Intel H265 is much better and has more settings accessible (but lacks look-ahead), and the very best is x265, quality mode or 2-pass.

**Comment by stax76** [comment]
@Xenas2127 

In the latest test build

https://github.com/stax76/staxrip/wiki/Test-Build

please go to main menu > Help > Forum > doom9 or videohelp

trackers are mostly used for bug reports and feature request
