### ISSUE TITLE
Can't encode h265 source ?

### ISSUE THREAD

**Issue by kchiem** [stax76/staxrip#49]
>"\StaxRip_x64_2016-03-14_test3\Apps\ffmpeg\ffmpeg.exe" -i ...
y4m  [info]: 1920x1024 fps 24/1 i420p8 sar 253:255 unknown frame count
raw  [info]: output file: NUL
x265 [info]: HEVC encoder version 1.9+88-b6d8e66e7f71
x265 [info]: build info [Windows][GCC 5.3.0][64 bit] 10bit
x265 [info]: using cpu capabilities: MMX2 SSE2Fast SSSE3 SSE4.2
x265 [info]: Main 10 profile, Level-4 (Main tier)
x265 [info]: Thread pool created using 8 threads
x265 [info]: frame threads / pool features       : 3 / wpp(16 rows)
x265 [error]: can't open mbtree stats file ...
x265 [error]: failed to open encoder
av_interleaved_write_frame(): Broken pipe
Error writing trailer of pipe:: Broken pipe

**Comment by stax76** [comment]
please attach the full log file
