### ISSUE TITLE
Event command criteria - program output

### ISSUE THREAD

**Issue by Fidelix** [stax76/staxrip#50]
![Event Commands](https://vgy.me/mU0fAS.png)
Using event commands, Stax could execute one or more stax commands (like choosing a different audio profile) depending on the output of a custom program.

This program would receive as a parameter a json (or whatever) with all the possible criteria data, as well as the event command's name and the target command.

This would allow users to achieve lot of complex automation logic.

**Comment by Fidelix** [comment]
I imagine the reason we don't already have this is because these are not currently exposed?

```
Shared Function GetMacrosWithParams() As List(Of Macro)
        Dim ret = GetMacros()

        ret.Add(New Macro("$enter_text:<prompt>$", "Enter Text (Params)", GetType(String), "Text entered in a input box."))
        ret.Add(New Macro("eval:<expression>", "Eval Math Expression", GetType(String), "Evaluates a math expression which may contain default macros."))
        ret.Add(New Macro("eval_js:<expression>", "Eval JScript Expression", GetType(String), "Evaluates a JScript expression which may contain default macros."))
        ret.Add(New Macro("eval_vb:<expression>", "Eval VBScript Expression", GetType(String), "Evaluates a VBScript expression which may contain default macros."))
        ret.Add(New Macro("filter:<name>", "Filter", GetType(String), "Returns the script code of a filter of the active project that matches the specified name."))
        ret.Add(New Macro("$select:<param1;param2;...>$", "Select", GetType(String), "String selected from dropdown."))
        ret.Add(New Macro("media_info_video:<property>", "MediaInfo Video Property", GetType(String), "Returns a MediaInfo video property for the source file."))
        ret.Add(New Macro("media_info_audio:<property>", "MediaInfo Audio Property", GetType(String), "Returns a MediaInfo audio property for the video source file."))

        Dim names As New List(Of String)

        For Each i In Packs.Packages
            names.Add(i.Name)
        Next

        ret.Add(New Macro("app:<name>", "Application File Path", GetType(String), "Returns the path of a aplication. Possible names are: " + String.Join(", ", names.ToArray)))
        ret.Add(New Macro("app_dir:<name>", "Application Directory", GetType(String), "Returns the directory of a aplication. Possible names are: " + String.Join(", ", names.ToArray)))

        Return ret
    End Function
```

Should the issue be renamed to "Provide a way to specify parameters to event commands" instead?

**Comment by stax76** [comment]
The topic is a bit difficult, a possibility would be define a new event that fires whenever a tool finishes and and make the output of the tool available as macro.

new event: Tool Finished
new macro: 'Output Of Last Tool' or maybe better something more general 'Event Arguments'

Another thing I was thinking of is adding check boxes to the event command list to make it easier to disable event commands.

What exactly would you like to automate? Maybe other solutions are possible.

**Comment by Fidelix** [comment]
Most of what I want to automate is already possible.

There are many types of sources that we encode and I'd like to define target sizes, audio profiles and bitrates depending on different criteria like source/target resolution, source/target size, source container and more.

I am aware that my use case is very uncommon, but this would also help solving automation problems for many other complex use cases.

It seems all the criteria I need is already available, now it's just a matter of calling a custom program during the current events - which already seem to be enough for what I need - with the criteria that's already there.

A new text field called "argument" or "target" for this specific criteria for instance, while jarring to the UI, would solve it.
But I'm not sure if I am being 100% clear, so let me know if I'm not and I can try to create a small mockup of it...

**Comment by stax76** [comment]
Yes I don't understand yet what you mean.

**Comment by Fidelix** [comment]
Something like this:
![Stax mockup](https://vgy.me/QhcDL4.png)

The executable would be passed the information of all the other criteria when it's called, maybe as a command line argument or as a path to a temporary json file...

**Comment by stax76** [comment]
I added something else, a new command:

Perform | Execute Batch Script

This will execute a batch script with all macros being solved plus additionally all macros being available as environment variables, if you run a exe in the batch script, then the exe has access to the macros too because it can access the environment variables too.

The 'Execute Batch Script' command has a option 'Interpret Output' that can be turned on to interpret each output line from the batch script or tools started in the batch script as StaxRip command like described in the command line help of StaxRip. 

possible tools: batch script, powershell.exe, cscript.exe (VBScript/JScript), python.exe, any other scripting engine or language like C#.

**Comment by Fidelix** [comment]
That is fantastic, if it works the way I think it pretty much solves any use cases I can think of.

Just one last thing:
Where will it execute this script from? Does it require a full system path or can I specify a relative path from the stax directory?

**Comment by Fidelix** [comment]
Do you mean you'll still add this new command or that I should use this one that's already in stax?
![Windows script](https://vgy.me/YjHGXr.png)

**Comment by stax76** [comment]
The batch script is entered directly. WSH is not supported on x64.

The command is here:

https://github.com/stax76/staxrip/blob/master/General/Misc.vb#L2626

Build is currently uploading.

**Comment by stax76** [comment]
I've added a wiki page with some info:

https://github.com/stax76/staxrip/wiki/Automation

**Comment by Fidelix** [comment]
I haven't been able to test this because the test build does not allow me to use my old template / configs, but I'm guessing we can close this.

If a problem comes up, I'll reopen or open another issue.

Thank you very much for the incredibly quick response and development @stax76

**Comment by stax76** [comment]
You are welcome, latest build has a new scripting solution btw.
