### ISSUE TITLE
StaxRip's pytnon can't import a module

### ISSUE THREAD

**Issue by eugenesvk** [stax76/staxrip#51]
I was trying to follow these [instructions](https://www.svp-team.com/forum/viewtopic.php?id=3244) on how to convert to video to 60FPS, but can't get past the first line **Script error** `Python exception: name 'core' is not defined`.
My setup
- latest [StaxRip test build](https://github.com/stax76/staxrip/wiki/Test-Build) with paths to Python and VapourSynth defined in `Tools->Apps` (though it did complain it couldn't read Python version, so I had to confirm manually `3.5.1 x64`
- installed [Python 3.5.1](https://www.python.org/ftp/python/3.5.1/python-3.5.1-amd64.exe) to default `c:\Program Files\Python35\` just for StaxRip (since it couldn't read any of the already installed conda or msys pythons)
- vapoursynth-r31
- Windows 10

Now, when I run the first few lines of the script from command line after invoking Python from `c:\Program Files\Python35\` it doesn't through this error, it's able to import the module and assign core variable. But not from within StaxRip. Not sure why.

The script is 

```
import vapoursynth as vs

core = vs.get_core(threads=19)
core.std.LoadPlugin("c:\\Apps\\MultiMedia\\Utilities\\VapourSynth\\plugins64\\svpflow1_vs64.dll")
core.std.LoadPlugin("c:\\Apps\\MultiMedia\\Utilities\\VapourSynth\\plugins64\\svpflow2_vs64.dll")
clip = clip.resize.Bicubic(format=vs.YUV420P8)

crop_string  = ""
resize_string = "core.resize.Bicubic(input,1280,720,filter_param_a=0,filter_param_b=0.75)"
super_params     = "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params   = "{main:{search:{coarse:{distance:-8},distance:0}}}"
smoothfps_params = "{gpuid:11,rate:{num:2,den:1},algo:13,mask:{area:50},scene:{blend:true}}"

def interpolate(clip):
    input = clip
    if crop_string!='':
        input = eval(crop_string)
    if resize_string!='':
        input = eval(resize_string)
    super   = core.svp1.Super(input,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
    smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
    return smooth
smooth =  interpolate(clip)
smooth.set_output()
```

Also, when I clicked `Crop` menu, I couldn't exit it because on every try (Esc, Alt-F4 etc.) it would warn with that `Python exception` and I had to terminate the process via Task Manager
![staxrip crop](https://cloud.githubusercontent.com/assets/12956286/14347845/bbccb58a-fcc1-11e5-95df-36858129a3bb.PNG)

**Comment by stax76** [comment]
> I was trying to follow these instructions

this doesn't look good since it sets the core which StaxRip already does for convenience, if you have problems to understand how StaxRip's scripting editor works you can also open avs or vpy files with StaxRip, it still uses the scripting editor but puts the entire script into a single filter. Next build has some improvements for it.

> latest StaxRip test build with paths to Python and VapourSynth defined in Tools->Apps (though it did complain it couldn't read Python version, so I had to confirm manually

it should detect the original installer using last change date, confirming manually is no problem if the version is compatible

> installed Python 3.5.1 to default c:\Program Files\Python35\ just for StaxRip (since it couldn't read any of the already installed conda or msys pythons)

next build will have some improvement:

> besides detecting the python location of the regular setup and miniconda setup StaxRip now also searches in the PATH and Path environment variables for python

> Also, when I clicked Crop menu, I couldn't exit it because on every try (Esc, Alt-F4 etc.) it would warn with that Python exception and I had to terminate the process via Task Manager

it's fixed in the next build:

> in same situations it wasn't possible to close the crop dialog due to an script error, now the message box showing the error has an additional exit button

**Comment by eugenesvk** [comment]
> sets the core which StaxRip already does for convenience

But where, for example, can I see the `rate:{num:2,den:1}` option in StaxRip that would get added to all the other encoding parameters I've set e.g. in GUI?

> can also open avs or vpy files with StaxRip

The person on that forum attached his avs files, but StaxRip just crashed when I tried to open them, so that's not of much help unfortunately (you can see that forum for detailed error message).

> next build will have some improvement

That's nice!

> it should detect the original installer using last change date

Can it not just run `python -V` and read output? It has been unable to identify any of the `python.exe` files I pointed it to (just downloaded the latest version)


Also, now that I've set the preset, when I open a video file and select e.g. `Automatic VapourSynth`, I get an error that it can't be read source (which is strange, before saving a preset, it all worked fine and I've already transcoded the same video file to ~60FPS).

```
Failed to open source
Script error: expected a , or )
(C:\Users\Evgeny\Videos\20110618-Sample-Original_temp\20110618-Sample-Original_new_Source.avs, line 1, column 79)
```

The `20110618-Sample-Original_new_Source.avs` file is
```
clip = core.ffms2.Source(r"C:\Users\Evgeny\Videos\20110618-Sample-Original.mkv", cachefile = r"C:\Users\Evgeny\Videos\20110618-Sample-Original_temp\20110618-Sample-Original.ffindex")
```
Don't understand what the issue is, there is a comma at exactly the spot StaxRip is complaining about.


If I try to cancel the dialog that offers several filters and rely on the preset (because those filters overwrite all my settings and I have to copy&paste that SVP script again) I get a crash

```
Exception
Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) in D:\Projekte\GitHub\staxrip\Forms\MainForm.vb:line 1845
```
and I don't have any `D:\Projekte\GitHub\staxrip\Forms\MainForm.vb`

**Comment by eugenesvk** [comment]
Here is the full log from exception error
```
-----------------------------------------------------------
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

------------------------------------------------------------
                        Environment
------------------------------------------------------------

StaxRip x64 : 1.3.3.5
OS          : Windows 10 Pro
Language    : English (United States)
CPU         : Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
GPU         : NVIDIA GeForce GTX TITAN

------------------------------------------------------------
                   Source file MediaInfo
------------------------------------------------------------

C:\Users\Evgeny\Videos\20110618-Sample-Original.mkv

General
Complete name             : C:\Users\Evgeny\Videos\20110618-Sample-Original.mkv
Format                    : Matroska
Format version            : Version 2
File size                 : 15.9 MiB
Duration                  : 26s 693ms
Overall bit rate          : 4 996 Kbps
Writing application       : x264 r1995 c1e60b9
Writing library           : Haali Matroska Writer b0
IsTruncated               : Yes

Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High@L3.1
Format settings, CABAC    : Yes
Format settings, ReFrames : 4 frames
Codec ID                  : V_MPEG4/ISO/AVC
Duration                  : 26s 693ms
Bit rate                  : 4 896 Kbps
Width                     : 1 280 pixels
Height                    : 720 pixels
Display aspect ratio      : 16:9
Frame rate mode           : Constant
Frame rate                : 23.976 (24000/1001) fps
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.222
Stream size               : 15.6 MiB (98%)
Writing library           : x264 core 115 r1995 c1e60b9
Encoding settings         : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                  : English
Default                   : Yes
Forced                    : No


------------------------------------------------------------
                    Error opening source
------------------------------------------------------------

Script error: expected a , or )
(C:\Users\Evgeny\Videos\20110618-Sample-Original_temp\20110618-Sample-Original_new_Source.avs, line 1, column 79)

clip = core.ffms2.Source(r"C:\Users\Evgeny\Videos\20110618-Sample-Original.mkv", cachefile = r"C:\Users\Evgeny\Videos\20110618-Sample-Original_temp\20110618-Sample-Original.ffindex")

------------------------------------------------------------
                         Exception
------------------------------------------------------------

System.NullReferenceException: Object reference not set to an instance of an object.
   at StaxRip.MainForm.OpenVideoSourceFiles(IEnumerable`1 files, Boolean isNotEncoding) in D:\Projekte\GitHub\staxrip\Forms\MainForm.vb:line 1845
```

**Comment by eugenesvk** [comment]
It seems there is an issue with custom templates in source filters.
If I save just one source simple line in 
Source: `ffms2` `clip = core.ffms2.Source(r"%source_file%", cachefile = r"%temp_file%.ffindex")`, save it as a template, and load it — that's it. I start to get all those weird errors that I didn't get before when exactly the same command got auto-populated AFTER I've loaded the file.

Would you please fix it so I can save those two scripts (source and resize) and have a profile "Convert 24fps to 60fps"? Otherwise I have to copy&paste the scripts every single time :(

**Comment by stax76** [comment]
Please open a dedicated issue for each problem, for the last problem please post a screenshot.
