### ISSUE TITLE
Access is denied to settings folder

### ISSUE THREAD

**Issue by eugenesvk** [stax76/staxrip#52]
On install I've put my settings in Dropbox `D:\Eugene\Personal\PC\Dropbox\Settings\MultiMedia\StaxRip\`. Now when I open `tools->Directories->Settings` I get the following error
```
Access is denied
File: D:\Eugene\Personal\PC\Dropbox\Settings\MultiMedia\StaxRip\
```
tried to launch StaxRip as admin — didn't help
Window 10 with latest test build StaxRip x64 1.3.3.5 beta

**Comment by stax76** [comment]
I only use gdrive and 1drive so I cannot test it. When .NET throws an exception something must be locked so it's not a StaxRip problem. I've added now some excepting handling to show error messages instead of crashing.

**Comment by eugenesvk** [comment]
Thank you, it's fixed now (even though Chrome  tried to block your updated app this time ;)
