### ISSUE TITLE
Can't open file with pre-loaded template source script

### ISSUE THREAD

**Issue by eugenesvk** [stax76/staxrip#53]
Filing a separate issue from https://github.com/stax76/staxrip/issues/51

1. Add a template with Source `ffms2` `clip = core.ffms2.Source(r"%source_file%", cachefile = r"%temp_file%.ffindex")`
![staxrip 1 editor](https://cloud.githubusercontent.com/assets/12956286/14405337/54c7afd6-fe95-11e5-8850-04676b44afb0.PNG)

2. Restart StaxRip and load this template
![staxrip 2 template](https://cloud.githubusercontent.com/assets/12956286/14405339/5e3b801a-fe95-11e5-8dbf-4a7da9904407.PNG)

3. Drag&drop a sample [mkv file](http://www.spirton.com/uploads/InterFrame/20110618-Sample-Original.mkv) to get a crash
![staxrip 3 crash](https://cloud.githubusercontent.com/assets/12956286/14405344/8815137e-fe95-11e5-8dc2-30d7c9db6725.PNG)

4. Follow the suggestion to uses another source filter, choose e.g. "Automatic Vaporsynth" (which actually uses the same ffms2).
Enjoy a different looking window with the same error
![staxrip 3 crash2 with vapor auto](https://cloud.githubusercontent.com/assets/12956286/14405359/b7b9d876-fe95-11e5-9f11-b42b5cce28b0.PNG)

5. Open the mysterious `Sample_x24_new_Source.avs` and see a pretty harmless text
`clip = core.ffms2.Source(r"C:\Users\Evgeny\Videos\Sample_x24.mkv", cachefile = r"C:\Users\Evgeny\Videos\Sample_x24_temp\Sample_x24.ffindex")`

Using Windows 10 and yesterday's version of StaxRip

**Comment by eugenesvk** [comment]
When opening the same file with default template (`x264`) it all works fine and the resulting source filter is also identical `clip = core.ffms2.Source(r"%source_file%", cachefile = r"%temp_file%.ffindex")` (I'm actually just copy&pasting it in my example.

**Comment by eugenesvk** [comment]
And error log `Sample_x24_new_StaxRip.log`

```
-----------------------------------------------------------
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

------------------------------------------------------------
                        Environment
------------------------------------------------------------

StaxRip x64 : 1.3.3.6
OS          : Windows 10 Pro
Language    : English (United States)
CPU         : Intel(R) Core(TM) i7-3770K CPU @ 3.50GHz
GPU         : NVIDIA GeForce GTX TITAN

------------------------------------------------------------
                   Source file MediaInfo
------------------------------------------------------------

C:\Users\Evgeny\Videos\Sample_x24.mkv

General
Complete name             : C:\Users\Evgeny\Videos\Sample_x24.mkv
Format                    : Matroska
Format version            : Version 2
File size                 : 15.9 MiB
Duration                  : 26s 693ms
Overall bit rate          : 4 996 Kbps
Writing application       : x264 r1995 c1e60b9
Writing library           : Haali Matroska Writer b0
IsTruncated               : Yes

Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : High@L3.1
Format settings, CABAC    : Yes
Format settings, ReFrames : 4 frames
Codec ID                  : V_MPEG4/ISO/AVC
Duration                  : 26s 693ms
Bit rate                  : 4 896 Kbps
Width                     : 1 280 pixels
Height                    : 720 pixels
Display aspect ratio      : 16:9
Frame rate mode           : Constant
Frame rate                : 23.976 (24000/1001) fps
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.222
Stream size               : 15.6 MiB (98%)
Writing library           : x264 core 115 r1995 c1e60b9
Encoding settings         : cabac=1 / ref=3 / deblock=1:0:0 / analyse=0x3:0x113 / me=hex / subme=7 / psy=1 / psy_rd=1.00:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=6 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=3 / b_pyramid=2 / b_adapt=1 / b_bias=0 / direct=1 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=23 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=crf / mbtree=1 / crf=18.0 / qcomp=0.60 / qpmin=0 / qpmax=69 / qpstep=4 / ip_ratio=1.40 / aq=1:1.00
Language                  : English
Default                   : Yes
Forced                    : No


------------------------------------------------------------
                    Error opening source
------------------------------------------------------------

Script error: expected a , or )
(C:\Users\Evgeny\Videos\Sample_x24_temp\Sample_x24_new_Source.avs, line 1, column 65)

clip = core.ffms2.Source(r"C:\Users\Evgeny\Videos\Sample_x24.mkv", cachefile = r"C:\Users\Evgeny\Videos\Sample_x24_temp\Sample_x24.ffindex")
```

**Comment by stax76** [comment]
```
clip = core.ffms2.Source(r"C:\Users\Evgeny\Videos\Sample_x24.mkv", cachefile = r"C:\Users\Evgeny\Videos\Sample_x24_temp\Sample_x24.ffindex")
```

It's not a full script, saving the vpy file StaxRip normally adds the missing parts:

```
import vapoursynth as vs
core = vs.get_core()
core.std.LoadPlugin(r"D:\Projekte\GitHub\staxrip\bin\Apps\Plugins\both\ffms2\ffms2.dll")
clip = core.ffms2.Source(r"D:\Video\Samples\MKV\DTS-MA  PGS.mkv", cachefile = r"D:\Video\Samples\MKV\DTS-MA  PGS_temp\DTS-MA  PGS.ffindex")
clip.set_output()
````

I don't think this has anything to do with templates, it will probably happen whenever your source filter is core.ffms2.Source, please note the default source filter is called Manual which will trigger the filter selection dialog. Why not use automatic instead?

```
[Source]
**Automatic = # can be configured at main menu > Tools > Settings > Source Filters**
AviSource = AviSource("%source_file%", Audio = False)
DGSource = DGSource("%source_file%")
DGSourceIM = DGSourceIM("%source_file%")
DirectShowSource = DirectShowSource("%source_file%", audio = False)
DSS2 = DSS2("%source_file%")
FFVideoSource = FFVideoSource("%source_file%", cachefile = "%temp_file%.ffindex")
LSMASHVideoSource = LSMASHVideoSource("%source_file%", format = "YUV420P8")
LWLibavVideoSource = LWLibavVideoSource("%source_file%", format = "YUV420P8")
**Manual = # shows the filter selection dialog**
```

I cannot reproduce it however, maybe it's due to some changed setting, please zip your settings dir and attach/mail it.

**Comment by eugenesvk** [comment]
> Why not use automatic instead?

Because then it overwrites my custom resize filter. I wanted to do a simple thing — save default ffms2 source and custom resize filter in a template. If I paste my resize filter and then use automatic filter selection dialogue, the resize filter gets discarded

> it will probably happen whenever your source filter is core.ffms2.Source

Nope, when I use automatic my source is ffms2 and it goes fine. It only breaks when I have preset the same identical source line myself (by loading via a template)

**Comment by eugenesvk** [comment]
Config files are here, though I've only changed menus, otherwise all other settings are  not changed https://github.com/eugenesvk/temp

**Comment by eugenesvk** [comment]
> it will probably happen whenever your source filter is core.ffms2.Source
I think I might have found the issue with your hint.

Check the screenshots of my source filters **before**I load a file and select `Automatic VapourSynth` (it has NO ffms2 filter) and **after** I load it (ffms2 appears)
1. before (fresh start)
![staxrip 4 sourcesfreshstart](https://cloud.githubusercontent.com/assets/12956286/14407009/647c6930-fec2-11e5-97c7-4a8ab1a09c15.PNG)

2. after
![staxrip 4 sourcesaftervs](https://cloud.githubusercontent.com/assets/12956286/14407010/6973688a-fec2-11e5-8687-650c1392734b.PNG)

**Comment by stax76** [comment]
Apparently we both missed the obvious, I mean look at the first screenshot, AviSynth and VapourSynth code all mixed up, in Trumps words: total disaster

go to

Filters > Filter Setup

and load VapourSynth

**Comment by eugenesvk** [comment]
Thanks! That one is gone.
However, I still can't use the template function properly.
With the same script 
1. (works) Fresh start, drag&drop video file, select "Automatic Vapoursynth"
2. (works) Fresh start, Filters -> Filter Setup -> Load VapourSynth, drag&drop
3. (**FAILS**) Fresh start, load template with the same script, drag&drop -> `python exception: name 'core' is not defined`

Just FYI the resize script again (source script is always ffms2):
```
core = vs.get_core(threads=19)
clip = clip.resize.Bicubic(format=vs.YUV420P8)
crop_string  = ""
resize_string = "core.resize.Bicubic(input,1280,720,filter_param_a=0,filter_param_b=0.75)"
super_params     = "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params   = "{main:{search:{coarse:{distance:-8},distance:0}}}"
smoothfps_params = "{gpuid:11,rate:{num:25,den:10},algo:13,mask:{area:50},scene:{blend:true}}"
def interpolate(clip):
    input = clip
    if crop_string!='':
        input = eval(crop_string)
    if resize_string!='':
        input = eval(resize_string)
    super   = core.svp1.Super(input,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
    smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
    return smooth
smooth =  interpolate(clip)
smooth.set_output()
```

**Comment by stax76** [comment]
download svp VapourSynth x64 plugins from:

http://www.svp-team.com/files/gpl/svpflow-4.0.0.128.zip

go to Tools > Directories > Plugins

it opens the VapourSynth x64 auto load plugin folder were you put your plugins in

use this resize code

```
clip = clip.resize.Bicubic(format=vs.YUV420P8)
crop_string  = ""
resize_string = "core.resize.Bicubic(input,1280,720,filter_param_a=0,filter_param_b=0.75)"
super_params     = "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params   = "{main:{search:{coarse:{distance:-8},distance:0}}}"
smoothfps_params = "{gpuid:11,rate:{num:25,den:10},algo:13,mask:{area:50},scene:{blend:true}}"
def interpolate(clip):
    input = clip
    if crop_string!='':
        input = eval(crop_string)
    if resize_string!='':
        input = eval(resize_string)
    super   = core.svp1.Super(input,super_params)
    vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
    smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
    smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
    return smooth
clip = interpolate(clip)
```
I don't know what the code does but it don't look like the there is any need for using a function.

Almost all of your issues are because of very very poor understanding of Python, VapourSynth and StaxRip.

**Comment by eugenesvk** [comment]
> download svp VapourSynth x64 plugins from

I've done this step already earlier, that's why I removed these two lines from the original script
```
core.std.LoadPlugin("path\\VapourSynth\\plugins64\\svpflow1_vs64.dll")
core.std.LoadPlugin("path\\VapourSynth\\plugins64\\svpflow2_vs64.dll")
```
Python complained that the modules were already loaded when I tested it.

> poor understanding of Python, VapourSynth and StaxRip.

Well, it's not like there is a StaxRip guide that explains that without filter setup filters get mixed up.
Or that you can't load VapourSynth module within the script (which is a strange limitation).

By the way, I've noticed that the script can't contain comments despite being written in python, right? When I tried to just use a `#` in front of `core = vs.get_core(threads=19)` I'd get the same error.
I think actually that was the main reason of my troubles — StaxRip continued to try import VS module (and generate an error) even though I've commented it out in my python file and didn't realize that sometimes I'd just paste it to StaxRip with the commented out line and StaxRip would not ignore the the comment. That's why this `core` line was working for the other person who proposed this solution. 

> I don't know what the code does

It converts a video from 30fps to 60fps using very nice [SVP](www.svp-team.com) interpolation technique that smooths the video playback — quite a noticeable improvement.

>don't look like there is a need for using a function

Nope, just helps with readability.

**Comment by stax76** [comment]
get_core don't matter as it looks for 'import vapoursynth'

```
If engine = ScriptingEngine.VapourSynth AndAlso Not scriptLower.Contains("import vapoursynth") Then
    code = "import vapoursynth as vs" + CrLf + "core = vs.get_core()" + CrLf
End If
```

**Comment by eugenesvk** [comment]
`Not scriptLower.Contains("import vapoursynth")`
Interesting that you're checking for this line in the script, but actually not allowing it to actually be there (it'd throw an error).
Closing this as I you've helped resolved all the issues that prevented me from saving a simple 24->60fps conversion template. Thank you

**Comment by stax76** [comment]
It's allowed otherwise you couldn't open avs or vpy files.

**Comment by eugenesvk** [comment]
But how is it allowed if I can't use it? I get an error if I include that line in my script

**Comment by stax76** [comment]
Script Editor > Context Menu > Join Filters > post it
Script Editor > Context Menu > Code Preview > post it

**Comment by eugenesvk** [comment]
I don't have the `Join Filters` command in the context menu
![staxrip 5 filtercontext](https://cloud.githubusercontent.com/assets/12956286/14408743/4efc6f5a-ff09-11e5-8c0a-79468cc71b54.PNG)


Script Editor > Context Menu > Code Preview 
```
clip = core.ffms2.Source(r"C:\Users\Evgeny\Videos\Sample_x24.mkv", cachefile = r"C:\Users\Evgeny\Videos\Sample_x24_temp\Sample_x24.ffindex")
import vapoursynth as vs
core            	= vs.get_core(threads=19)
clip            	= clip.resize.Bicubic(format=vs.YUV420P8)
crop_string     	= ""
resize_string   	= "core.resize.Bicubic(input,1280,720,filter_param_a=0,filter_param_b=0.75)"
super_params    	= "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params  	= "{main:{search:{coarse:{distance:-8},distance:0}}}"
smoothfps_params	= "{gpuid:11,rate:{num:25,den:10},algo:13,mask:{area:50},scene:{blend:true}}"
def interpolate(clip):
	input = clip
	if crop_string!='':
		input = eval(crop_string)
	if resize_string!='':
		input = eval(resize_string)
	super   = core.svp1.Super(input,super_params)
	vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
	smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
	smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
	return smooth
clip = interpolate(clip)
clip.set_output()
```

And if I remove just one single line `import vapoursynth as vs` it all works fine (because you automatically add vapoursynth in your script and it also happens to be imported as `vs`

**Comment by stax76** [comment]
You are making me crazy :-), double-click the list to show the editor or click on edit in the menu.

**Comment by eugenesvk** [comment]
But you've already seen that part, I've posted it several times before!

Source is `clip = core.ffms2.Source(r"%source_file%", cachefile = r"%temp_file%.ffindex")`
and Resize is 
```
import vapoursynth as vs
core            	= vs.get_core(threads=19)
clip            	= clip.resize.Bicubic(format=vs.YUV420P8)
crop_string     	= ""
resize_string   	= "core.resize.Bicubic(input,1280,720,filter_param_a=0,filter_param_b=0.75)"
super_params    	= "{pel:1,scale:{up:0},gpu:1,full:false,rc:true}"
analyse_params  	= "{main:{search:{coarse:{distance:-8},distance:0}}}"
smoothfps_params	= "{gpuid:11,rate:{num:25,den:10},algo:13,mask:{area:50},scene:{blend:true}}"
def interpolate(clip):
	input = clip
	if crop_string!='':
		input = eval(crop_string)
	if resize_string!='':
		input = eval(resize_string)
	super   = core.svp1.Super(input,super_params)
	vectors = core.svp1.Analyse(super["clip"],super["data"],input,analyse_params)
	smooth  = core.svp2.SmoothFps(input,super["clip"],super["data"],vectors["clip"],vectors["data"],smoothfps_params,src=clip)
	smooth  = core.std.AssumeFPS(smooth,fpsnum=smooth.fps_num,fpsden=smooth.fps_den)
	return smooth
clip = interpolate(clip)
```

The code preview shows them combined, but ok, here is the screenshot of the editor

![staxrip 5 filtercontext2](https://cloud.githubusercontent.com/assets/12956286/14408847/abe27918-ff0d-11e5-98c2-582d6dcf400d.PNG)

**Comment by stax76** [comment]
Please read a couple of beginner python tutorials before creating a new issue on the tracker...

**Comment by eugenesvk** [comment]
Please point to a page in a python tutorial explaining why I can't import a python module in a python script.
The python tutorial I have read plus the vapoursynth tutorial I've started to read (and test in python itself)  don"t explain it.

**Comment by stax76** [comment]
clip = **core**.ffms2.Source(r"C:\Users\Evgeny\Videos\Sample_x24.mkv", cachefile = r"...")
import vapoursynth as vs
**core** = vs.get_core(threads=19)

You cannot see what is the problem here? You use the core variable before it was declared and assigned. It doesn't look that you actually programmed something more useful then Hello World.

**Comment by eugenesvk** [comment]
But it's not the actual script that gets executed! Your pre-script defines **core** variable!
```
import vapoursynth as vs
core = vs.get_core()              <-- Here it's defined
core.std.LoadPlugin(r"ffms2.dll")
clip = core.ffms2.Source(...)     <-- so this shouldn't throw an error
                                                        just because I have core defined later
                                  < -- and if the script had 'import vapoursynth as vs' here
                                    also shouldn't throw an error
core            	= vs.get_core(threads=19)         
clip            	= clip.resize.Bicubic(format=vs.YUV420P8)
```

So the problem is that at runtime the app executes one script, but during script setup the assistant checks a totally different script (and to confuse it even further, it complains that core is undefined it **only** when `import vapoursynth as vs` is present). And that weird behavior doesn't have much to do with any python knowledge (or lack thereof) on the user's part.
