### ISSUE TITLE
Default Project Name should use "Default Target Name".

### ISSUE THREAD

**Issue by Yuanuo** [stax76/staxrip#54]
When the template is set up, if the "Options" specified "Default Target Name", generated srip project should be followed by the specified name are the same, or version of a video to generate several different parameters, the last project file will override works before, because there's always using the source file name project name.

Please fix this, thank you.

**Comment by stax76** [comment]
Please try to describe the issue much better, I can't follow you.

Maybe you don't understand StaxRip not good enough, maybe your English isn't good enough or maybe it's both.

Please have mercy, another user was giving me a very hard time lately.

**Comment by Yuanuo** [comment]
I'm sorry, please forgive me for my bad English.

My demand is that I need to encode the video into MP4, a 600kbps and a 1500kbps.
I made two templates, for each template, and specify the "Options->Paths->Default Target Name" (similar to "%source_name%-600kbps", "%source_name%-1500kbps")
But when I use batch processing tasks,
First select the "600kbps" template, open a source file-> File Batch->Add->Add Files, select "001.avi" automatically creates a srip project file "001.srip".
Then select the "1500kbps" template, repeat the above operation select "001.avi", will also create a srip project file "001.srip", "600kbps" srip project file overrides.
That's the problem, what do you see what I mean?

**Comment by stax76** [comment]
No problem, next build has it fixed.
