### ISSUE TITLE
please add an option in the preferences to scale the user interface

### ISSUE THREAD

**Issue by northwest1976** [stax76/staxrip#56]
![staxrip](https://cloud.githubusercontent.com/assets/18382344/14411963/f0db2bc0-ff56-11e5-8e40-d917d5dcdcce.PNG)

**Comment by northwest1976** [comment]
![stax](https://cloud.githubusercontent.com/assets/18382344/14453365/a83c06f2-0094-11e6-85f7-6d8658704ae4.PNG)

Thanks

**Comment by stax76** [comment]
Please post a screenshot in case you find a scaling bug or quirk.
