### ISSUE TITLE
Encoding using QSVEncC 2.44v2 x64 failed with exit code: 1 (0x1)

### ISSUE THREAD

**Issue by emre55aydin** [stax76/StaxRip#58]
-----------------------------------------------------------
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

------------------------------------------------------------
                        Environment
------------------------------------------------------------

StaxRip x64 : 1.3.3.9
OS          : Windows 10 Pro
Language    : Turkish (Turkey)
CPU         : Intel(R) Core(TM) i5-3570K CPU @ 3.40GHz
GPU         : Intel(R) HD Graphics 4000, AMD Radeon (TM) R9 380 Series

------------------------------------------------------------
                   Source file MediaInfo
------------------------------------------------------------

D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359.mp4

General
Complete name             : D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359.mp4
Format                    : MPEG-4
Format profile            : Base Media
Codec ID                  : isom (isom/3gp4)
File size                 : 977 MiB
Duration                  : 6mn 45s
Overall bit rate          : 20.2 Mbps
Encoded date              : UTC 2015-01-25 12:40:51
Tagged date               : UTC 2015-01-25 12:40:51
Video
ID                        : 1
Format                    : AVC
Format/Info               : Advanced Video Codec
Format profile            : Baseline@L4
Format settings, CABAC    : No
Format settings, ReFrames : 1 frame
Format settings, GOP      : M=1, N=30
Codec ID                  : avc1
Codec ID/Info             : Advanced Video Coding
Duration                  : 6mn 45s
Bit rate                  : 20.0 Mbps
Width                     : 1 920 pixels
Height                    : 1 080 pixels
Display aspect ratio      : 16:9
Frame rate mode           : Variable
Frame rate                : 30.000 fps
Minimum frame rate        : 6.006 fps
Maximum frame rate        : 31.315 fps
Color space               : YUV
Chroma subsampling        : 4:2:0
Bit depth                 : 8 bits
Scan type                 : Progressive
Bits/(Pixel*Frame)        : 0.321
Stream size               : 967 MiB (99%)
Title                     : VideoHandle
Language                  : English
Encoded date              : UTC 2015-01-25 12:40:51
Tagged date               : UTC 2015-01-25 12:40:51
Audio
ID                        : 2
Format                    : AAC
Format/Info               : Advanced Audio Codec
Format profile            : LC
Codec ID                  : 40
Duration                  : 6mn 45s
Source duration           : 6mn 45s
Bit rate mode             : Constant
Bit rate                  : 192 Kbps
Nominal bit rate          : 256 Kbps
Channel(s)                : 2 channels
Channel positions         : Front: L R
Sampling rate             : 48.0 KHz
Frame rate                : 46.875 fps (1024 spf)
Compression mode          : Lossy
Stream size               : 9.29 MiB (1%)
Source stream size        : 9.29 MiB (1%)
Title                     : SoundHandle
Language                  : English
Encoded date              : UTC 2015-01-25 12:40:51
Tagged date               : UTC 2015-01-25 12:40:51
mdhd_Duration             : 405988

------------------------------------------------------------
             Demux audio using MP4Box 0.6.0 x64
------------------------------------------------------------

"C:\Program Files\StaxRip\Apps\MP4Box\MP4Box.exe" -single 2 -out "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.m4a" "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359.mp4"

Start:    19:59:56
End:      20:00:00
Duration: 00:00:04

General
Complete name         : D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.m4a
Format                : MPEG-4
Format profile        : Base Media
Codec ID              : isom (isom)
File size             : 9.38 MiB
Duration              : 6mn 45s
Overall bit rate mode : Variable
Overall bit rate      : 194 Kbps
Encoded date          : UTC 2016-04-13 16:59:56
Tagged date           : UTC 2016-04-13 16:59:56
Audio
ID                    : 2
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : 40
Duration              : 6mn 45s
Bit rate mode         : Variable
Bit rate              : 192 Kbps
Nominal bit rate      : 27 bps
Maximum bit rate      : 197 Kbps
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 KHz
Frame rate            : 46.875 fps (1024 spf)
Compression mode      : Lossy
Stream size           : 9.29 MiB (99%)
Encoded date          : UTC 2016-04-13 16:59:56
Tagged date           : UTC 2016-04-13 17:00:00

------------------------------------------------------------
                    Index with ffmsindex
------------------------------------------------------------

"C:\Program Files\StaxRip\Apps\Plugins\both\ffms2\ffmsindex.exe" "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359.mp4" "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359.ffindex"

Writing index... done.

Start:    20:00:00
End:      20:00:11
Duration: 00:00:10

------------------------------------------------------------
                           Script
------------------------------------------------------------

LoadPlugin("C:\Program Files\StaxRip\Apps\Plugins\both\ffms2\ffms2.dll")
FFVideoSource("D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359.mp4", cachefile = "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359.ffindex")

------------------------------------------------------------
                     Script Properties
------------------------------------------------------------

source frame count : 12175
source frame rate  : 30.000000
source duration    : 00:06:45.8330000
target frame count : 12175
target frame rate  : 30.000000
target duration    : 00:06:45.8330000

------------------------------------------------------------
                Audio Source File MediaInfo
------------------------------------------------------------

General
Complete name         : D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.m4a
Format                : MPEG-4
Format profile        : Base Media
Codec ID              : isom (isom)
File size             : 9.38 MiB
Duration              : 6mn 45s
Overall bit rate mode : Variable
Overall bit rate      : 194 Kbps
Encoded date          : UTC 2016-04-13 16:59:56
Tagged date           : UTC 2016-04-13 16:59:56
Audio
ID                    : 2
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : 40
Duration              : 6mn 45s
Bit rate mode         : Variable
Bit rate              : 192 Kbps
Nominal bit rate      : 27 bps
Maximum bit rate      : 197 Kbps
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 KHz
Frame rate            : 46.875 fps (1024 spf)
Compression mode      : Lossy
Stream size           : 9.29 MiB (99%)
Encoded date          : UTC 2016-04-13 16:59:56
Tagged date           : UTC 2016-04-13 17:00:00

------------------------------------------------------------
    Convert from M4A to FLAC using ffmpeg 2016-03-10 x64
------------------------------------------------------------

"C:\Program Files\StaxRip\Apps\ffmpeg\ffmpeg.exe" -i "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.m4a" -y -hide_banner -ac 2 "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.flac"

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.m4a':
Metadata:
major_brand     : isom
minor_version   : 1
compatible_brands: isom
creation_time   : 2016-04-13 16:59:56
Duration: 00:06:45.99, start: 0.000000, bitrate: 193 kb/s
Stream #0:0(und): Audio: aac (LC) (mp4a / 0x6134706D), 48000 Hz, stereo, fltp, 191 kb/s (default)
Metadata:
creation_time   : 2016-04-13 16:59:56
handler_name    : GPAC ISO Audio Handler
[flac @ 0000021644f9d400] encoding as 24 bits-per-sample
Output #0, flac, to 'D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.flac':
Metadata:
major_brand     : isom
minor_version   : 1
compatible_brands: isom
encoder         : Lavf57.28.100
Stream #0:0(und): Audio: flac, 48000 Hz, stereo, s32 (24 bit), 128 kb/s (default)
Metadata:
creation_time   : 2016-04-13 16:59:56
handler_name    : GPAC ISO Audio Handler
encoder         : Lavc57.28.100 flac
Stream mapping:
Stream #0:0 -> #0:0 (aac (native) -> flac (native))
Press [q] to stop, [?] for help
video:0kB audio:70008kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.011652%

Start:    20:00:58
End:      20:00:59
Duration: 00:00:01

General
Complete name         : D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.flac
Format                : FLAC
Format/Info           : Free Lossless Audio Codec
File size             : 68.4 MiB
Duration              : 6mn 45s
Overall bit rate mode : Variable
Overall bit rate      : 1 413 Kbps
Writing application   : Lavf57.28.100
major_brand           : isom
minor_version         : 1
compatible_brands     : isom
Audio
Format                : FLAC
Format/Info           : Free Lossless Audio Codec
Duration              : 6mn 45s
Bit rate mode         : Variable
Bit rate              : 1 413 Kbps
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 KHz
Bit depth             : 24 bits
Stream size           : 68.4 MiB (100%)
Writing library       : Lavf57.28.100

------------------------------------------------------------
            Audio encoding using eac3to 3.31 x86
------------------------------------------------------------

"C:\Program Files\StaxRip\Apps\eac3to\eac3to.exe" "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle.flac" "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle_out2.m4a" -quality=0.35 -normalize -downStereo -progressnumbers

FLAC, 2.0 channels, 0:06:46, 24 bits, 1413kbps, 48kHz
Decoding FLAC...
Writing WAV...
Creating file "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle_out2.m4a.pass1.wav"...
The original audio track has a constant bit depth of 24 bits.
Starting 2nd pass...
Reading WAV...
Reducing depth from 64 to 32 bits...
Encoding AAC <0.35> with NeroAacEnc...
Applying -0.09dB gain...
The processed audio track has a constant bit depth of 32 bits.
eac3to processing took 10 seconds.
Done.

Start:    20:00:59
End:      20:01:10
Duration: 00:00:10

General
Complete name         : D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359 ID2 English SoundHandle_out2.m4a
Format                : MPEG-4
Format profile        : Base Media / Version 2
Codec ID              : mp42 (M4A /mp42/isom)
File size             : 5.27 MiB
Duration              : 6mn 46s
Overall bit rate mode : Variable
Overall bit rate      : 109 Kbps
Encoded date          : UTC 2016-04-13 17:01:02
Tagged date           : UTC 2016-04-13 17:01:10
Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : LC
Codec ID              : 40
Duration              : 6mn 46s
Bit rate mode         : Variable
Bit rate              : 107 Kbps
Maximum bit rate      : 120 Kbps
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 48.0 KHz
Frame rate            : 46.875 fps (1024 spf)
Compression mode      : Lossy
Stream size           : 5.19 MiB (99%)
Writing library       : Nero AAC codec 1.5.4.0
Encoding settings     : -q 0.35
Encoded date          : UTC 2016-04-13 17:01:02
Tagged date           : UTC 2016-04-13 17:01:10
Menu

------------------------------------------------------------
             Encoding using QSVEncC 2.44v2 x64
------------------------------------------------------------

"C:\Program Files\StaxRip\Apps\QSVEncC\QSVEncC64.exe" --codec hevc --fallback-rc --cqp 24:26:27 -i "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359.avs" -o "D:\ProgRamlar & OyunLar\ProGraMlaR_ReSiMleR\resimler&Videolar\OnePlus One videolar\VID_20150125_143359_temp\VID_20150125_143359_out.hevc"

Failed to load hw hevc encoder.
hevc encoding is not supported on current platform.
QSVEncC.exe finished with error!

------------------------------------------------------------
          Error Encoding using QSVEncC 2.44v2 x64
------------------------------------------------------------

Encoding using QSVEncC 2.44v2 x64 failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Yanlış işlev.

Failed to load hw hevc encoder.
hevc encoding is not supported on current platform.
QSVEncC.exe finished with error!

Start:    20:01:11
End:      20:01:11
Duration: 00:00:00

**Comment by Arcanemagus** [comment]
```
Failed to load hw hevc encoder.
hevc encoding is not supported on current platform.
```

Looks like you need to switch to using the software encoder as hardware encoding isn't supported on your system.
