### ISSUE TITLE
Error using script 

### ISSUE THREAD

**Issue by KayOs-GFX** [stax76/StaxRip#59]
-----------------------------------------------------------
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

------------------------------------------------------------
                        Environment
------------------------------------------------------------

StaxRip x64 : 1.3.4.0
OS          : Windows 7 Ultimate
Language    : English (United Kingdom)
CPU         : Intel(R) Core(TM)2 Quad  CPU   Q9550  @ 2.83GHz
GPU         : NVIDIA Quadro 4000

------------------------------------------------------------
                         Exception
------------------------------------------------------------

System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.ScriptOptions' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Reflection.ProcessorArchitecture' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver..ctor(ImmutableArray`1 searchPaths, String baseDirectory)
   at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.get_Default()
   at StaxRip.Scripting.VB$StateMachine_7_RunCSharpAsync.MoveNext() in D:\Projekte\GitHub\staxrip\General\Scripting.vb:line 15
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at StaxRip.Scripting.RunCSharp(String code) in D:\Projekte\GitHub\staxrip\General\Scripting.vb:line 11
   at StaxRip.GlobalCommands.ExecuteScriptFile(String filepath) in D:\Projekte\GitHub\staxrip\General\Misc.vb:line 2733
   at StaxRip.MainForm._Closure$__262-0._Lambda$__0() in D:\Projekte\GitHub\staxrip\Forms\MainForm.vb:line 1187
   at StaxRip.UI.ActionMenuItem.OnClick(EventArgs e) in D:\Projekte\GitHub\staxrip\UI\Menu Types.vb:line 460
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
---> (Inner Exception #0) System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.ScriptOptions' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver' threw an exception. ---> System.TypeLoadException: Could not load type 'System.Reflection.ProcessorArchitecture' from assembly 'System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
   at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver..ctor(ImmutableArray`1 searchPaths, String baseDirectory)
   at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.CodeAnalysis.Scripting.ScriptOptions.get_Default()
   at StaxRip.Scripting.VB$StateMachine_7_RunCSharpAsync.MoveNext() in D:\Projekte\GitHub\staxrip\General\Scripting.vb:line 15<---

**Comment by stax76** [comment]
Hello,

I think scripting needs at least .NET 4.6.1, what version do you currently have?

https://www.microsoft.com/en-us/download/details.aspx?id=49981

**Comment by KayOs-GFX** [comment]
Hi I have the latest NET 4.6.1 installed & Plus  I did a complete uninstall of the other software as advised  just to make sure  all  was installed correctly - then checked all apps to see if they were OK YES they were & stil if I  run the script or not it crashes while extracting the audio & now the windows system error popup -- so no error reports are being saved to show you  - it is very strange as I use staxrip x265 ver 1.2 all the time with no errors any help is appreciated thanks

**Comment by KayOs-GFX** [comment]
Sorry for my late reply real life got in the way ;))

**Comment by KayOs-GFX** [comment]
"E:\01 New Projects\StaxRip_x64_1.3.4.0_stable\Apps\AVSMeter\AVSMeter64.exe" ""
pause

-----------------------------------------------------------
      _________ __                __________.__        
     /   _____//  |______  ___  __\______   \__|_____  
     \_____  \\   __\__  \ \  \/  /|       _/  \____ \ 
     /        \|  |  / __ \_>    < |    |   \  |  |_> >
    /_______  /|__| (____  /__/\_ \|____|_  /__|   __/ 
            \/           \/      \/       \/   |__|   

------------------------------------------------------------
                        Environment
------------------------------------------------------------

StaxRip x64 : 1.3.4.0
OS          : Windows 7 Ultimate
Language    : English (United Kingdom)
CPU         : Intel(R) Core(TM)2 Quad  CPU   Q9550  @ 2.83GHz
GPU         : NVIDIA Quadro 4000

------------------------------------------------------------
                   Source file MediaInfo
------------------------------------------------------------

E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA.mkv

General
Unique ID                : 197711890733283659962948046271182224463 (0x94BDECD18C8EDA958C152014671B3C4F)
Complete name            : E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA.mkv
Format                   : Matroska
Format version           : Version 4 / Version 2
File size                : 222 MiB
Duration                 : 46mn 46s
Overall bit rate         : 664 Kbps
Movie name               : PSArips.com | Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA
Encoded date             : UTC 2016-04-09 12:50:09
Writing application      : mkvmerge v9.0.1 ('Obstacles') 64bit
Writing library          : libebml v1.3.3 + libmatroska v1.4.4
Video
ID                       : 1
Format                   : HEVC
Format/Info              : High Efficiency Video Coding
Format profile           : Main@L3.1@Main
Codec ID                 : V_MPEGH/ISO/HEVC
Duration                 : 46mn 46s
Bit rate                 : 594 Kbps
Width                    : 1 280 pixels
Height                   : 720 pixels
Display aspect ratio     : 16:9
Frame rate mode          : Constant
Frame rate               : 23.976 (24000/1001) fps
Color space              : YUV
Chroma subsampling       : 4:2:0
Bit depth                : 8 bits
Bits/(Pixel*Frame)       : 0.027
Stream size              : 199 MiB (89%)
Default                  : Yes
Forced                   : No
Color range              : Limited
Color primaries          : BT.709
Transfer characteristics : BT.709
Matrix coefficients      : BT.709
Audio
ID                       : 2
Format                   : AAC
Format/Info              : Advanced Audio Codec
Format profile           : HE-AAC / LC
Codec ID                 : A_AAC
Duration                 : 46mn 46s
Bit rate                 : 68.5 Kbps
Channel(s)               : 2 channels
Channel positions        : Front: L R
Sampling rate            : 48.0 KHz / 24.0 KHz
Frame rate               : 23.438 fps (1024 spf)
Compression mode         : Lossy
Delay relative to video  : -105ms
Stream size              : 22.9 MiB (10%)
Title                    : Stereo
Default                  : Yes
Forced                   : No
Text
ID                       : 3
Format                   : UTF-8
Codec ID                 : S_TEXT/UTF8
Codec ID/Info            : UTF-8 Plain Text
Duration                 : 46mn 28s
Bit rate                 : 53 bps
Count of elements        : 502
Stream size              : 18.3 KiB (0%)
Default                  : Yes
Forced                   : No

------------------------------------------------------------
           Demux audio using mkvextract 9.0.1 x64
------------------------------------------------------------

"E:\01 New Projects\StaxRip_x64_1.3.4.0_stable\Apps\MKVToolNix\mkvextract.exe" tracks "E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA.mkv" 1:"E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.aac" --ui-language en

Extracting track 1 with the CodecID 'A_AAC' to the file 'E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.aac'. Container format: raw AAC file with ADTS headers

Start:    03:38:35
End:      03:40:55
Duration: 00:02:20

General
Complete name         : E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.aac
Format                : ADTS
Format/Info           : Audio Data Transport Stream
File size             : 23.4 MiB
Overall bit rate mode : Variable
Audio
Format                : AAC
Format/Info           : Advanced Audio Codec
Format version        : Version 4
Format profile        : Main
Bit rate mode         : Variable
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 24.0 KHz
Frame rate            : 23.438 fps (1024 spf)
Compression mode      : Lossy
Stream size           : 23.4 MiB (100%)

------------------------------------------------------------
           Mux AAC to M4A using MP4Box 0.6.0 x64
------------------------------------------------------------

"E:\01 New Projects\StaxRip_x64_1.3.4.0_stable\Apps\MP4Box\MP4Box.exe" -add "E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.aac:name= " -new "E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.m4a"

AAC ADTS import  - sample rate 24000 - MPEG-4 audio - 2 channels
Setting up iTunes/iPod file...
Saving E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.m4a: 0.500 secs Interleaving

General
Complete name         : E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID2 -105ms.m4a
Format                : MPEG-4
Format profile        : Apple audio with iTunes info
Codec ID              : M4A  (isom/M4A /mp42)
File size             : 23.2 MiB
Duration              : 46mn 46s
Overall bit rate mode : Variable
Overall bit rate      : 69.4 Kbps
Encoded date          : UTC 2016-04-24 02:40:59
Tagged date           : UTC 2016-04-24 02:40:59
Audio
ID                    : 1
Format                : AAC
Format/Info           : Advanced Audio Codec
Format profile        : Main
Codec ID              : 40
Duration              : 46mn 46s
Bit rate mode         : Variable
Bit rate              : 68.5 Kbps
Maximum bit rate      : 111 Kbps
Channel(s)            : 2 channels
Channel positions     : Front: L R
Sampling rate         : 24.0 KHz
Frame rate            : 23.438 fps (1024 spf)
Compression mode      : Lossy
Stream size           : 22.9 MiB (99%)
Title                 : 
Encoded date          : UTC 2016-04-24 02:40:59
Tagged date           : UTC 2016-04-24 02:41:38

Start:    03:40:55
End:      03:41:43
Duration: 00:00:47


------------------------------------------------------------
         Demux subtitles using mkvextract 9.0.1 x64
------------------------------------------------------------

"E:\01 New Projects\StaxRip_x64_1.3.4.0_stable\Apps\MKVToolNix\mkvextract.exe" tracks "E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA.mkv" 2:"E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID3 Undetermined.srt" --ui-language en

Extracting track 2 with the CodecID 'S_TEXT/UTF8' to the file 'E:\Downloads01\Banshee.S04E01.HDTV.x264-KILLERS[ettv]\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA_temp\Banshee.S04E02.720p.HDTV.2CH.x265.HEVC-PSA ID3 Undetermined.srt'. Container format: SRT text subtitles

Start:    03:41:43
End:      03:44:28
Duration: 00:02:45


that is as far as it gets folks any help please I will check in every day I want to get this to work it has to be something simple :))

**Comment by stax76** [comment]
Problem might be .NET incompatible with your CPU.

                    Environment

StaxRip x64 : 1.3.4.0
OS : Windows 7 Ultimate
Language : English (United Kingdom)
**CPU : Intel(R) Core(TM)2 Quad CPU Q9550 @ 2.83GHz**
GPU : NVIDIA Quadro 4000

                     Exception

System.AggregateException: One or more errors occurred. ---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.ScriptOptions' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver' threw an exception. ---> **System.TypeLoadException: Could not load type 'System.Reflection.ProcessorArchitecture' from assembly 'System.Runtime, Version=4.0.0.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.
at Microsoft.CodeAnalysis.Scripting.Hosting.RuntimeMetadataReferenceResolver..ctor(ImmutableArray

**Comment by KayOs-GFX** [comment]
Problem might be .NET incompatible with your CPU. could explain this in more details is there a way around this thanks

**Comment by stax76** [comment]
I can't tell much more, you can try to make a bug report here:

https://github.com/dotnet/roslyn/issues
