### ISSUE TITLE
Hardcoded Subtitle Not Responding ( Crash )

### ISSUE THREAD

**Issue by fmohican** [stax76/staxrip#60]
After i select sub and i press Open, program crash xD
Can you fix?

========
Win 10 x64

**Comment by stax76** [comment]
Hello,

is there a log file? Where do you select what kind of subtitle?

**Comment by fmohican** [comment]
I have no logs, .ass format

**Comment by stax76** [comment]
If you can open a source file then you have a log file:

Main Menu > Tools > Log File

Main Menu > Tools > Directories > Working > *_StaxRip.log

Did you select the subtitle in the muxing dialog or at Tools > Advanced > Hardcoded Subtitle ?

Can you upload the ass file?

**Comment by fmohican** [comment]
from Tools > Advanced > Hardcoded Subtitle
I will check for logs and sure I can.

**Comment by fmohican** [comment]
There.

[subtitle.zip](https://github.com/stax76/staxrip/files/227025/subtitle.zip)

[logs.zip](https://github.com/stax76/staxrip/files/227024/logs.zip)

**Comment by stax76** [comment]
Thanks for uploading, if you open the AviSynth script (*.avs) with MPC x64 or VirtualDub x64 it freezes also, it means there is a bug in VSFilters TextSub() function.

VSFilter development is dead as far as I know so there is not much that can be done.

**Comment by fmohican** [comment]
can replace textsub with textsubmod?

**Comment by stax76** [comment]
Does it work with your file? Where can I download it?

**Comment by fmohican** [comment]
yes was work for me via your filter editor, hmm

**Comment by fmohican** [comment]
i trink you don't need to downlod something...just repace textsub with textsubmod
take look
LoadPlugin("C:\Users\Fmohican\Desktop\StaxRip\Apps\Plugins\both\ffms2\ffms2.dll")
a1=FFVideoSource("C:\Users\Fmohican\Desktop\encode\[Anime-Koi] Dansai Bunri no Crime Edge - 01 [h264-720p][DC257A3D].mkv", cachefile = "C:\Users\Fmohican\Desktop\encode\[Anime-Koi] Dansai Bunri no Cr..._temp\[Anime-Koi] Dansai Bunri no Crime Edge - 01 [h264-720p][DC257A3D].ffindex")
a2=ImageReader("E:\ws.png")
a3=ImageReader("E:\ws.png",pixel_type="RGB32").ShowAlpha(pixel_type="RGB32")
Overlay(a1,a2,x=1100,y=1,mask=a3)
TextSubMod("C:\Users\Fmohican\Desktop\encode\[Anime-Koi] Dansai Bunri no Crime Edge - 01 [h264-720p][DC257A3D].ORIGINAL.ass")

**Comment by stax76** [comment]
It says unknown function! Do you have a plugin with TextSubMod filter in your auto load plugin dir?

**Comment by stax76** [comment]
Found it here:

https://code.google.com/archive/p/vsfiltermod/downloads

**Comment by stax76** [comment]
new build is online :)

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by fmohican** [comment]
Thanks you <3 !
