### ISSUE TITLE
Including 10bits

### ISSUE THREAD

**Issue by Leinad4Mind** [stax76/StaxRip#64]
It would be great if StaxRip could include an option on the profiles so we can select 8bits or 10bits.
That way I could saved different profiles, and it will be a matter of choosing the profile of 10 bits or the profile of 8 bits.

**Comment by Arcanemagus** [comment]
This already exists, at least for x265. Are you sure that the encoder you are using _supports_ 10-bit encoding?

**Comment by Leinad4Mind** [comment]
It exist for choosing between x264 and x265 not between x264 8bit, x264 10bit, x265 8 bit and x265 10bit, and hell, why not 12bit. And thats what I wanted.
I know I can change the file manually on the staxrip folder, but the idea is to save on the profile that information and staxrip would choose from the folder the correct x264.
So that way I could have x264.exe, x264-10.exe and select an option on the profile.

**Comment by Arcanemagus** [comment]
The x265 encoder has options to select the bit-depth:
![image](https://cloud.githubusercontent.com/assets/427137/14798136/eced1f24-0aea-11e6-8d24-f6b7767c4ff1.png)

By setting that to whatever you desire and then saving an encoder profile you can create whatever settings you desire.

As far as I can tell the interface for x264 doesn't expose options for 10-bit encoding, from the help output it looks like the encoder executable itself does, so you might be able to pass in some additional options via the command line section of the configuration.

All of that can be handled by creating your own profiles _already_ though, so what are you asking for?

**Comment by Leinad4Mind** [comment]
Oh, I see. Thanks for that!

Maybe the same x265.exe can encode on all three depth. But x264 10bits version I dont know if it's able to encode on 8bits too. I normally have 2 exe one for 8bits and other for 10.

I wanted an option like that but for x264, as megui has. And that way I could select on the profile, and the staxrip would choose the correct exe.

If its possible to pass as a custom command line that would be enough for me. But I dont know which command is.

**Comment by stax76** [comment]
added to latest Test Build

https://github.com/stax76/staxrip#download
