### ISSUE TITLE
.mka audio file error

### ISSUE THREAD

**Issue by hydropunk69** [stax76/StaxRip#65]
When a mkv file is added and the audio has a .mka extension this generates an error, but if I change the extension of the file manually .mka to .flac the program works perfectly.

![captura](https://cloud.githubusercontent.com/assets/6971339/14806245/fad8add2-0b36-11e6-8384-d8c4922e5b8b.PNG)
![error](https://cloud.githubusercontent.com/assets/6971339/14806251/031f5496-0b37-11e6-8105-f072ed554053.png)

**Comment by stax76** [comment]
Hello,

> To solve problems I have to see a full log file uploaded to www.pastebin.com. pastebin has a auto expire feature which must be set to 30 days.

> If you want to obfuscate the file path I recommend to temporarily rename the file.

https://stax76.gitbooks.io/staxrip-handbook/content/

You cannot change mka extension to flac because flac uses a proprietary container format.
