### ISSUE TITLE
Set "app.Project.Size" using C# script

### ISSUE THREAD

**Issue by dudul** [stax76/StaxRip#66]
Hi,
Is there any way to set the "app.Project.Size" when using C# script?
I'm running the script after I loaded the file, but the application ignores it.

The "app.Project.TargetFile" (for example) works.

Thanks.

**Comment by stax76** [comment]
Hi,
what's the goal of your script?

Cheers,
Frank

**Comment by dudul** [comment]
I'm using the StaxRip for encode the video with hardcode subtitles.
I already have a batch script that add the subtitle filter and the subtitle file.

I want to keep the original file size (leave the audio untouched - Just mux).

**Comment by dudul** [comment]
I've also tried to add "Event command":
After Project loaded -> Parameter | Bitrate By Percent -> Percent value - 99%.

That's not working either.

**Comment by stax76** [comment]
with the latest test build this will work:

```
dynamic app = Scripting.App;
var x265 = new x265Encoder();
x265.Params.Mode.Value = 3; // two pass
var g = ShortcutModule.g;
g.LoadVideoEncoder(x265);
g.MainForm.tbTargetSize.Text = 1000.ToString();
// app.SetSize(1000); // using command engine
```

**Comment by dudul** [comment]
Thanks, works great
