### ISSUE TITLE
Compressibility check not work with unicode

### ISSUE THREAD

**Issue by Mike-83** [stax76/staxrip#67]
Hi Stax!
Thanks for your work! Your application is the best! 
And when last build added support for unicode filenames it was a very cool!

But looks like compressibility check is not supported unicode:

"CHCP" �� ���� ����७��� ��� ���譥�
��������, �ᯮ��塞�� �ணࠬ��� ��� ������ 䠩���.
x264 [error]: could not open output file `Z:\StaxRipTEMP\╨в╤А╨░╨╜╤Б╤Д╨╛╤А╨╝╨╡╤А╤Л 4 - ╨н╨┐╨╛╤Е╨░ ╨╕╤Б╤В╤А╨╡╨▒╨╗╨╡╨╜╨╕╤П IMAX Edition_temp\t_CompCheck.h264'
Script evaluation failed:
File reading exception:
[Errno 2] No such file or directory: 'Z:\StaxRipTEMP\╨в╤А╨░╨╜╤Б╤Д╨╛╤А╨╝╨╡╤А╤Л 4 - ╨н╨┐╨╛╤Е╨░ ╨╕╤Б╤В╤А╨╡╨▒╨╗╨╡╨╜╨╕╤П IMAX Edition_temp\t_CompCheck.vpy'

Error Compressibility Check

Compressibility Check failed with exit code: -1 (0xFFFFFFFF)

**Comment by stax76** [comment]
Hello Mike,

it works here, please upload the log file.

**Comment by Mike-83** [comment]
[t_StaxRip.txt](https://github.com/stax76/StaxRip/files/243490/t_StaxRip.txt)

**Comment by stax76** [comment]
comp check and normal encoding use the same function to create and execute the batch file, both works here. Maybe something is different in Russian Windows or maybe it's Windows 7 specific.

**Comment by stax76** [comment]
please try the new build:

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by Mike-83** [comment]
Error : 
Error Compressibility Check

Compressibility Check failed with exit code: -1 (0xFFFFFFFF)

x264 [error]: could not open output file `Z:\StaxRipTEMP\╤В╨╡╤Б╤В_temp\╤В╨╡╤Б╤В_CompCheck.h264'
Script evaluation failed:
File reading exception:
[Errno 2] No such file or directory: 'Z:\\StaxRipTEMP\\╤В╨╡╤Б╤В_temp\\╤В╨╡╤Б╤В_CompCheck.vpy'



StaxRip.ErrorAbortException: Compressibility Check failed with exit code: -1 (0xFFFFFFFF)

x264 [error]: could not open output file `Z:\StaxRipTEMP\╤В╨╡╤Б╤В_temp\╤В╨╡╤Б╤В_CompCheck.h264'
Script evaluation failed:
File reading exception:
[Errno 2] No such file or directory: 'Z:\\StaxRipTEMP\\╤В╨╡╤Б╤В_temp\\╤В╨╡╤Б╤В_CompCheck.vpy'


   в StaxRip.Proc.Start() в D:\Projekte\VS\VB\StaxRip\General\Proc.vb:строка 264
   в StaxRip.x264Encoder.Encode(String passName, String args, VideoScript script, ProcessPriorityClass priority) в D:\Projekte\VS\VB\StaxRip\Encoding\x264.vb:строка 65
   в StaxRip.x264Encoder.RunCompCheck() в D:\Projekte\VS\VB\StaxRip\Encoding\x264.vb:строка 113

**Comment by Mike-83** [comment]
[тест_StaxRip.txt](https://github.com/stax76/StaxRip/files/367301/_StaxRip.txt)

**Comment by Mike-83** [comment]
But if Run- cmd and then paste cmd.exe /C call "Z:\StaxRipTEMP\тест_temp\тест_encode.bat" it work!

**Comment by stax76** [comment]
When you enter chcp in cmd what does it print?

**Comment by stax76** [comment]
I've uploaded another test build, please post the log again if it still fails.

**Comment by Mike-83** [comment]
When chcp in cmd: Текущая кодовая страница 866 
[тест(1.3.8.1)_StaxRip.txt](https://github.com/stax76/StaxRip/files/367327/1.3.8.1._StaxRip.txt)

**Comment by stax76** [comment]
What's the output with this PowerShell command:

[System.Text.Encoding]::Default.CodePage

**Comment by Mike-83** [comment]
1251

**Comment by stax76** [comment]
please try if it works now:

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by Mike-83** [comment]
StaxRip-x64-1.3.8.2-test  - again error, but another look symbol. After that I did as it is written here http://magicprinc.blogspot.ru/2011/04/2011-default-cmdexe-cp1251.html  and ... yes!!! it worked!! 
But only 1.3.8.2-test.    When run StaxRip-x64-1.3.8.1-test -error.

**Comment by stax76** [comment]
I'm working on this to make things work with the default dos codepage (866 for Russia), the problem is the tools are buggy! I already made a bug report to ffmpeg and avs2pipemod, if nobody fixes the tools only thing I can do is fix them myself which will be difficult since my C++ knowledge is basic and rusty.

https://trac.ffmpeg.org/ticket/5721#ticket

https://github.com/chikuzen/avs2pipemod/issues/2

**Comment by Mike-83** [comment]
Ок, will hope that fixes the tools. And  great thanks for your work in development application!!!

**Comment by stax76** [comment]
Can this be closed now?

**Comment by Mike-83** [comment]
Hello! Yes, it works fine in Vapoursynth or in AviSynth+.
The issue can be closed. 
Many thanks!!
