### ISSUE TITLE
Support for more than two audio tracks

### ISSUE THREAD

**Issue by mxmlnkn** [stax76/staxrip#7]
I would like this as a feature.
Up until now I would have to manually encode and mux the 3rd and/or 4th audio track.

**Comment by stax76** [comment]
Hi, sorry about the late reply, I somehow missed it, I hope one day I will add support for more tracks, it's potentially a huge task, days of work.

**Comment by STaRDoGG** [comment]
@stax76  Putting in my vote for this one. =)

**Comment by panther7** [comment]
+1
