### ISSUE TITLE
 xy-VSFilter problem

### ISSUE THREAD

**Issue by Baka99** [stax76/staxrip#70]
Try using xy-VSFilter in StaxRip problem is that VSFilter (Default) does not support xy and the result is this: https://gyazo.com/8320aaa82362ae49927f9e33872d9b07.png
It should look like: https://gyazo.com/7276306a12915a320873f758769601cf.png

I tried to put xy-VSFilter 3.0.0.306 x64 by Cyberbeing in \Apps\Plugins\avs\VSFilter
I get this error: https://i.gyazo.com/1edef4b97f835ec9da660a6da184f352.png
OR
"AviSynth Error
AviSynth returned empty image data."
but the final video looks good ^^ without error so the problem is only in preview
PS: Excuse my English

**Comment by stax76** [comment]
You can try the last test build which uses VSFilterMod64.dll. The reason why xy-VSFilter don't work is a bug in xy-VSFilter. Do you know if xy-VSFilter development is dead or if there is somebody fixing bugs?

**Comment by Baka99** [comment]
I know only this https://github.com/Cyberbeing/xy-VSFilter/releases
Test v1.3.6.0 https://i.gyazo.com/30a5f45dc48d8a771cdeaf674d383992.png
and .ass here https://drive.google.com/file/d/0B5FbZFByl_7obTliQ2Z0ZzF3MU0/view

**Comment by stax76** [comment]
It don't look like there is somebody providing bug fix support.

Did you try VSFilterMod64 of the last release?

**Comment by stax76** [comment]
the latest test build uses HomeOfVapourSynthEvolution/VSFilterMod
