### ISSUE TITLE
error while hardcode srt subtitle

### ISSUE THREAD

**Issue by ahmedflix25** [stax76/StaxRip#77]
i get this error while trying to burn srt (arabic windows) subtitle file into the video 
x265 with three pass
http://pastebin.com/333QeaRj

**Comment by stax76** [comment]
MP4Box cannot mux the SRT file:
```
Timed Text (SRT) import - text track 848 x 480, font Serif (size 18)
Invalid UTF data (line 6)
```
You hardcode a subtitle and then mux the exact same subtitle as well, is this on purpose? Why?

**Comment by ahmedflix25** [comment]
it's not me the new version from the program do that with any srt subtitle when i burn it into the video

**Comment by stax76** [comment]
By default StaxRip auto loads audio and subtitle files, was the SRT file simply auto loaded? In that case you can disable it in the container options dialog.

**Comment by ahmedflix25** [comment]
no it was a separate file if it was softsub it was going to show up at demuxing window

by the way if there is a softsub file with the video the program at demuxing window should ask me to burn it into the video or leave it as softsub now it just leave it as it is with no option to hardcode it
http://i.imgur.com/VJaF5vE.png

**Comment by stax76** [comment]
I have a hard time to understand your problem, please provide more detailed and clearer descriptions in the future otherwise it will be difficult for us.

Again, separate subtitle files get auto loaded by default, you can disable them in the container options dialog.

**Comment by ahmedflix25** [comment]
about my problem 
http://imgur.com/ja4QDfa
but i think you mean the program auto load them like video players when it have the same name as the video file or some thing

my suggestion 
http://imgur.com/q7eLz9F
