### ISSUE TITLE
Taskbar progress

### ISSUE THREAD

**Issue by regs01** [stax76/StaxRip#78]
May it have support for taskbar progressbar that has been introduced with Windows 7. Will have some visual feedback of current progress and completion.

![](http://www.codeproject.com/KB/winsdk/Win7NewFeatures/ProgressBar3.png)

**Comment by stax76** [comment]
I'll investigate it, since it's something bigger though probably not before end of the year.

**Comment by regs01** [comment]
there is a bit of stuff for vb for investigation
http://www.dreamincode.net/forums/topic/163162-show-progress-bar-progress-on-windows-taskbar-win7-only/

**Comment by stax76** [comment]
It's available in the next build.
