### ISSUE TITLE
one-pass Xvid size output

### ISSUE THREAD

**Issue by batmman8** [stax76/staxrip#8]
Hi,
when i encoding Xvid format, i can´t change the final video size with one-pass Xvid codec like in the old Staxrip releases. It works only with 2-pass method.
![untitled](https://cloud.githubusercontent.com/assets/14978744/10281682/8c929e60-6b76-11e5-912d-14cc1409076b.jpg)
Sorry for my english an thanks for your work 
Mirko

**Comment by stax76** [comment]
Hello Mirko,

xvid encraw probably has a CBR mode but StaxRip don't has a profile for it, making a profile is very simple, for help please ask in the forum:

https://github.com/stax76/staxrip/wiki/Support

-Frank
