### ISSUE TITLE
Components of StaxRip 1.3.7.0 are detected as Malware by Windows Defender (Win10)

### ISSUE THREAD

**Issue by pessimism** [stax76/staxrip#81]
See attached screenshot
<img width="571" alt="malwaredetection" src="https://cloud.githubusercontent.com/assets/4689702/16177264/e1a654de-35f4-11e6-843d-17e5195bb4e2.PNG">

**Comment by Arcanemagus** [comment]
What are the SHA-1 sums of those files? None of the 1.3.7.0 files trigger a warning for me.

For reference, here is what I have on my system:

* qaac64.exe: `53F61382BB52C05B2D4B479940D53978BEC3F2DB`
* refalac64.exe: `D937B972FE38C11B3B91111409F87578BA91760B`

**Comment by stax76** [comment]
Did you download StaxRip here from github or somewhere else?

**Comment by DZmaniac** [comment]
I have noticed the same thing. I downloaded it from here on github.

**Comment by stax76** [comment]
> qaac64.exe: 53F61382BB52C05B2D4B479940D53978BEC3F2DB 

I get the same hash but cannot reproduce it with Windows Defender and up-to-date virus definitions.

**Comment by Arcanemagus** [comment]
@DZmaniac What are the SHA-1 sums of your local files?

**Comment by pjfoley** [comment]
I just installed (via Github downloaded x64 version) on a fresh Windows 10 installation with upto date Windows Defender virus and spyware definitions.

Windows Defender provided these details:
Definitions created on: 9/9/2016 at 2030
Definitions last updated: 10/9/2016 at 2104
Virus Definitions version: 1.227.1988.0
Spyware Definitions version: 1.227.1988.0

Checksums:
dd065fd39500af1f4a37f0ae80c9153d21b8ab93  StaxRip-x64-1.3.7.0-stable.7z
53f61382bb52c05b2d4b479940d53978bec3f2db  Apps/qaac/qaac64.exe

Hope it helps.
