### ISSUE TITLE
Exception Error

### ISSUE THREAD

**Issue by rkolja** [stax76/StaxRip#82]
Hi,

since version 1.3.7.0, I receive an exception error. Find attached files for detailed information.

Is it a problem of my PC config?
I already tried the unstable release v1.3.7.x - unfortunately the same error. :-(

Any tips? :-)
Thank you!

BR,
rkolja

![2016-06-19 15_04_21-staxrip x64 - log](https://cloud.githubusercontent.com/assets/15999412/16177496/96000eb8-362f-11e6-9ae9-f6d388b3dbc6.png)
Detailed error message:
[Stax64_ERROR.txt](https://github.com/stax76/StaxRip/files/322312/Stax64_ERROR.txt)

**Comment by stax76** [comment]
Which version of the test build did you try?

**Comment by rkolja** [comment]
Hmmm...let me lie...
Version 1.3.7.3, I think?
The Version that is currently downloadable from your gdrive.
Am 19.06.2016 20:56 schrieb "stax76" <notifications@github.com>:

**Comment by stax76** [comment]
Try 1.3.7.4

**Comment by rkolja** [comment]
**Update:**
I tried Testbuild 1.3.7.5. Now it works - no error message. It works fine now.

Thank you!

Cheers
rkolja
