### ISSUE TITLE
Job froze/stop progressing when using Nvidia H.264 with NVEnc(avcuvid native/cuda) decoders

### ISSUE THREAD

**Issue by nhantrn** [stax76/StaxRip#83]
When using Nvidia H.264 encoding with NVEnc(avcuvid native/cuda) decoders, the job would not finish encoding. It gets stuck when almost finishing job (e.g at 92% and sometime at 100%) and does nothing else until I have to abort it. I'm running it on a laptop with Nvidia GTX 960M.

**Comment by stax76** [comment]
It's unlikely a bug in StaxRip, you can try to mail the NVEncC author.
