### ISSUE TITLE
Non-english characters in file name (x265 encoding - all profiles)

### ISSUE THREAD

**Issue by noblemd00** [stax76/staxrip#87]
Error Encoding video using x265 1.9+200 x64 multi lib 8/10/12 bit

Encoding video using x265 1.9+200 x64 multi lib 8/10/12 bit failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

L:\219.D¢d Kalm_temp\219.D¢d Kalm.x265.avs: No such file or directory
x265 [error]: unable to open input file <->

StaxRip.ErrorAbortException: Encoding video using x265 1.9+200 x64 multi lib 8/10/12 bit failed with exit code: 1 (0x1)

The exit code might be a system error code: STATUS_WAIT_1

The exit code might be a system error code: Incorrect function.

L:\219.D¢d Kalm_temp\219.D¢d Kalm.x265.avs: No such file or directory
x265 [error]: unable to open input file <->

   at StaxRip.Proc.Start()
   at StaxRip.x265Encoder.Encode(String passName, String batchCode, ProcessPriorityClass priority)
   at StaxRip.x265Encoder.Encode()
   at StaxRip.MainForm.Encode()
   at StaxRip.MainForm.RunJobRecursive()

---

Temp folder listing:

```
       Size Name                                            Created

    3.22 KB 219.Død Kalm.ffindex                        Today 09:38
     252 KB 219.Død Kalm ID2 34ms English.m4a           Today 09:38
  181 bytes 219.Død Kalm.x265.avs                       Today 09:38
    33.4 KB 219.Død Kalm.x265.srip                      Today 09:38
  264 bytes 219.Død Kalm.x265_encode.bat                Today 09:39
  153 bytes 219.Død Kalm.x265_Source.avs                Today 09:38
    9.51 KB 219.Død Kalm.x265_StaxRip.log               Today 09:38
```

**Comment by stax76** [comment]
Which Windows version do you use? On Windows 10 it works.

**Comment by noblemd00** [comment]
Microsoft Windows 10 Professional 64-bit 

Named another (test) file - just in case  - and tried again - got same error.

[Død.Kalm.x264.x265_StaxRip.txt](https://github.com/stax76/StaxRip/files/365905/Dod.Kalm.x264.x265_StaxRip.txt)

Changed name from Død.Kalm.x264.mkv to Dod.Kalm.x264.mkv and the file encoded without error.

[Dod.Kalm.x264.x265_OK_StaxRip.txt](https://github.com/stax76/StaxRip/files/365916/Dod.Kalm.x264.x265_OK_StaxRip.txt)

**Comment by stax76** [comment]
please try the new build:

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by noblemd00** [comment]
Død.Kalm.x264.mkv still creates an error -

The new build appears to change the file name non-english character in the file name (Død.Kalm.x264) it's looking for - as evidenced by the line:

D:\~Conv Temp\~Temp\Dod.Kalm.x264_temp\Dod.Kalm.x264_new.avs: No such file or directory
x265 [error]: unable to open input file <->

but only after it has created the temp folder and files. 

BTW: also experienced the same error with a file containing the "%" character. 

[Død.Kalm.x264_new_StaxRip.log.txt](https://github.com/stax76/StaxRip/files/367297/Dod.Kalm.x264_new_StaxRip.log.txt)

**Comment by stax76** [comment]
When you enter chcp in cmd what does it print? In Germany it's:

C:\Users\Frank>chcp
Aktive Codepage: 850.

**Comment by stax76** [comment]
I've uploaded another test build, please post the log again if it still fails.

**Comment by noblemd00** [comment]
Active code page: 437
(US-OEM)

New test build works ok - x264 to x265 re-encode.

[Død.Kalm.x264_new_StaxRip.log.txt](https://github.com/stax76/StaxRip/files/367833/Dod.Kalm.x264_new_StaxRip.log.txt)

**Comment by stax76** [comment]
I've committed the source code, I will have to change it however because of:

https://github.com/stax76/StaxRip/issues/67

**Comment by noblemd00** [comment]
Not sure if this is related to the changes you made. The files go all the way through encoding and when the final mux is supposed to occur there is an error finding file. 

This is the file name to be re-encoded: 0207.Home Part 2

0207.Home, Part 2_temp    (note the extra character after Home)

           Size Name                                            Created

         306 KB 0207.Home, Part 2.ffindex                   Today 12:12
        43.3 KB 0207.Home, Part 2.srip                      Today 12:07
         472 MB 0207.Home, Part 2 ID2 English Englis...     Today 12:11
        31.8 MB 0207.Home, Part 2 ID2 English Englis...     Today 12:12
      222 bytes 0207.Home, Part 2.x265.avs                  Today 12:12
      325 bytes 0207.Home, Part 2.x265_NVEncC.bat           Today 12:14
         343 MB 0207.Home, Part 2.x265_out.h265             Today 12:14
      220 bytes 0207.Home, Part 2.x265_Source.avs           Today 12:12
        28.7 KB 0207.Home, Part 2.x265_StaxRip.log          Today 12:11
        1.80 KB 0207.Home, Part 2_Chapters.xml              Today 12:12

[0207.Home, Part 2.x265_StaxRip.log.txt](https://github.com/stax76/StaxRip/files/369692/0207.Home.Part.2.x265_StaxRip.log.txt)

**Comment by stax76** [comment]
--title ""Home: Part 2""

You probably entered quotation marks in the title in the muxing options causing this issue, next build will replace " with '

**Comment by noblemd00** [comment]
This was a folder batch add - I did not enter or change the names.

**Comment by stax76** [comment]
Sorry, it was taken from the source, the log shows it's in the source, next build takes care of it.

```
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
                   Source file MediaInfo
-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-

D:\Conv\Battlestar Galactica\0207.Home, Part 2.mkv

General
Complete name               : D:\Conv\Battlestar Galactica\0207.Home, Part 2.mkv
Format                      : Matroska
Format version              : Version 4 / Version 2
File size                   : 3.22 GiB
Duration                    : 43mn 44s
Overall bit rate            : 10.5 Mbps
Movie name                  : "Home: Part 2"
```

**Comment by noblemd00** [comment]
Just so you know I did recompile the source after changing _new to .x265
in
tbTargetFile.Text = Filepath.GetDirAndBase(p.TargetFile) + ".x265" + Filepath.GetExtFull(p.TargetFile)

**Comment by stax76** [comment]
with the last build 1.3.8.7 there is a much better way:

![unbenannt](https://cloud.githubusercontent.com/assets/11410540/16929922/395558f4-4d3a-11e6-8c81-2e47e8aed1d5.png)

https://github.com/stax76/staxrip/blob/master/md/test-build.md

**Comment by noblemd00** [comment]
Excellent - Thanks

Haven't said it yet - Great program!

**Comment by stax76** [comment]
Can this be closed now or is there still an issue?

**Comment by noblemd00** [comment]
Yes, close - thought stax76 closed a long time ago???
