### ISSUE TITLE
Video Comparison overwriting log

### ISSUE THREAD

**Issue by noblemd00** [stax76/StaxRip#88]
When using Video Comparison, it overwrites the temp file log of whatever is the currently active file in StaxRip regardless of what files are compared. 

Example:
xyz.mkv was just re-encoded using StaxRip.
Video Comparison is used to compare abc1.mkv to abc2.mkv.
xyz.mkv_temp folder log file xyz_new_StaxRip.log is overwritten with the log data from abc2.mkv created when abc2.mkv loaded into Video Comparison.

**Comment by stax76** [comment]
fixed in the last test build
