### ISSUE TITLE
_VCEEncC.bat missing VCEEncC64 executable name and location

### ISSUE THREAD

**Issue by JustDobby** [stax76/staxrip#89]
Hi, 

To start - thank you for a great program! 

But ever since version 1.3.8.1 (1.3.8.1, 1.3.8.5 and 1.3.8.7 anyway) it is impossible (for me anyway) to use StaxRip to re-encode files with VCEEncC64 .. everything starts out ok, but in the generated batchfile the pathname to the executable is missing, it starts out  with the "--quality" option, as in
# -----------------------------------

@echo off
--quality slow --profile High --bframes 3 --b-pyramid --cqp 22:24:27 -i "D:\Wrk\Current\Visiting Hours (1982)_temp\Visiting Hours (1982)_new.avs" -o "D:\Wrk\Current\Visiting Hours (1982)_temp\Visiting Hours (1982)_new_out.h264"
# ------------------------------------

Previous versions (at least up to 1.3.7.8 inclusive) were ok in this regard...

Running W10Pro 1511 in a TSC session.

When checking the settings (Apps->Manage...) things are ok, a valid path to the executable is displayed with the correct version number (which should make sense since the included binary is used)

![staxrip_01](https://cloud.githubusercontent.com/assets/6625863/16961282/107c3bba-4ded-11e6-94e2-ec35e5a12bab.png)

Any ideas?? - I will include the logfile (renamed .txt) just in case anyway, though not much path things in there....
[Visiting Hours (1982)_new_StaxRip.txt](https://github.com/stax76/StaxRip/files/372108/Visiting.Hours.1982._new_StaxRip.txt)

Anything else I could/should try?

**Comment by stax76** [comment]
I think this was fixed meanwhile in test builds so I close it.
