### ISSUE TITLE
Wrong arguments passed to VCEEncC64.exe

### ISSUE THREAD

**Issue by bj73** [stax76/staxrip#9]
Hi, I'd like to report the following error, unrecognised *--input* and *--output* arguments in line 1803 of VideoEncoder.vb.

According to help file it should be:

*--input-file* or *-i*
*--output-file* or *-o*

Error output:
------------------------------------------------------------
                   Encoding using VCEEncC
------------------------------------------------------------

"P:\StaxRip_x64_1.3.1.7_beta\Apps\VCEEncC\VCEEncC64.exe" --cqp 22:24:27 --input "X:\test.avs" --output "X:\test_out.h264"

Unknow Options: "--input"

------------------------------------------------------------
                Error Encoding using VCEEncC
------------------------------------------------------------

Encoding using VCEEncC failed with error code 1

Unknow Options: "--input"

**Comment by stax76** [comment]
Hi,

thanks for the report, IIRC I've fixed and uploaded it, test version is here:

https://www.mediafire.com/folder/0jakce45o99kb/StaxRip

I hope it works.
