### ISSUE TITLE
cuvid: Failed cuvidCreateDecoder 2 (CUDA_ERROR_OUT_OF_MEMORY)

### ISSUE THREAD

**Issue by noblemd00** [stax76/staxrip#90]
Not sure if this is a StaxRip error or a NVIDIA error. 

[WaywardPines_Test_error.txt](https://github.com/stax76/StaxRip/files/376002/WaywardPines_Test_error.txt)
[Wayward.Pines.test_new_StaxRip.log.txt](https://github.com/stax76/StaxRip/files/376003/Wayward.Pines.test_new_StaxRip.log.txt)

Works ok with AVISynth/VaporSynth setting.

6.5 MB test file 

http://aerobytepc.com/wp-content/uploads/2016/07/Wayward.Pines_.test_.mkv

**Comment by stax76** [comment]
There is a problem with this sample and using nvencc as decoder instead of avs/vs, you can find the email address of the author here:

http://rigaya34589.blog135.fc2.com/blog-category-17.html
