### ISSUE TITLE
Unhandled excepiton (error)

### ISSUE THREAD

**Issue by fmohican** [stax76/staxrip#94]
Hello,
i got an error with our new update.
I try to reinstall .NET Framework but... nothing xD
can you take a look ?
as side mention, if i ignore this error video will be encoded successfully.

edit: On your beta version all are fine,

[error.txt](https://github.com/stax76/StaxRip/files/394243/error.txt)
![untdfsafsaitled](https://cloud.githubusercontent.com/assets/8583317/17300362/c1d51530-581a-11e6-8de7-526340c38b25.png)

**Comment by dhimanAdhikari** [comment]
I am having the same problem when trying to batch/queue encode.
If I ignore this error, will it encode all without a problem?

**Comment by fmohican** [comment]
@dhimanAdhikari yes if you ignore error all encode will be done without problem.

**Comment by stax76** [comment]
Was this solved in recent test builds?

**Comment by fmohican** [comment]
yap
