### ISSUE TITLE
%source_dir% incorrect when using UNC paths

### ISSUE THREAD

**Issue by Dave--G** [stax76/staxrip#95]
Setting Project Settings / Default Target Directory to "%source_dir%\" results in converted file being incorrectly written to C:\SERVER_NAME\SHARE\PATH\ folder on local system instead of \SERVER_NAME\SHARE\PATH\ on server as intended.

Reason:  Leading "\" UNC path qualifier is apparently missing in %source_dir% variable.

**Comment by stax76** [comment]
Next build will have some UNC fixes.
