### ISSUE TITLE
Advanced Media Framework

### ISSUE THREAD

**Issue by wakywarez** [stax76/staxrip#96]
AMD x.265 or open CL x.265
http://gpuopen.com/gaming-product/advanced-media-framework/

**Comment by Brainiarc7** [comment]
To rephrase your vague question:

Does StaxRip support AMD VCE's HEVC encode capabilities on supported hardware?

**Comment by Brainiarc7** [comment]
If this feature were supported, you'd require to have at least a VCE 3.0+ capable GPU, see this entry for [more](https://en.wikipedia.org/wiki/Video_Coding_Engine) information.

At the moment, I'm only aware of the current H.264 VCE-based implementation that's supported on Staxrip.

**Comment by wakywarez** [comment]
If I have the a10 7850k and it goes great with the AMD x.264, I plan to buy the rx 480 for x.265 so I ask if there is or there will be compatibility, but to buy a gtx1060 and use nvenc

**Comment by Brainiarc7** [comment]
If this feature were supported, you'd require to have at least a VCE 3.0+ capable GPU, see this entry for [more](https://en.wikipedia.org/wiki/Video_Coding_Engine) information.

At the moment, I'm only aware of the current H.264 VCE-based implementation that's supported on Staxrip.

**Comment by wakywarez** [comment]
http://gpuopen.com/gaming-product/advanced-media-framework/

**Comment by stax76** [comment]
For GPU related issues it's better to use the doom9 staxrip thread since there are a couple of people that are well informed about the topic.

Generally staxrip supports all features of all GPU encoders, each GPU encoder has a help file for more info.
