### ISSUE TITLE
QSVEncC Intel - Checking Limit performance - Error

### ISSUE THREAD

**Issue by noblemd00** [stax76/staxrip#97]
Enabling - Limit performance to lower resource usage - creates an error indicating a value is required.  

Error: Unknown value "--cqp" for "--max-procfps"
"--max-procfps" requires value.

Start:    14:32:30
End:      14:32:30
Duration: 00:00:00

**Comment by stax76** [comment]
Which encoder is it?

**Comment by noblemd00** [comment]
Many moons ago - must have been Intel H.265. Only thing I would have used QSVEncC Intel for.
