### ISSUE TITLE
Suggestion: process audio in parallel to video

### ISSUE THREAD

**Issue by Dave--G** [stax76/staxrip#99]
I'm using a very fast GTX1080 card with NVEncc to re-encode my media library and noticed that video encoding is so fast (1080p h264 -> h265 @150-200fps) that audio processing now takes up a significant (~30%) portion of the overall processing time.

Not sure how easy / hard this would be, but a major throughput improvement could be achieved by exec'ing the audio processing steps into a 2nd process, allowing both audio & video to be processed at the same time.

Since the source is read-only process coordination might be as easy as 'wait-for' semaphore process mechanics at the final re-mux stage.

This is just a suggestion, feel free to close

**Comment by STaRDoGG** [comment]
Sounds like an interesting idea to me. The author doesn't seem real active on this project though, so I'm guessing another dev would have to chip in on the project if that were to happen.

**Comment by Dave--G** [comment]
@STaRDoGG Actually I've been playing around with various approaches and it looks pretty easy.  At least when creating a batch file to simulate what StaxRip does, it's as simple as splitting the process into separate audio & video encoding batch files after demux, running the .bat files via the start command, and using a few temp files & WAIT FOR for synchronization before re-muxing the file.  IO contention isn't bad, and output file fragmentation shouldn't be an issue since re-mux is a single process.  Achieved a 20-40% execution time reduction in the tests I ran.

It looks like StaxRip exec's it's tools out-of-proc, so it shouldn't be too hard to port this approach to a more native approach, although the toolset that StaxRip drives is pretty diverse and I have no idea how this would effect corner-cases.  The feature is probably best left to a checkbox optimization feature for advanced users who have very fast encoders and can take properly take advantage of it.

Not ready to fork and start anything though.  I'm unclear as to whether the original author would consider this a friendly or hostile fork.  (??) Would greatly prefer friendly or going with a lean-slate approach.

@Stax76, are you interested in accepting external pull requests?

**Comment by STaRDoGG** [comment]
Personally, I love to see this added as an option for users to choose. I just cloned the repo myself for a couple of other things I wanted to poke around with. It's a fairly complicated piece of software, with a lot of lines of code. 

Even the simple things, like menus for example, are custom, so it takes a bit of a learning curve to follow the flow of things before diving right in to add stuff.

**Comment by Dave--G** [comment]
Yeah, there are quite a few bugs I'd like to fix myself.  Especially the batch bitrate bug that's been around for something like 10 years.  Problem is, the workarounds work and I'm too lazy to take it on seriously.  But then I do have a lot of video to trans-code...

It's only VB, it's not really complicated.  Skim over the UI fluff and you'll be fine.

Still waiting for feedback from @Stax76 (??)

**Comment by STaRDoGG** [comment]
I've just about finished the stuff I wanted to add to it myself. I'm just going to send in the Pull request, and hope he adds it (assuming he comes around here to see it, LOL). If not, I'll at least still be able to use it on my own local copy.

I'd probably suggest the same for your fixes. Just do them, send the pull req, and see what happens. If he doesn't want them I'm sure there would be others (including myself) who'd probably merge them to their own local copies.

But, yea, the VB itself isn't the complicated part, it's the crazy flow of things he's got going on in there, LOL. If you haven't cloned it yet, and poked through it, check it out, you'll see what I mean. =)

**Comment by stax76** [comment]
Sorry for the late reply. I welcome pull requests if they are simple enough.

StaxRip was my first app I ever wrote beginning over 15 years ago and some fundamental things are designed poorly. Multi threading wasn't a big topic and ac3 audio source files were small and fast to process, like 5 minutes per audio file. Now with formats like dtsma and eac3to being also not very fast it takes longer.

This feature would probably be difficult to design, implement and test, these days I mostly maintain staxrip because I use it very rarely.

**Comment by stax76** [comment]
It's finally supported.

https://forum.doom9.org/showthread.php?p=1810725#post1810725
